- src/app/components/table/table.ts
Fixed <ins>**#13243**</ins>
Correcting the typo from propery to property
> FIX: typo on primeng-table Warning

- src/app/components/fileupload/fileupload.ts
> Fixed fileupload, now is showing multiple errors messages

- src/app/components/inputnumber/inputnumber.ts
> [#13426] - Fixed maxlength on inputNumber component

- src/app/components/tieredmenu/tieredmenu.ts
Reverts primefaces/primeng#13443
> Revert "[#13433] - Fixed double tap to open submenu in tieredmenu component"

- src/app/components/panelmenu/panelmenu.ts
> Bugfix #13401 fix panelmenu style, styleClass, tooltip and tooltipOptions propagation

- src/app/components/accordion/accordion.ts
- src/app/showcase/doc/accordion/accessibilitydoc.ts
Fix #13431
* remove role tablist
* change header role from tab to button
* added heading role to accordion header and the corrisponding level customizable via input
* updated docs
> Bugfix #13431 Fix accordion accessibility

- src/app/components/fileupload/fileupload.ts
Fix #13467 
Added 1024 base unit conversion in FileUpload Component and refactored code
> FileUpload: Added 1024 base unit conversion

- src/app/components/table/table.ts
- src/app/components/treetable/treetable.ts
> Editable Column: do not exit mode on shift enter

- src/app/components/button/button.ts
> fix(primeng/p-button): add disable class on host element

- src/app/components/calendar/calendar.ts
> fix: formarray wrongly marked as touched

- src/app/components/password/password.ts
> fix(primeng/p-password): typo in template

- src/app/components/image/image.ts
- src/app/showcase/doc/Image/imagedoc.module.ts
- src/app/showcase/doc/Image/previewimagesourcedoc.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/pages/image/imagedemo.ts
Added Preview Image Src, so in my case I will be able to use small thumbnail version of image at start and a bigger one on preview.
Resolves #12928
> (p-image) Add previewImageSrc attribute for preview image

- src/app/components/treetable/treetable.ts
Fix #13254
* Fixed the type of the selectionChange emitter in the TreeTable component.
> fix #13254 - TreeTable: selectionChange emitter type error

- src/app/showcase/layout/app.module.ts
Removed duplicated AppRoutingModule in `app.module.ts`
> Removed duplicated AppRoutingModule

- src/app/components/galleria/galleria.ts
- src/app/showcase/doc/apidoc/index.json
> feat(primeng/p-galleria): add new property for autoplay mode

- src/app/components/chips/chips.ts
> fix(primeng/p-chips): update the state of the `max` element when clear button is clicked

- src/app/components/keyfilter/keyfilter.ts
#13246 - Do not prevent Enter key when using pKeyFilter
> Fix #13246 - Do not prevent Enter key when using pKeyFilter

- src/app/components/contextmenu/contextmenu.ts
- src/app/components/panelmenu/panelmenu.ts
- src/app/components/slidemenu/slidemenu.ts
fixes #13024 for contextmenu, panelmenu and slidemenu components
> jest test fixes via forwardRef

- src/app/showcase/doc/progressspinner/styledoc.ts
Fixes #13552 minor changes in ProgressSpinner docs for showing correct class names
> docs: fix incorrect class names for ProgressSpinner

- src/app/components/dropdown/dropdown.ts
Addressing issue || #13559 
After solution video for details and test result 
[Video details of test](https://www.awesomescreenshot.com/video/20317533?key=487361804b4da54c3d5960f15d9f915f)
> fix: #13559 || DropDown filter search not trimming text and search gone empty

- src/app/components/api/treetablenode.ts
- src/app/components/treeselect/treeselect.ts
- src/app/components/treetable/treetable.interface.ts
- src/app/components/treetable/treetable.ts
Solves https://github.com/primefaces/primeng/issues/13415
> TreeTable and TreeSelect: Output emits wrong type (TreeTable.onNodeExpand and TreeSelect.onNodeUnselect and .onNodeSelect) 

- src/app/components/dataview/dataview.ts
- src/app/showcase/doc/apidoc/index.json
Adding a LazyLoadOnInit Flag to the Data View component, similar to the table and treetable component.
> Add LazyLoadOnInit flag for Data View (#12526)

- src/app/components/table/table.css
> fix: #13562 || Component: Buttons and table frozen column

- src/app/components/api/primengconfig.ts
- src/app/components/api/translation.ts
- src/app/components/api/translationkeys.ts
- src/app/components/fileupload/fileupload.ts
- src/app/showcase/doc/configuration/locale/apidoc.ts
Following the indications of @mertsincan in this comment: https://github.com/primefaces/primeng/pull/13400#issuecomment-1697703103, 
I added **filesizeTypes** and updated the docs.
> Added filesizeTypes in config

- src/app/components/confirmdialog/confirmdialog.interface.ts
- src/app/components/confirmdialog/confirmdialog.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/doc/confirmdialog/templatedoc.ts
Fixes #13700 
message and icon templates added.
> ConfirmDialog | Add missing templates (message, icon) &  update the docs

- src/app/components/tooltip/tooltip.css
> fix: fix tooltip flicker issue

- src/app/components/calendar/calendar.ts
> fix: #13662 || Calendar: Calendar is closed when month view press space

- src/app/components/slider/slider.ts
> Fix #9013 - p-slider: Slider issue with onSlideEnd event

- src/app/components/panelmenu/panelmenu.ts
> fix: #13637 || Component: Panelmenu SubMenus not supported HTML

- src/app/components/toast/toast.ts
> fix: #13707 || Toast: closeIcon on message is outside of button

- src/app/components/calendar/calendar.ts
> fix: #13695 || Calendar: disabledDate Template Broken

- src/app/components/megamenu/megamenu.ts
> Fix MegaMenu in jest using forwardRef

- src/app/components/button/button.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/doc/button/linkdoc.ts
- src/app/showcase/doc/button/outlineddoc.ts
- src/app/showcase/doc/button/raiseddoc.ts
- src/app/showcase/doc/button/raisedtextdoc.ts
- src/app/showcase/doc/button/roundeddoc.ts
- src/app/showcase/doc/button/severitydoc.ts
- src/app/showcase/doc/button/sizesdoc.ts
- src/app/showcase/doc/button/templatedoc.ts
- src/app/showcase/doc/button/textdoc.ts
> Fix #13851 - Button: New props

- src/app/components/blockui/blockui.ts
> fixed #11838 - refactor unblock method conditional in blockui

- src/app/components/tooltip/tooltip.ts
> Fixed #13866 - Revert regression of content template and refactor #13843

- src/app/components/table/table.ts
> Fixed #13875 - Add method to update styles on column drop

- src/app/components/galleria/galleria.ts
> fix: fix galleria tabbing issue

- src/app/showcase/layout/doc/codeeditor/templates.ts
> fix: fix missing ConfirmPopupModule import

- src/app/components/overlaypanel/overlaypanel.ts
> fix(overlaypanel): close overlay panel on escape key press

- src/app/components/tabview/tabview.ts
Fix #13902 TabView inkbar accessibility
> Bugfix #13902 Fix TabView inkbar accessibility

- src/app/components/button/button.ts
> fixed #13901 pButton | Loading icon problem

- src/app/components/multiselect/multiselect.ts
> Bug fix: #13942 Multi select component console error

- src/app/components/treetable/treetable.ts
> fix: eventemitter type for treetable single select

- src/app/components/contextmenu/contextmenu.ts
> Bug fix #13948 - ContextMenu with appendTo="body" doesn't close when destroyed

- src/app/showcase/pages/uikit/uikit.component.html
> Fix Preview Dark Mobile Responsive Issue

- src/app/components/dialog/dialog.ts
> Issue #13856 / Dialog: bad drag behavior when keepInViewport is false

- README.md
Fix #13685. Add Discussions badge to the README for awareness and potential SEO.
Badge in action can be viewed at: https://github.com/FlipWarthog/primeng/tree/discussions-badge
> Fix #13685: Add Discussions badge

- src/app/components/autocomplete/autocomplete.ts
> Fixed #14064 - AutoComplete | delete fix

- src/app/components/chips/chips.ts
> Fixed #14101 - Chips | Focus class fix

- src/app/components/dropdown/dropdown.ts
Fixes #14078
Video show the fix
https://github.com/primefaces/primeng/assets/45439491/ef93b7c8-9361-4fe4-9072-55b00918281c
> Fix additional case where dropdown causes panel (#14078)

- src/app/components/multiselect/multiselect.ts
Fix issue [#14134](https://github.com/primefaces/primeng/issues/14134)
> Fix issue #14134

- src/app/components/messages/messages.css
- src/app/components/toast/toast.css
> fix: fix close icon shrinks on long text

- src/app/showcase/doc/table/rowexpanddoc.ts
> Fixed #14109 - RowExpandDoc | Fixed wrong object property

- src/app/showcase/doc/table/rowexpanddoc.ts
> fix: #14109 || Error in rowexpanddoc file

- src/app/components/fileupload/fileupload.ts
> Fixed #14046 - Fileupload | Unexpected disable behavior fix

- src/app/components/contextmenu/contextmenu.ts
- src/app/showcase/doc/table/rowexpanddoc.ts
> Fix: #14006 - 16.7.0: Context Menu with appendTo="body" throws Type Error in a nested Table

- src/app/components/table/table.ts
> fix: #13672 || ColumnFilter in row mode and type date not trigger 

- src/app/showcase/doc/toolbar/templatedoc.ts
The provided code was invalid (does not compile). This PR does a small change to fix this.
> docs: broken example code in toolbar template section

- src/app/components/table/table.ts
> Table |  cell edit fix

- src/app/components/dropdown/dropdown.ts
> fix for option values of null and empty string (#14223)

- src/app/components/button/button.ts
> Bug fix: #13963 Component: Button styleClass is not being added to the <button>

- src/app/components/listbox/listbox.ts
> Fixed #14294 - Listbox | emptyMessage not working

- src/app/components/tristatecheckbox/tristatecheckbox.css
- src/app/showcase/doc/tristatecheckbox/basicdoc.ts
- src/app/showcase/doc/tristatecheckbox/reactiveformsdoc.ts
Revert PR [#13977](https://github.com/primefaces/primeng/pull/13977).
Will follow [w3School example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_checkbox)
> chore(TriStateCheckbox): Revert cursor pointer in label

- package.json
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.
> Add module

- src/app/components/picklist/picklist.ts
https://github.com/primefaces/primeng/issues/14334
Included a check to make sure that whenever a user clicks right or left, that we only remove a selected item if it is included in the filtered view.
> Issue 14334 - Make sure to only remove item if in filtered list. 

- src/app/components/multiselect/multiselect.ts
Fixes #14387
copied the required code from dropdown.ts
> multiselect.autofocusFilter fixed

- src/app/components/inputnumber/inputnumber.ts
fix: #14327, Inputnumber: Inputnumber#currency mode not allowing to remove minus sign for Dollar and INR fields.
> fix: #14327, Inputnumber: Inputnumber#currency mode not allowing to remove minus sign for Dollar and INR fields.

- src/app/components/treeselect/treeselect.ts
> Fixed #14355 - TreeSelect: Trigger Button missing aria-label

- src/app/components/utils/objectutils.ts
> primefaces/primeng#10482 Fix removing diacritics

- src/app/components/dynamicdialog/dynamicdialog-config.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
Relates to issue https://github.com/primefaces/primeng/issues/13486
#13486.
> DynamicDialog: ability to turn off autofocus on show

- src/app/components/tree/tree.css
added removed css classes for p-tree horizontal layout
Fixes #14445
> fix #14445

- src/app/showcase/doc/chart/basicdoc.ts
- src/app/showcase/doc/chart/combodoc.ts
- src/app/showcase/doc/chart/doughnutdoc.ts
- src/app/showcase/doc/chart/horizontalbardoc.ts
- src/app/showcase/doc/chart/linedoc.ts
- src/app/showcase/doc/chart/linestyledoc.ts
- src/app/showcase/doc/chart/multiaxisdoc.ts
- src/app/showcase/doc/chart/piedoc.ts
- src/app/showcase/doc/chart/polarareadoc.ts
- src/app/showcase/doc/chart/radardoc.ts
- src/app/showcase/doc/chart/stackedbardoc.ts
- src/app/showcase/doc/chart/verticalbardoc.ts
- src/app/showcase/domain/appconfig.ts
- src/app/showcase/layout/app.component.ts
- src/app/showcase/layout/app.main.component.ts
- src/app/showcase/layout/config/app.config.component.ts
- src/app/showcase/layout/doc/app.docapitable.component.ts
- src/app/showcase/layout/topbar/app.topbar.component.ts
- src/app/showcase/pages/landing/featuressection.component.ts
- src/app/showcase/pages/landing/herosection.component.ts
- src/app/showcase/pages/landing/landing.component.ts
- src/app/showcase/pages/landing/templatesection.component.ts
- src/app/showcase/pages/landing/themesection.component.ts
- src/app/showcase/pages/landing/userssection.component.ts
- src/app/showcase/pages/uikit/uikit.component.ts
- src/app/showcase/service/appconfigservice.ts
Adds stateful darkmode, includes fixes for configservice
> Stateful darkmode

- src/app/components/dropdown/dropdown.ts
> Fixed #14492 - Dropdown |  FilterBy multiple values is not working

- src/app/components/calendar/calendar.ts
the initial load now respect the dateFormat when dataType is set to "string"
Fix #14484
> fix #14484 Calendar: the initial load now respect the dateFormat

- src/app/components/autocomplete/autocomplete.ts
- src/app/showcase/doc/guides/csslayer/specificitydoc.ts
Fix #14468
- Added `string | (item: any) => string`
> Fix(AutoComplete): optionLabel input has wrong type 

- src/app/components/dropdown/dropdown.ts
fix: #14503, p-dropdown: selecting an option or clearing the value should clear the filter input
> fix: #14503, p-dropdown: selecting an option or clearing the value should clear the filter input

- src/app/showcase/demo/deferreddemo.ts
- src/app/showcase/pages/landing/herosection.component.ts
> fix: calendar showcase hidden issue

- src/app/components/splitbutton/splitbutton.ts
> fix: fix typo in splitbutton

- src/app/components/table/table.ts
Fixes #14564
| With        | Without           | 
| ------------- |:-------------:|
| <img width="642" alt="Screenshot 2024-01-16 at 11 36 56 AM" src="https://github.com/primefaces/primeng/assets/6710794/382f2b57-c297-4046-88af-b120d6eb8ca1"> | <img width="527" alt="Screenshot 2024-01-16 at 11 38 06 AM" src="https://github.com/primefaces/primeng/assets/6710794/e8f0b0ec-027c-47db-8e6d-e481421b9f30"> |
> Fix #14564 - Fix calendar popup being cropped by overflow

- src/app/components/chart/chart.ts
Fixes an issue with angular change detection firing and causing the application to crash.
> Chart component should runOutsideOfAngular

- src/app/components/chips/chips.ts
> fix: fix invalid aria attribute in chips

- src/app/components/chips/chips.ts
> fix: fix numpad enter key issue in chips

- src/app/components/calendar/calendar.ts
> Fixed #14558 - p-calendar: Doesn't close on date selection in range mode

- src/app/components/autocomplete/autocomplete.ts
> Fixed #14595 - Autocomplete | maxlength doesn't work anymore

- src/app/components/tabview/tabview.ts
TabView with scrollable throws an exception #13332
Resolving console error.
> fix #13332 tabview with scrollable exception error

- src/app/components/dropdown/dropdown.ts
> fix: placeholder not working in dropdown

- src/app/components/api/translationkeys.ts
- src/app/components/table/table.ts
Using right aria-label translation and fixing text order on hide/show.
@cetincakiroglu
> fix #14608 p-ColumnFilter aria-label

- src/app/components/inputnumber/inputnumber.ts
Fixes https://github.com/primefaces/primeng/issues/14630
#14630
> fix(#14630): emit blur after input value validation

- src/app/components/multiselect/multiselect.ts
> Fix MultiSelect: dynamic text in placeholder is not displayed fixes #14321

- src/app/components/dropdown/dropdown.ts
Reverts primefaces/primeng#14728
> Revert "Fixed #14701 - Dropdown | removing a letter from filter that comes af…"

- src/app/components/calendar/calendar.ts
Reverts primefaces/primeng#14497
> Revert "fix #14484 Calendar: the initial load now respect the dateFormat"

- src/app/components/api/translationkeys.ts
- src/app/components/multiselect/multiselect.ts
Fix for issue #14554. It is already closed, but the issue persists.
> Fix #14554

- src/app/components/multiselect/multiselect.ts
- src/app/components/utils/objectutils.ts
> Fixed #12854 - Multiselect | Multiselect with string array search not working

- src/app/components/multiselect/multiselect.ts
> Fixed #14737 - Multiselect | headerCheckboxViewChild not found

- src/app/components/treeselect/treeselect.ts
> Fixed #14764 - TreeSelect | Incorrect alignment in TreeSelect on filter

- src/app/components/listbox/listbox.ts
> Fixed #14794 - Listbox | readonly attribute no longer works

- src/app/components/autofocus/autofocus.ts
> Fixed #14745 - Calendar | Autofocus not working

- src/app/components/table/table.ts
> fix: fix select all in single selection mode on Ctrl-A press

- src/app/components/tabview/tabview.ts
> fix: #14785 rounded scrollLeft for scaled displays

- src/app/showcase/doc/theming/builtinthemesdoc.ts
> Fixed #14872 - Theming | Wrong Icon in documentation

- src/app/components/tree/tree.ts
> Fixed #14912 - Tree | ARIA attributes must conform to valid values

- src/app/components/api/primengconfig.ts
- src/app/components/api/translation.ts
- src/app/components/api/translationkeys.ts
- src/app/components/colorpicker/colorpicker.ts
> Fixed #14941 - ColorPicker | Form elements must have labels

- src/app/components/treeselect/treeselect.ts
- src/app/components/treetable/treetable.ts
> Fixed #14939 - TreeTable, TreeSelect | Fix jsdoc

- src/app/components/inputswitch/inputswitch.css
Reverts primefaces/primeng#14922
> Revert "Fixed #14921 Hiding the checkmark of InputSwitch md-dark theme"

- src/app/components/menubar/menubar.ts
> Fixed #14972 - MenuBar | Remove duplicate id

- src/app/components/table/table.ts
> Fixed #14888 - Restore reordered columns

- src/app/components/table/table.ts
Reverts https://github.com/primefaces/primeng/pull/14433
fixes #14558
fixes #14903
> Revert https://github.com/primefaces/primeng/pull/14433

- CHANGELOG.md
> fix: Numpad enter issue in Listbox

- CHANGELOG.md
> fix: Numpad enter issue in multiselect

- src/app/components/tree/tree.ts
Fixes issue https://github.com/primefaces/primeng/issues/15020
Thanks.
> Add data-id attribute on tree node element

- src/app/components/inputnumber/inputnumber.interface.ts
> Fixed #15076 - Update inputNumber event value type

- src/app/components/autocomplete/autocomplete.ts
> Fixed #15078 - Update backspace keyboard support for single selection

- src/app/components/panelmenu/panelmenu.ts
> Fixed #14893, Fixed #15057

- src/app/components/dropdown/dropdown.ts
> Fixed #15049

- src/app/components/treeselect/treeselect.ts
> Fix TreeSelect itemcheckboxicon bug

- src/app/components/chip/chip.ts
> fix #15095 Added button role

- src/app/components/steps/steps.ts
> fix #1469 Removed tablist roles

- src/app/components/confirmdialog/confirmdialog.ts
- src/app/components/dialog/dialog.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
> fix #14950 Dialog ariaLabelledBy

- src/app/components/picklist/picklist.ts
> Picklist items deleted fix 

- src/app/components/calendar/calendar.ts
> Fix #14590 and #12286 - Single dates not possible with calendar in range mode

- src/app/components/steps/steps.ts
> fix #15133 Update steps link attributes

- src/app/components/picklist/picklist.ts
fixes #14944
Added IDs to the headers and aria-labelledby attributes to the listboxes.
> fix #14944 picklist listbox aria-labelledby

- src/app/components/tieredmenu/tieredmenu.ts
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.
Fix #13818
> fix: first item focused on toggle on TierMenu

- src/app/components/api/primengconfig.ts
- src/app/components/api/translation.ts
- src/app/components/dialog/dialog.ts
> Fixed #14949 - Dialog | Missing Aria Label on Maximize button

- src/app/components/listbox/listbox.ts
> Fixed #15084 - Listbox | Missing aria-label

- src/app/components/treetable/treetable.ts
Reverts primefaces/primeng#15159
> Revert "Fixed #15158 - TreeTable | Update selection logic and fix partial sel…"

- src/app/components/treetable/treetable.ts
> Fixed #15178 - Use ObjectUtils for comparison

- src/app/components/multiselect/multiselect.ts
fixes #14958 
fixes #14946
This may also fix the following issues: #15001 and #15002
> fix #14958 MultiSelectItem role=option

- src/app/components/inputotp/inputotp.ts
- src/app/showcase/doc/inputotp/sampledoc.ts
- src/app/showcase/doc/inputotp/templatedoc.ts
> Fixed #15200 - backspace key doesn't work @ Template

- src/app/components/api/treenode.ts
- src/app/components/treetable/treetable.ts
- src/app/showcase/doc/treetable/selectioncheckboxdoc.ts
- src/app/showcase/service/nodeservice.ts
Fixed #15216 | new input property `selectionKeys` added.
Also fixes #9188 by updating ttHeaderCheckbox
> Issue 15216

- src/app/components/paginator/paginator.ts
Fixed #15231: update page links when pageLinkSize is changed
#15231
> Fixed #15231: update page links when pageLinkSize is changed

- api-generator/build-apidoc.ts
- src/app/components/calendar/calendar.css
- src/app/components/calendar/calendar.spec.ts
- src/app/components/calendar/calendar.ts
- src/app/components/cascadeselect/cascadeselect.ts
- src/app/components/inputotp/inputotp.ts
- src/app/components/treeselect/treeselect.ts
- src/app/showcase/doc/treeselect/virtualscrolldoc.ts
- src/app/showcase/service/nodeservice.ts
> Bug #15168 - placeholder overflow fix

- src/app/components/inputnumber/inputnumber.interface.ts
> Fix #15206 Incorrect type of InputNumberInputEvent.value

- src/app/components/multiselect/multiselect.ts
> fix #15246 MultiSelect aria checked

- src/app/components/multiselect/multiselect.ts
> fix: modal overlay blocking scrolling on close in multiselect 

- src/app/components/table/table.ts
Reverts primefaces/primeng#15280
> Revert "Fixed #15233 - Dropdown | Dropdown in Table Filter Menu Fails to Appl…"

- src/app/components/calendar/calendar.ts
> Fixed #15287 - Add condition for timeOnly

- src/app/components/editor/editor.ts
> Fixed #15297

- src/app/components/table/table.ts
- src/app/showcase/doc/apidoc/index.json
> Revert typo & fix #15306

- src/app/components/divider/divider.css
> fix style for vertical dotted divider

- src/app/components/tree/tree.ts
> Do not render <p-treeNode> if no items

- src/app/components/dropdown/dropdown.ts
> Bug #15016 - Dropdown: 'Enter' from numeric pad does not select option

- src/app/components/colorpicker/colorpicker.ts
> fix(primeng/p-colorPicker): reactive control not updated when mousemove triggered

- src/app/components/checkbox/checkbox.spec.ts
- src/app/components/menubar/menubar.spec.ts
- src/app/components/picklist/picklist.spec.ts
- src/app/components/progressbar/progressbar.spec.ts
Fixes #15416
Still working on this
> WIP: Fix unit broken tests

- src/app/components/menu/menu.ts
Fixes #15415 
Solve for [#15415](https://github.com/primefaces/primeng/issues/15415)
Added case for numpadEnter on menu component
> Added missing case for numpadEnter on menu component

- src/app/components/inputnumber/inputnumber.ts
Issue-> https://github.com/primefaces/primeng/issues/15442
Fixed above issue.
> Fixed android keyboard event code is coming as empty for backspace

- src/app/showcase/pages/timeline/timelinedemo.ts
> fix p-timeline mobile responsiveness

- src/app/components/dropdown/dropdown.ts
> Fixed #14953 - Add missing stopPropagation

- src/app/components/timeline/timeline.css
fixes #14582 
Added min width to timeline event content and opposite
> Fix: Timeline vertical alignment broken in case of small devices

- src/app/components/splitbutton/splitbutton.ts
> Bug #15342 - Split Button: Aria Label not correctly working

- src/app/components/dynamicdialog/dynamicdialog.spec.ts
- src/app/components/message/message.spec.ts
- src/app/components/messages/messages.spec.ts
> fix message and messages component unit test #15492

- src/app/components/inputotp/inputotp.ts
> fix: paste function issue in inputOtp for integerOnly

- src/app/components/tieredmenu/tieredmenu.ts
> Remove aria hidden attribute from tiered menu menu items

- src/app/components/dropdown/dropdown.ts
> fix #15339 Remove invalid abstract role section

- src/app/components/colorpicker/colorpicker.spec.ts
fixed [#15501](https://github.com/primefaces/primeng/issues/15501)
> Fixes #15501 : Broken colour picker unit test

- src/app/components/dom/domhandler.ts
- src/app/components/focustrap/focustrap.ts
> Issue 15482 - Rework and update focustrap

- src/app/components/api/primengconfig.ts
- src/app/components/calendar/calendar.ts
- src/app/components/carousel/carousel.ts
- src/app/components/confirmdialog/confirmdialog.ts
- src/app/components/dialog/dialog.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
- src/app/components/galleria/galleria.ts
- src/app/components/orderlist/orderlist.ts
- src/app/components/picklist/picklist.ts
- src/app/components/table/table.ts
- src/app/components/toast/toast.ts
- src/app/showcase/doc/button/templatedoc.ts
- src/app/showcase/doc/configuration/configurationdoc.module.ts
- src/app/showcase/doc/configuration/cspdoc.ts
- src/app/showcase/pages/configuration/configurationdemo.component.ts
> Issue 15560 - Introduces csp none

- src/app/components/focustrap/focustrap.ts
- src/app/components/galleria/galleria.css
- src/app/components/galleria/galleria.ts
> Fixed #15546 - Galleria | Keyboard Trap within Galleria component

- src/app/components/tooltip/tooltip.ts
> Fixed #15545 - Tooltip visual issue

- src/app/components/dropdown/dropdown.spec.ts
- src/app/components/dropdown/dropdown.ts
> fix dropdown unit test

- src/app/components/treeselect/treeselect.ts
https://github.com/primefaces/primeng/issues/15539
> fix(treeselect): hide panel on selected option #15539

- src/app/components/dialog/dialog.spec.ts
Fixes [#15526](https://github.com/primefaces/primeng/issues/15526)
> Dialog: Fix broken unit test

- src/app/components/rating/rating.spec.ts
Fixes: [#15522](https://github.com/primefaces/primeng/issues/15522)
> Rating: fix unit tests

- src/app/components/tree/tree.ts
> FIX: p-tree - Node which is not selectable shouldn't have focus

- src/app/components/inputotp/inputotp.ts
> fix: disable paste function on readonly mode

- src/app/components/button/button.interface.ts
- src/app/components/button/button.ts
> Fixes #15582 - Button | Remove wrapper span element from icon templates

- src/app/components/tooltip/tooltip.ts
> Fixed #15390 - Button/p-button and tooltip: Doesn't work correctly

- src/app/showcase/doc/stepper/templatedoc.ts
> Fixed #15175 - Stepper | linear does not work with header template

- src/app/components/inputnumber/inputnumber.ts
Fixes https://github.com/primefaces/primeng/issues/15293
> #15293 fixed inputNumber selection lost when selecting left prefix

- src/app/components/table/table.ts
> Fixed #15338 - Update condition

- src/app/components/table/table.ts
> Fixed #15563 - Fix typo and remove boolean attribute transform

- src/app/components/breadcrumb/breadcrumb.spec.ts
- src/app/components/breadcrumb/breadcrumb.ts
- src/app/components/inputmask/inputmask.spec.ts
- src/app/components/inputswitch/inputswitch.spec.ts
> fix inputswitch, inputmask, and breadcrumb unit test

- src/app/components/calendar/calendar.spec.ts
- src/app/components/calendar/calendar.ts
> fix: fix hideOnDateTimeSelect for range mode calendar

- src/app/components/calendar/calendar.ts
- src/app/components/slider/slider.spec.ts
- src/app/components/slider/slider.ts
> fix - Slider: Change range slider by keys does not trigger the onSlideEnd event

- src/app/components/inputmask/inputmask.ts
> fix: disable paste functionality in disabled mode

- src/app/components/picklist/picklist.spec.ts
- src/app/components/picklist/picklist.ts
> fix picklist unit tests

- src/app/components/autocomplete/autocomplete.ts
- src/app/components/calendar/calendar.ts
> FIX - Autocomplete: Showing empty overlay when has no suggestions and showEmptyMessage is false

- src/app/components/calendar/calendar.ts
> FIX: Calendar datepicker covers input component when there is 6 week displayed on

- src/app/components/api/treenode.ts
> TreeNode | Fix jsdoc

- src/app/components/accordion/accordion.ts
> fix(accordion): updateActiveIndex does not update _activeIndex

- src/app/components/inputnumber/inputnumber.ts
> FIX - InputNumber Component: Default value for minFractionDigits is not correct when value explicitly set to null 

- src/app/components/multiselect/multiselect.ts
> Fixed #15118 - Multiselect | onRemove event not getting emitted

- src/app/components/splitbutton/splitbutton.ts
resolves: https://github.com/primefaces/primeng/issues/15752
> fix(splitbutton): 15710 fix aria expanded issue

- src/app/components/inputotp/inputotp.ts
Fixes https://github.com/primefaces/primeng/issues/15613
Backaspace event issue fixed in input otp
> Backspace event issue in input otp control for mobile phone is fixed - #15613

- src/app/components/chips/chips.ts
Fixes [15611](https://github.com/primefaces/primeng/issues/15611)
> fix(chips): trigger itemClick event with 'Space' key

- src/app/components/tieredmenu/tieredmenu.ts
Resolves https://github.com/primefaces/primeng/issues/15536
> fix: add tooltip to tieredmenu items

- src/app/components/splitbutton/splitbutton.ts
> Add tooltip option for main button of `SplitButtonModule`

- src/app/components/multiselect/multiselect.spec.ts
> Multiselect: Unit Test Fix

- src/app/components/splitbutton/splitbutton.ts
Resolves: https://github.com/primefaces/primeng/issues/15758
> fix(splitbutton): 15758 add show hide event emitters for the menu

- src/app/components/tree/tree.ts
> Fixed #15828 - Tree | Accessibility within Tree Component

- src/app/components/tree/tree.ts
> Fixed #15714 - pTree: right click on treenode chevron down

- src/app/components/menu/menu.ts
> Fix keyboard navigation problem in menu component

- src/app/showcase/doc/iconfield/importdoc.ts
> docs(IconField): Add import to documentation

- src/app/components/menu/menu.ts
> Fixed #15781 - p-menu | pTemplate not working for p-menu alone

- src/app/components/orderlist/orderlist.ts
> Fixed #15326 - OrderList: Unable to insert space into input component

- src/app/components/autocomplete/autocomplete.spec.ts
- src/app/components/autocomplete/autocomplete.ts
> fix(p-autocomplete) selectItem and multipleItems broken due to optionValue support

- src/app/showcase/doc/configuration/cspdoc.ts
- src/app/showcase/doc/configuration/filtermodedoc.ts
- src/app/showcase/doc/configuration/locale/setlocaledoc.ts
I'm not sure if this is correct, but in my tests without some of  this modification I get an error.
> Documentation Correction - Configuration

- src/app/showcase/layout/doc/codeeditor/templates.ts
> Fixed #15902 - PrimeNG Button Link stackblitz not working

- package-lock.json
- src/app/components/password/password.ts
https://github.com/primefaces/primeng/issues/15905
> fix(p-password) add disabled atribute to inside input #15905

- src/app/components/listbox/listbox.ts
> Fixed #15873 - Listbox | p-listbox triggers onChange multiple times

- src/app/components/tree/tree.ts
> Fixed #15886 - Tree | Tree hierarchy

- src/app/components/table/table.ts
Reverts primefaces/primeng#15917
> Revert "Fixed #15903 - Table | Multiple Selection with dataKey shows wrong selected row count upon CTRL+A"

- src/app/components/table/table.ts
Reverts primefaces/primeng#15904
> Revert "Fixed #15903 - Table | Multiple Selection with dataKey shows wrong se…"

- src/app/components/table/table.ts
Fixes #15911 
Adds the missing CSP attribute to responsiveStyleElement
> Fixes #15911 - Table | Add csp nonce to responsive style element

- src/app/components/multiselect/multiselect.ts
> Fixed #15954 - MultiSelect | MultiSelectChangeEvent wrong select value

- src/app/components/inputnumber/inputnumber.ts
> Fixed #15799 - InputNumber unneeded update model on blur

- src/app/components/splitter/splitter.ts
> fix(splitter): minSizes not working as expected

- src/app/components/tooltip/tooltip.ts
> Fixed #15933 - Button Tooltip shows up after Dialog opens

- src/app/components/multiselect/multiselect.ts
> add `p-disabled` to the chip icon if option is disabled

- src/app/components/splitter/splitter.css
> Fixes #15959 - Splitter | Add missing rule

- src/app/components/table/table.ts
> Fixed #15550 - Table | Custom sort in table not working

- src/app/components/dialog/dialog.ts
> Fixed #15978 - Doesn't call this.focus infinitely.

- src/app/components/dropdown/dropdown.ts
> fix(Dropdown): Placeholder is overwritten by float-label

- src/app/components/keyfilter/keyfilter.ts
> Fixed #15531 - KeyFilter | No longer working on chips component

- src/app/components/picklist/picklist.ts
> Fixed #15861 - Component: picklist scrolls to top

- src/app/showcase/doc/toast/animationdoc.ts
- src/app/showcase/doc/toast/basicdoc.ts
- src/app/showcase/doc/toast/cleardoc.ts
- src/app/showcase/doc/toast/headlessdoc.ts
- src/app/showcase/doc/toast/lifedoc.ts
- src/app/showcase/doc/toast/multipledoc.ts
- src/app/showcase/doc/toast/positiondoc.ts
- src/app/showcase/doc/toast/responsivedoc.ts
- src/app/showcase/doc/toast/severitydoc.ts
- src/app/showcase/doc/toast/stickydoc.ts
- src/app/showcase/doc/toast/targetdoc.ts
- src/app/showcase/doc/toast/templatedoc.ts
> fix(primeng/documentation): unnecessary ripple effect on button in toast examples

- src/app/components/tree/tree.ts
fix: #16055, Tree: inputText in Template mode does not respond to a space key
> fix: #16055, Tree: inputText in Template mode does not respond to a space key

- src/app/components/listbox/listbox.ts
> Fixed #16051 - Issue with ListBox and style since 17.18.4

- src/app/components/tieredmenu/tieredmenu.ts
Fixes #13861
Implemented @kubedan's suggestion [here](https://github.com/primefaces/primeng/issues/13512#issuecomment-2044409597)
> fix(tieredmenu): show submenu on mouse hover

- src/app/components/menu/menu.ts
> Fix popup menu cannot be opened on new target when already opened

- src/app/components/breadcrumb/breadcrumb.ts
> Fixed #16139 - Breadcrumb | tabindex property not working

- src/app/components/table/table.ts
#16070 Table> double call to (onLazyLoad) event
pull request #15996 created the issue, this commit solves it without breaking fix for #15550
> closes #16070 Table> double call to (onLazyLoad) event

- src/app/components/dialog/dialog.ts
> Fixed #14916 - Dialog | Material Design close button regression

- src/app/components/breadcrumb/breadcrumb.ts
- src/app/showcase/doc/tabview/dynamicdoc.ts
> fix: tabview demo code for TabViewDynamic

- src/app/components/tree/tree.ts
> Fixed #16156 - Tree: Accessibility issues

- src/app/components/listbox/listbox.ts
> Fixed #16152 - ListBox component accessibility issues

- src/app/components/calendar/calendar.ts
Fixes #16176 
This is my first fix contribution so please let me know if you require anything.
Thanks.
> Fixed #16176 - Calendar | add checks on panelStyle width and min-width before applying alignOverlay styles

- src/app/components/sidebar/sidebar.ts
> Fixed #16233 - Sidebar: Overlay of Nested Sidebar Blocks Its Own Content

- src/app/components/table/table.ts
> Fixed #16182 - p-table triggers lazy loading event twice

- src/app/components/panel/panel.ts
- src/app/showcase/doc/panel/basicdoc.ts
> Fixed #16326 - Panel component -> toggle from the outside

- src/app/showcase/doc/dynamicdialog/exampledoc.ts
> fix incorrect import in dynamicdialog

- src/app/showcase/doc/icons/colordoc.ts
> fix#16277 invalid quotes in documentation of HTML attribute

- src/app/components/selectbutton/selectbutton.ts
https://github.com/primefaces/primeng/issues/16251
> fix(select button): focused on tab #16251

- src/app/components/slider/slider.ts
> Fixed #16324 - Accessibility: Slider -> Keyboardtrap

- src/app/components/tree/tree.spec.ts
- src/app/components/tree/tree.ts
- src/app/showcase/layout/doc/codeeditor/services.ts
- src/app/showcase/service/nodeservice.ts
- src/assets/showcase/data/files.json
Commit bcf299a737394784d71ab53d3d4af6dda56e056c Fixes https://github.com/primefaces/primeng/issues/16430
> Fix #16430 - p-tree: Unselectable children is selected when selecting parent

- src/app/showcase/doc/table/customersdoc.ts
- src/app/showcase/doc/table/filteradvanceddoc.ts
- src/app/showcase/doc/table/filterbasic.ts
- src/app/showcase/doc/table/lazyloaddoc.ts
> doc: fix documentation for table-> filter multiselect

- src/app/components/organizationchart/organizationchart.ts
> OrganizationChart | Make Collapsible Propagate

- src/app/showcase/doc/multiselect/accessibilitydoc.ts
> chore: update accessibilitydoc.ts

- src/app/components/table/table.ts
> Fix #16304 Table: editable column is broken when disabled temporarily

- src/app/showcase/doc/button/buttongroupdoc.ts
- src/app/showcase/layout/doc/codeeditor/templates.ts
> Fix #16276 p-buttonGroup: 'p-buttonGroup' is not a known element 

- src/app/showcase/doc/multiselect/templatedoc.ts
> fix: MultiSelect template demo

- src/app/components/messages/messages.ts
Fixes https://github.com/primefaces/primeng/issues/16253
> fix(messages): template not working #16253

- src/app/components/multiselect/multiselect.ts
> Fixed #16379 - Multi-select | Chip remove event not exposed

- src/app/components/splitbutton/splitbutton.ts
https://github.com/primefaces/primeng/issues/16725
#16725.
> bug fix use TooltipOptions type instead of string

- src/app/showcase/doc/inputotp/sampledoc.ts
> fix: Enable Paste Handling in Template and Sample doc

- src/app/components/steps/steps.ts
> Fixed #16620 - Steps | Remove unnecessary spaces

- src/app/components/calendar/calendar.ts
fix for https://github.com/primefaces/primeng/issues/16686
This pull request fixes incorrect month value in Calendar component by incrementing month value.
> fix( #16686): incorrect month value in Calendar component

- src/app/components/dom/domhandler.ts
- src/app/components/scroller/scroller.ts
> fix(scroller): contentEl might be undefined if calling setTimeout

- src/app/components/sidebar/sidebar.ts
> fix(primeng/p-sidebar): `onHide` event not send after close manually

- src/app/showcase/doc/autocomplete/showclear-doc.component.ts
Fixes https://github.com/primefaces/primeng/issues/16568
> doc(16568): fixed Autocomplete ShowClear Doc Demo

- apps/showcase/doc/theming/definepresetdoc.ts
- apps/showcase/doc/theming/dtdoc.ts
- apps/showcase/doc/theming/palettedoc.ts
- apps/showcase/doc/theming/updatepresetdoc.ts
- apps/showcase/doc/theming/updateprimarypalettedoc.ts
- apps/showcase/doc/theming/updatesurfacepalettedoc.ts
- apps/showcase/doc/theming/usepresetdoc.ts
> docs: Fix all imports of the primeng themes

- src/app/components/splitbutton/splitbutton.ts
> fix: #16731 Adds a plain textual class to the button

- src/app/components/menu/menu.ts
I encounter the exact same issue as mention in #16298.
This pull request implement the fix proposed by @hyilai in the issue #16298.
> Fix #16298

- src/app/components/autocomplete/autocomplete.ts
Fixes https://github.com/primefaces/primeng/issues/16570
> fix(16570): Autocomplete: do not clear whole input on backspace

- src/app/components/dropdown/dropdown.ts
Fixes primefaces/primeng#16411
> Fix dropdown filled calculation regarding null or undefined values

- src/app/components/tree/tree.interface.ts
- src/app/components/tree/tree.ts
Fixed #16170 : We can now implement different behavior based on drop element type
> Add a boolean which indicates if the drop is in a drop point or a node

- src/app/components/package.json
Reverts primefaces/primeng#16783
> Revert "feat(angular): allow/support Angular 19 with zone.js 0.15"

- packages/primeng/src/select/select.ts
> Fixed #16419 | Select v18: Checkmark not working

- packages/primeng/src/accordion/style/accordionstyle.ts
> Fixed #16804 | Accordion - Ripple | unexpected behavior

- packages/primeng/src/tree/tree.ts
> Fixed #16874 | Tree: Arrow Up not working

- apps/showcase/doc/stepper/verticaldoc.ts
> Fixed #16897 | Stepper: Missing orientation property

- packages/primeng/src/drawer/drawer.ts
- packages/primeng/src/menu/menu.ts
- packages/primeng/src/overlaypanel/overlaypanel.ts
- packages/primeng/src/popover/popover.ts
- packages/primeng/src/sidebar/sidebar.ts
- packages/primeng/src/tieredmenu/tieredmenu.ts
Fixes #16795. Also addresses the same issue in a few other components.
> Fix: Menu(16795): appendChild param order reversed

- apps/showcase/doc/table/productsdoc.ts
- apps/showcase/doc/textarea/autoresizedoc.ts
- apps/showcase/doc/textarea/basicdoc.ts
- apps/showcase/doc/textarea/disableddoc.ts
- apps/showcase/doc/textarea/filleddoc.ts
- apps/showcase/doc/textarea/floatlabeldoc.ts
- apps/showcase/doc/textarea/importdoc.ts
- apps/showcase/doc/textarea/invaliddoc.ts
- apps/showcase/doc/textarea/keyfilterdoc.ts
- apps/showcase/doc/textarea/reactiveformsdoc.ts
- apps/showcase/doc/textarea/sizesdoc.ts
> Fix #16928 Textarea import typo

- apps/showcase/assets/styles/global.scss
- apps/showcase/components/layout/app.component.ts
- apps/showcase/components/layout/configurator/app.configurator.component.ts
- apps/showcase/service/appconfigservice.ts
> Fixed #16803 - Showcase | save appState

- apps/showcase/doc/select/filterdoc.ts
- apps/showcase/doc/table/filterbasic.ts
- apps/showcase/doc/tailwind/formdoc.ts
- apps/showcase/pages/landing/themesection.component.ts
> Fixed #16925 | Showcase: Misaligned Country Flags in Components Showcase

- packages/primeng/src/ripple/ripple.ts
> Fixed #16944 - Ripple | Ripple effect remains active when disabled

- packages/primeng/src/confirmdialog/confirmdialog.ts
> Fixed #16963 | v18-rc.2 Component: ConfirmationDialog

- src/app/components/inputnumber/inputnumber.ts
> #16607 fixed bug in inputnumber for dead keys

- packages/primeng/src/treetable/treetable.ts
> Fixed #15610 - TreeTable | Only add scrollbar padding, when scrollHeight is specified.

- src/app/components/togglebutton/togglebutton.ts
> fix incorrect property used in hasOffLabel getter

- src/app/components/editor/editor.ts
> Fix #16825 Editor setValue in hidden dialog not working

- src/app/components/multiselect/multiselect.ts
fix: #16684, MultiSelect: Unable to select remove icon of chips through keyboard
> fix: #16684, MultiSelect: Unable to select remove icon of chips through keyboard

- src/app/components/password/password.ts
fix: #16555, Password: Tab navigation not getting focussed on Eye icon in ToggleMask Mode.
> fix: #16555, Password: Tab navigation not getting focussed on Eye icon in ToggleMask Mode.

- src/app/components/inputmask/inputmask.ts
Fixes #14529 
It also makes the gboard behaviour similar to the keyboard one.
> Fix #14529 - Google Gboard and inputmask control

- src/app/components/tabview/tabview.ts
> fixed issue #16313 (p-tabview closing active first tab opens not the next tab)

- packages/primeng/src/tooltip/tooltip.ts
> fix: :bug: Fix Tooltip display behavior

- apps/showcase/components/doc/app.docsection-nav.component.ts
This PR originally was meant to fix #16892, which has been fixed already by manually triggering a change detection whenever the activeItem is updated.
This PR is still valuable as its add following changes:
- remove dependencies to `NgZone`, `Renderer2` and `ChangeDetectorRef`
- improve types
- use angulars new control-flow syntax
- use signals
> Fixed #16892 - Showcase | Table of Contents not updating on scroll

- src/app/showcase/doc/stepper/lineardoc.ts
https://github.com/primefaces/primeng/issues/16967
> Fix linear stepper stackblitz example not working due to misspelling

- packages/primeng/src/dynamicdialog/dynamicdialog.ts
> Fixed #16968 | Component: DynamicDialog - breakpoints are ignored

- apps/showcase/doc/theming/presetsdoc.ts
> Fixed #17003 | Documentation: Theming, Presets wrong link

- packages/primeng/src/drawer/drawer.ts
> Fixed #17006 | Theming: Scoped tokens not working

- apps/showcase/doc/theming/darkmodedoc.ts
> Fixed #17060 | Darkmode: Missmatch between Code and Docs

- packages/primeng/src/config/provideprimeng.ts
> fix(v19): provideprimeng

- packages/primeng/src/tabs/tablist.ts
> Fixed #17071 | Tabs: scroll buttons should be type=button

- apps/showcase/components/doc/app.code.component.ts
- apps/showcase/components/doc/codeeditor/templates.ts
> Fixed #17004 | v18 documentation: StackBliltz option missing from demos

- packages/primeng/src/picklist/picklist.ts
> Fixed #16983 | Component: Picklist v18

- packages/primeng/src/confirmdialog/style/confirmdialogstyle.ts
- pnpm-lock.yaml
> Fixed #17087 | ConfirmDialog: icon has wrong size

- packages/primeng/src/breadcrumb/breadcrumb.ts
> fix: Removed apostrophe typo

- packages/themes/src/presets/material/radiobutton/index.ts
> add missing semi-colon in radiobutton material style

- packages/primeng/src/inputotp/inputotp.ts
> fix: handle otp keyboard filling

- packages/primeng/src/paginator/paginator.ts
> feat: Move showAll option to the end of options

- packages/primeng/src/autocomplete/autocomplete.ts
> Fixes #17143 Autocomplete emptyMessage not shown

- packages/primeng/src/togglebutton/public_api.ts
> Fix: ToggleButton(#17209) Missing ToggleButtonChangeEvent export

- packages/primeng/src/calendar/calendar.ts
- packages/primeng/src/datepicker/datepicker.ts
> Fix #17206 - calendar next button user template

- packages/primeng/src/listbox/listbox.ts
[#17032](https://github.com/primefaces/primeng/issues/17032)
> fix: #17032 listbox with checkbox random click behavior

- packages/primeng/src/listbox/style/listboxstyle.ts
> fix listbox header checkbox and filter alignment

- packages/primeng/src/dropdown/dropdown.ts
fixes https://github.com/primefaces/primeng/issues/17220
> fix: #17220, Select: Editable Dropdown search not working as expected.

- apps/showcase/doc/table/sizedoc.ts
> Docs: Table Size(#17113) Update Size Documentation

- packages/primeng/src/inputotp/inputotp.ts
Fixes https://github.com/primefaces/primeng/issues/17392
> Remove onKeyDown event relying on KeyboardEvent.code -- Fixes #17392

- packages/primeng/src/table/table.ts
Fix https://github.com/primefaces/primeng/issues/17369
> fix(#17369) - Table - Fix row group footer rendered multiple times

- apps/showcase/components/doc/codeeditor/templates.ts
- apps/showcase/doc/dynamicdialog/exampledoc.ts
> fix: #17362 changed import to DynamicDialogModule in examples

- packages/primeng/src/table/style/tablestyle.ts
- packages/primeng/src/table/table.ts
> fix: #17339 scrolling behaviour in table with footer and frozen rows

- apps/showcase/pages/defer/index.ts
> docs: fix typo

- packages/primeng/src/card/card.ts
> fix: Fixes #17264 Card component subheader property

- packages/primeng/src/dynamicdialog/dynamicdialog.ts
fix maximize icon style for dynamic dialog
Fix maximize style issue with dynamic dialog
Fixes #17275
> fix: add missing rounded & text prop to maximize icon (Fixes #17275)

- packages/primeng/src/tabs/tablist.ts
fixes https://github.com/primefaces/primeng/issues/17270
> fix(tablist): tabindex now correctly set from unwrapped computed signal

- packages/primeng/src/textarea/style/textareastyle.ts
> fix: Fixes #17258 textarea style misplaced semi-colon

- packages/themes/src/presets/material/inputnumber/index.ts
> fix: Fixes #17256 inputnumber Material theme CSS missing semi-colon

- packages/primeng/src/listbox/listbox.ts
- packages/primeng/src/tree/tree.ts
> fix: #17230 listbox and tree checkbox filled or outline variant

- packages/primeng/src/datepicker/datepicker.ts
[#17199 Datepicker size not working](https://github.com/primefaces/primeng/issues/17199)
> fix: #17199 datepicker sizes

- packages/primeng/src/table/style/tablestyle.ts
> fix: update tablestyle.ts #17490

- packages/primeng/src/carousel/carousel.ts
> fix: refactor next button #17485

- apps/showcase/doc/table/lazyloaddoc.ts
- apps/showcase/doc/table/virtualscrolllazydoc.ts
Fixes https://github.com/primefaces/primeng/issues/17515
> Showcase, Table: Use TableLazyLoadEvent instead of LazyLoadEvent 

- packages/primeng/src/treetable/treetable.ts
<ins>https://github.com/primefaces/primeng/issues/17496</ins>[https://github.com/primefaces/primeng/issues/17496](url)
> fix: p-treeTableCheckbox disabled not working

- packages/primeng/src/listbox/listbox.ts
- packages/primeng/src/picklist/picklist.ts
> fix(picklist): Update picklist with drag and drop functionality issue #16578

- packages/primeng/src/table/table.ts
* fix(table): column resize does not work with sortable columns
* format fix
* fix
(cherry picked from commit cc1fe7fdcf81e17502847156565981faaf13053c)
fixes #17458
> fix(table): column resize does not work with sortable columns (#16735)

- packages/primeng/src/datepicker/datepicker.ts
- packages/primeng/src/message/message.ts
- packages/primeng/src/multiselect/multiselect.ts
- packages/primeng/src/toast/toast.ts
> fix: aria-labels

- packages/primeng/src/multiselect/multiselect.ts
> Fixed #17381 - Multiselect | Fix scoped tokens not working

- apps/showcase/app/app.config.ts
- packages/primeng/src/cascadeselect/cascadeselect.ts
- packages/primeng/src/checkbox/checkbox.ts
- packages/primeng/src/datepicker/style/datepickerstyle.ts
- packages/primeng/src/dropdown/dropdown.ts
- packages/primeng/src/dropdown/style/dropdownstyle.ts
- packages/primeng/src/inputmask/inputmask.ts
- packages/primeng/src/inputnumber/inputnumber.ts
- packages/primeng/src/inputotp/inputotp.ts
- packages/primeng/src/inputtextarea/inputtextarea.ts
- packages/primeng/src/multiselect/multiselect.ts
- packages/primeng/src/password/password.ts
- packages/primeng/src/password/style/passwordstyle.ts
- packages/primeng/src/radiobutton/radiobutton.ts
- packages/primeng/src/select/select.ts
- packages/primeng/src/select/style/selectstyle.ts
- packages/primeng/src/selectbutton/selectbutton.ts
- packages/primeng/src/textarea/textarea.ts
- packages/primeng/src/treeselect/style/treeselectstyle.ts
- packages/primeng/src/treeselect/treeselect.ts
> fix: global input variant settings, fixes #17595

- packages/primeng/src/listbox/listbox.ts
- packages/primeng/src/picklist/picklist.ts
> fix(picklist): allow disabled options in picklist

- packages/primeng/src/listbox/style/listboxstyle.ts
- packages/primeng/src/orderlist/orderlist.ts
fixes https://github.com/primefaces/primeng/issues/16633
I also added the styling for when the p-listbox-option is dragable
this fix is based on the merge from https://github.com/primefaces/primeng/pull/17475
> fix(p-orderlist): update orderlist with drag and drop functionality issue #16633

- packages/primeng/src/badge/badge.ts
> fix(badge): correctly set display none if disabled is true

- packages/primeng/src/autocomplete/style/autocompletestyle.ts
> fix(autocomplete): add missing . in invalid style

- packages/primeng/src/picklist/picklist.ts
> fix(picklist): update scroll parameters on reorder

- packages/primeng/src/tree/tree.ts
> fix(tree): apply styleClass of tree nodes

- apps/showcase/doc/select/loadingstatedoc.ts
> fix: incorrect placeholder in select docs

- packages/primeng/src/dataview/dataview.interface.ts
This interface is responsible for the DataView API documentation, which is still referring to previous, and now obsolete, versions.
> Update DataView interface to reflect current configuration

- packages/primeng/src/multiselect/multiselect.ts
https://github.com/primefaces/primeng/issues/17732
> fix: selectedOptions not taking into account all options sometimes

- packages/primeng/tsconfig.json
Should fix https://github.com/primefaces/primeng/issues/17716
Follows the recommendation of the Angular dev team, see https://angular.dev/tools/libraries/creating-libraries#publishing-libraries
> build: publish as partial-Ivy format

- packages/primeng/src/dynamicdialog/dynamicdialog.ts
https://github.com/primefaces/primeng/issues/17725
relates https://github.com/primefaces/primeng/issues/17404
> fix(dynamic-dialog): aria-label of close button

- packages/primeng/src/fileupload/fileupload.ts
This is fix for:
https://github.com/primefaces/primeng/issues/17721
https://github.com/primefaces/primeng/issues/15988
> Fixes issue #17721

- apps/showcase/doc/popover/basicdoc.ts
> fix(docs): Updating basicdoc.ts to use Control Flow syntax

- apps/showcase/doc/datepicker/sizesdoc.ts
#17690
Small copy paste error in showcase. Just a beauty issue
> fix: datepicker-sizes-demo ts

- packages/primeng/src/messages/messages.ts
> Fix wrong default icon in messages

- packages/primeng/src/accordion/accordion.ts
> Emit onOpen and onClose when header is clicked

- packages/primeng/src/confirmdialog/confirmdialog.ts
Issue described in https://github.com/primefaces/primeng/issues/17512
> Fixes issue #17512

- packages/primeng/src/calendar/calendar.ts
- packages/primeng/src/datepicker/datepicker.ts
fix: #17653 - calendar time picker am/pm localization issue
> fix: #17653 - calendar time picker am/pm localization issue

- apps/showcase/doc/api-generator/index.json
- packages/primeng/src/multiselect/multiselect.ts
- packages/primeng/src/select/select.ts
Fixes https://github.com/primefaces/primeng/issues/17670
> fix(multiselect): 17670 stop propagation for the escape event

- apps/showcase/doc/confirmdialog/positiondoc.ts
- apps/showcase/doc/dataview/loadingdoc.ts
- apps/showcase/doc/dialog/positiondoc.ts
- apps/showcase/doc/dock/basicdoc.ts
- apps/showcase/doc/fileupload/templatedoc.ts
- apps/showcase/doc/galleria/indicator/positioneddoc.ts
- apps/showcase/doc/galleria/thumbnaildoc.ts
- apps/showcase/doc/splitbutton/sizesdoc.ts
- apps/showcase/doc/table/customersdoc.ts
- apps/showcase/doc/table/filteradvanceddoc.ts
- apps/showcase/doc/table/productsdoc.ts
- apps/showcase/doc/toast/multipledoc.ts
- apps/showcase/doc/toast/targetdoc.ts
- apps/showcase/pages/landing/themesection.component.ts
https://github.com/primefaces/primeng/issues/17660
> chore(docs): set correct types for several components in the docs

- packages/primeng/src/multiselect/multiselect.ts
> fix: multiselect #17390

- packages/primeng/src/multiselect/multiselect.ts
Fixes https://github.com/primefaces/primeng/issues/17801
> Fixes issue 17801

- apps/showcase/doc/tabs/controlleddoc.ts
Fixes https://github.com/primefaces/primeng/issues/17861
> Controlled tab documentation: update selected button when tab is changed

- packages/primeng/src/inputnumber/style/inputnumberstyle.ts
> fix: clear icon position and cursor in inputnumber 

- packages/primeng/src/fieldset/style/fieldsetstyle.ts
Fixes https://github.com/primefaces/primeng/issues/17852
> Issue 17852 - Fixes token fieldset.legend.color never used

- packages/primeng/src/autocomplete/style/autocompletestyle.ts
Fixes https://github.com/primefaces/primeng/issues/17800
And as a regression https://github.com/primefaces/primeng/issues/17535
> Fixes issue #17800

- packages/primeng/src/dialog/dialog.ts
Fixes https://github.com/primefaces/primeng/issues/17245
> Fixes issue #17245 with showHeader flag for dialog not working

- packages/primeng/src/table/table.interface.ts
- packages/primeng/src/table/table.ts
https://github.com/primefaces/primeng/issues/17761
> fix(table): table has a generic RowData that applies on the input "value" and related interfaces

- packages/primeng/src/picklist/picklist.ts
> fix: allow searching items with spaces in picklist

- packages/primeng/src/tree/tree.ts
Fixes https://github.com/primefaces/primeng/issues/17681
> fix(Tree): apply gap between nodes

- packages/primeng/src/picklist/picklist.ts
resolves https://github.com/primefaces/primeng/issues/17413
> fix: picklist templates

- packages/primeng/src/select/select.ts
> fix: fixed #17995

- apps/showcase/pages/landing/herosection.component.ts
> fix: corrected hero section template links

- packages/primeng/src/table/table.ts
solves issue [18030](https://github.com/primefaces/primeng/issues/18030)
> fix(table): filter-icon-template has context whether filter is active

- packages/primeng/src/autocomplete/autocomplete.ts
> fix: #17998

- packages/primeng/src/table/table.ts
> fix: #17808 - table: keyboard navigation broken

- packages/primeng/src/picklist/picklist.ts
> fix: #18050 - remove deprecated p-header from picklist

- packages/primeng/src/listbox/listbox.ts
- packages/primeng/src/picklist/picklist.ts
Allows getting the disabled state inside the item template
Fixes #17882
> feat(picklist): allow retrieving disabled in item template

- apps/showcase/doc/inputnumber/accessibilitydoc.ts
- packages/primeng/src/inputnumber/inputnumber.ts
> fix(#17727): add support for `aria-describedby` attribute in inputnumber

- packages/primeng/src/textarea/textarea.ts
> fix(textarea): make textarea detect changes in case is rendered as content

- packages/primeng/src/button/button.interface.ts
- packages/primeng/src/button/button.ts
> fix: fixed #18018 - button directive - severity reactivity issue

- packages/primeng/src/tree/tree.ts
- packages/primeng/src/treeselect/treeselect.ts
> fix: fixed #17965 - treeselect filterinputautofocus does not work

- packages/primeng/src/picklist/picklist.ts
Fixes https://github.com/primefaces/primeng/issues/17575
> fix(picklist): pass filter templates to listbox components

- packages/primeng/src/tabs/tabs.ts
See **https://github.com/primefaces/primeng/issues/17436**
> fix(Tabs): Ensure tabs id is using signal value

- packages/primeng/src/fileupload/fileupload.ts
> fix(FileUpload): remove duplicate tabindex attributes from fileupload buttons

- packages/primeng/src/chips/chips.interface.ts
- packages/primeng/src/chips/chips.spec.ts
- packages/primeng/src/chips/chips.ts
- packages/primeng/src/chips/ng-package.json
- packages/primeng/src/chips/public_api.ts
- packages/primeng/src/chips/style/chipsstyle.ts
> fix: #16390 - Chips: Removed in V18

- packages/primeng/src/fileupload/fileupload.ts
> fix(fileupload): File size text now hides when files change

- packages/primeng/src/listbox/listbox.ts
- packages/primeng/src/picklist/picklist.ts
> fix(picklist): pass filterMatchMode and allow strings for custom filters

- apps/showcase/doc/table/productsdoc.ts
fix: https://github.com/primefaces/primeng/issues/18012
> Add missing ChangeDetectorRef import and implement OnInit in Table Sample Products

- packages/primeng/src/password/password.ts
Fixes https://github.com/primefaces/primeng/issues/17423
> fix(password): Rename hideIconTemplate name

- packages/primeng/src/confirmdialog/confirmdialog.ts
> refactor(confirm-dialog): simplify this || this by this

- packages/primeng/src/confirmdialog/confirmdialog.ts
> refactor(confirm-dialog): improve types for position property

- packages/primeng/src/autocomplete/autocomplete.ts
> fix(autocomplete): items not showed anymore when optionValue is set with multiple

- packages/primeng/src/listbox/listbox.ts
> fix(listbox): empty state and p-scroller conflict

- packages/primeng/src/table/table.ts
fixes #17977
`TableRadioButton` / `TableCheckbox` / `TableHeaderCheckbox`
- add missing `implements OnInit, OnDestroy`
- remove unused member `focused`
- passing though inputs `inputId`, `name` and `required` to checkbox component
- fix types on `onClick` handlers
- converted some inputs to signal inputs
> fix(table-checkbox): inputs "name" and "inputId" are considered

- apps/showcase/doc/apidoc/index.json
> fix: fixes #17849 update docs

- packages/primeng/src/selectbutton/selectbutton.ts
> fix: fixes #17835, update trackby

- .vscode/settings.json
- apps/showcase/components/doc/app.code.component.ts
- apps/showcase/doc/table/rowexpansiondoc.ts
- pnpm-lock.yaml
> fix: #17454

- packages/primeng/src/inputnumber/inputnumber.ts
Reverts primefaces/primeng#17347
> Revert "fix(#17109): sync p-inputnumber with formcontrol patchvalue"

- packages/primeng/src/table/style/tablestyle.ts
> fix: #17692 - Table Style Bug 

- packages/primeng/src/picklist/picklist.ts
> fix: #17650 - Picklist: When there's an active filter target and source are not updated until the filter changes

- packages/primeng/src/datepicker/datepicker.ts
> fix: #17616 - date format update Issue in primeng datepicker

- packages/primeng/src/textarea/textarea.ts
> fix: #17425 - Selector backward compat for Textarea

- packages/primeng/src/textarea/textarea.ts
Reverts primefaces/primeng#17803
> Revert "fix(textarea): make textarea detect changes in case is rendered as content"

- packages/primeng/src/confirmpopup/confirmpopup.ts
- packages/primeng/src/contextmenu/contextmenu.ts
- packages/primeng/src/megamenu/megamenu.ts
- packages/primeng/src/menu/menu.ts
- packages/primeng/src/menubar/menubar.ts
- packages/primeng/src/overlay/overlay.ts
- packages/primeng/src/overlaypanel/overlaypanel.ts
- packages/primeng/src/popover/popover.ts
- packages/primeng/src/speeddial/speeddial.ts
- packages/primeng/src/tieredmenu/tieredmenu.ts
> fix: #18204 - select: selection with mouse not working in 19.1.1

- packages/primeng/src/inputnumber/inputnumber.ts
fixes https://github.com/primefaces/primeng/issues/18311
> fix: set input as touched after blur (not after model change)

- packages/primeng/src/table/table.ts
> chore(table): remove redundant role attributes from table elements

- packages/primeng/src/table/table.ts
> fix(pSortableColumn): only apply role "columnheader" for element that are not th

- packages/primeng/src/confirmdialog/confirmdialog.ts
> fix(confirmdialog): Unsubscribe `acceptEvent`, `rejectEvent` on confirmdialog close

- packages/primeng/src/autocomplete/autocomplete.interface.ts
- packages/primeng/src/autocomplete/autocomplete.ts
> fix: #18289

- packages/primeng/src/table/table.ts
https://github.com/primefaces/primeng/issues/18552
> [#18552] add undefined check

- apps/showcase/doc/button/buttongroupdoc.ts
> fix invalid module import in buttongroup

- packages/primeng/src/dialog/dialog.ts
- packages/primeng/src/progressbar/progressbar.ts
- packages/primeng/src/table/table.ts
- packages/primeng/src/treetable/treetable.ts
> fix: #18499 - using angular style binding instead of style attribute to avoid CSP errors

- apps/showcase/doc/dialog/longcontentdoc.ts
fixes https://github.com/primefaces/primeng/issues/18581
> fix(longcontentdoc): correct typo in dialog content description

- packages/primeng/src/autocomplete/autocomplete.ts
> fix: add TimesIcon to imports and update clear icon SVG data attribute

- packages/primeng/src/galleria/galleria.ts
> fix(galleria): keep fullscreen open when navigating

- packages/primeng/src/dataview/dataview.ts
Closes #18812
Fixes #18812
Resolves #18812
> fix: DataView's paginator CSS classes and refactors *ngIf directives

- packages/primeng/src/inputnumber/inputnumber.ts
> fix: block float paste in integeronly input

- packages/primeng/src/autocomplete/autocomplete.ts
> fix(autocomplete): avoid adding the same value when no typeahead

- packages/primeng/src/textarea/textarea.ts
Fixes https://github.com/primefaces/primeng/issues/18665
> fix(#18665): fix textarea floatlabel initial state

- apps/showcase/components/layout/configurator/app.configurator.component.ts
- apps/showcase/doc/apidoc/index.json
- apps/showcase/doc/styleclass/hideonresizedoc.ts
- apps/showcase/doc/styleclass/styleclassdoc.module.ts
- apps/showcase/pages/styleclass/index.ts
- packages/primeng/src/styleclass/styleclass.ts
- pnpm-lock.yaml
> Issue 18824

- apps/showcase/doc/drawer/templatedoc.ts
> Fix issue-18457 - missing import

- apps/showcase/doc/dataview/basicdoc.ts
- apps/showcase/doc/dataview/paginationdoc.ts
fix: dataview | remove redundant class binding
Fix Issue: https://github.com/primefaces/primeng/issues/18460
> fix: dataview | remove redundant class binding

- packages/primeng/src/config/primeng.ts
Fixes https://github.com/primefaces/primeng/issues/17203, https://github.com/primefaces/primeng/issues/18200.
> fix: Fix zIndex not being set in setConfig

- apps/showcase/doc/dialog/accessibilitydoc.ts
- packages/primeng/src/api/translation.ts
- packages/primeng/src/config/primeng.ts
- packages/primeng/src/dialog/dialog.ts
Add an aria label to the dialog minimize button (the maximize button when being maximized).
Update documentation describing the accessibility options for the maximize button
#18859
> Dialog: add aria label to minimize button

- packages/primeng/src/datepicker/datepicker.ts
fix seconds being set when not displayed in picker
Closes #18567
> feat(datePickerSeconds): set seconds to zero

- packages/primeng/src/select/select.spec.ts
- packages/primeng/src/select/select.ts
> fix: fixes #18807 and extend unit tests

- packages/primeng/src/treetable/treetable.ts
> fix: #18434 - TreeTable: remove restricted aria attributes "aria-checked" and "aria-level

- apps/showcase/doc/configuration/locale/apidoc.ts
> fix: #18859
