- showcase/demo/messages/messagesdemo.html
> Typos fixed for message copy.

- package.json
closes https://github.com/AngularClass/angular2-webpack-starter/issues/411
> chore(package.json): move deps to peer

- showcase/demo/grid/griddemo.html
- showcase/demo/responsive/responsivedemo.html
Fixed a bad link and a word that looked incorrect.
> Fixed link and incorrect word.

- package.json
Just a simple update to the latest angular 2 beta version. Did a quick look at the showcase and did not see any issues.
Here is the change log for what changed in beta 13:
https://github.com/angular/angular/blob/master/CHANGELOG.md
> Update to latest angular 2 beta version.

- showcase/demo/toolbar/toolbardemo.ts
The Button import path was wrong
> Fix Button import path case

- showcase/demo/overlaypanel/overlaypaneldemo.html
Just a small example code fix.
> Fixed OverlayPanel demo code

- components/datatable/datatable.ts
Simple fix for this issue: https://github.com/primefaces/primeng/issues/293
"DataTable - expandableRows with some hidden columns"
> fix for bug 293

- components/galleria/galleria.ts
> Properly hide filmstrip. Fixes #336

- components/schedule/schedule.ts
- showcase/demo/schedule/scheduledemo.html
- Added viewRender-event from Fullcalendar to schedule-component
- Added viewRender-documentation to showcase
> Added viewRender-event

- components/datatable/datatable.ts
Issue 293 was fixed only for non-scrollable tables, this fixes scrollables.
> Issue 293: Fix for when tables are scrollable

- showcase/demo/autocomplete/autocompletedemo.html
ngmodel property was not properly documented for autocomplete component (advanced demonstration)
> fixed documentation

- components/schedule/schedule.ts
Fixed typo for allDaySlot option and added allDayText option
> Fixed issue #717

- components/inputmask/inputmask.ts
- package.json
decimal and currency with changed radixPoint is now unmasked correctly
> fixes #802 unmasking

- components/schedule/schedule.ts
- showcase/demo/schedule/scheduledemo.html
> Fixes issue #777

- components/datatable/datatable.ts
DataTableModule should import InputTextModule
> Fixed issue #768

- components/lightbox/lightbox.ts
Simple change in order to display the image title on lightboxes.
If a title is present this will display the close button too.
If there is no title the comportment is the same as before : lightbox is display without title and close button.
> Lightbox : Display image title and close button

- components/datatable/datatable.ts
Calling this.filter() in ngDoCheck()
> Filtered rows are not refreshed if [value] is changed

- components/dom/domhandler.ts
DomHandler equals method was returning false even when the object was equal
> DomHandler equals method wasn't working properly

- tsconfig.json
Fixed issue https://github.com/primefaces/primeng/issues/672
> Fixed issue #672

- components/datatable/datatable.ts
To fix issue #681 created by @mleonhartsberger.
> DataTable: sorting null not working properly

- showcase/demo/datatable/datatabledemo.html
Noticed some minor inconsistencies with the documentation for DataTable and decided to fix them.
> Update DataTable documentation

- components/slider/slider.ts
fix of left percent offset for (range) slider
> fix of left percent offset for (range) slider

- components/schedule/schedule.ts
add schedule 2 options for want draggable events.
see fullcalendar doc.
https://fullcalendar.io/js/fullcalendar-3.0.1/demos/external-dragging.html
> add droppable & dropevent options

- .gitignore
- components/accordion/accordion.ts
Just ignoring .idea folder for WebStorm users.
> ignoring .idea folder for webstorm

- components/datatable/datatable.ts
It was trowing an error in Firefox.
> Fixed #1084

- showcase/demo/calendar/calendardemo.html
> fix doc only

- components/spinner/spinner.ts
Block non numeric characters in spinner.
Fix #1460
> Fixed #1460 (block numeric character in spinner input)

- showcase/demo/datatable/datatabledemo.html
> fix sample source

- showcase/demo/overlaypanel/overlaypaneldemo.html
See https://github.com/primefaces/primeng/blob/master/components/overlaypanel/overlaypanel.ts#L35
> Fix overlay panel hide events in documentation

- components/schedule/schedule.ts
- showcase/demo/schedule/scheduledemo.html
Greetings!
This PR adds an additional method to the Schedule component that maps to the changeView() feature of FullCalendar. 
The method was added to the Schedule Typescript file and the HTML documentation was updated. Please let me know if I missed something that also needs to be addressed. 
Thanks so much for this amazing collection of tools!!
:brock
> Schedule component - add changeView method

- components/inputmask/inputmask.ts
- showcase/demo/inputmask/inputmaskdemo.html
Feature #1503
Add support to HTML5 input types. This feature is very important for mobile users.
> Add type property to inputMask

- components/autocomplete/autocomplete.ts
- showcase/demo/autocomplete/autocompletedemo.html
To support AutoComplete inside overflow elements
In order to fixing: #1616
Tested using:
> showcase/demo/autocomplete/autocompletedemo.html:
```
<div class="content-section implementation">
<h3 class="first">Basic</h3>
<div style="overflow: hidden">
<p-autoComplete [appendTo]="'body'" [(ngModel)]="country" [suggestions]="filteredCountriesSingle"
(completeMethod)="filterCountrySingle($event)" field="name" [size]="30"
placeholder="Countries" [minLength]="1"></p-autoComplete>
</div>
<span style="margin-left:10px">Country: {{country ? country.name||country : 'none'}}</span>
<h3>Advanced</h3>
<div style="overflow: hidden">
<p-autoComplete [appendTo]="'body'" [(ngModel)]="brand" [suggestions]="filteredBrands"
(completeMethod)="filterBrands($event)" [size]="30"
[minLength]="1" placeholder="Hint: …
```
> Add appendTo for AutoComplete

- components/inputmask/inputmask.ts
> Default value is not masked by InputMask

- components/dom/domhandler.ts
Had an issue in my code that the opacity will get negative values, which results in strange browser behavior.
> Prevent negative opacity values

- components/calendar/calendar.ts
Fixed #1475
Wrong date when select day of the next month on calendar
> Fixed #1475

- components/fileupload/fileupload.ts
OnUpload gets called when any success response is called (200-299)
> Call FileUpload onSuccess on success response only

- components/inputmask/inputmask.ts
> Proposed fix for #1734

- components/calendar/calendar.ts
Feature: https://github.com/primefaces/primeng/issues/1766
> Added onFocus event to calendar component

- components/calendar/calendar.ts
https://github.com/primefaces/primeng/issues/1676
> Fixing issue #1676 - Calendar control validity state

- components/dialog/dialog.ts
- showcase/demo/dialog/dialogdemo.html
> Adding option to close dialog when the background overlay is clicked

- components/chips/chips.ts
Removes the input field of chips if they are disabled as it is not functioning anyhow.
> Remove chips input field if dissabled

- components/inputmask/inputmask.ts
I fixed for this issue
http://forum.primefaces.org/viewtopic.php?f=45&t=48977
> fixed p-inputmask on android(http://forum.primefaces.org/viewtopic.php?f=35&t=48760)

- components/calendar/calendar.ts
When Use timeOnly and dataType is string, formatted value set to model object.
I fixed updateModel function.
> Fix updateModel in case of timeOnly

- components/listbox/listbox.ts
> Listbox onCheckboxClick() function parameter fix for #1887

- showcase/demo/confirmdialog/confirmdialogdemo.html
> Documentation is wrong at ConfirmDialog attributes

- showcase/demo/datatable/datatableeditabledemo.html
> update doc only

- components/spinner/spinner.ts
- showcase/demo/spinner/spinnerdemo.html
Added placeholder property to pinner component
> Added placeholder to spinner component

- components/common/shared.ts
Bugfix for #1780. Sorry, tested only in a limited cases.
> Bugfix for #1780

- components/datatable/datatable.ts
> Fix for #2082

- showcase/demo/galleria/galleriademo.html
This is a documentation update to fix issue https://github.com/primefaces/primeng/issues/870.
> Updated Galleria documentation for showCaption

- components/schedule/schedule.ts
> Schedule: onDrop emit jquery ui object Fixes #2121

- components/dom/domhandler.ts
> Add missing semicolon

- showcase/demo/tree/treedemo.html
Simple missing value in documentation for Tree
> Add missing checkbox documentation for Tree

- components/autocomplete/autocomplete.ts
- showcase/demo/autocomplete/autocompletedemo.html
> Add focus event to autocomplete #2136

- components/multiselect/multiselect.ts
> Add space after comma in label to better apparence  #2250

- showcase/demo/fieldset/fieldsetdemo.html
> add attributes doc

- components/calendar/calendar.ts
Both angles incremented seconds. I've fixed this.
> Fix error with decrementSecond

- components/captcha/captcha.ts
> Add return statement when repatcha is not loaded

- components/datatable/datatable.ts
remove redundancy appending anchor which already added before
> optimize(datatable): exportCSV

- components/calendar/calendar.ts
> updateUI() can now handle string and number version of hourFormat

- components/fileupload/fileupload.ts
> FileUpload. Added file type validation 

- components/tooltip/tooltip.ts
- showcase/demo/tooltip/tooltipdemo.html
> Adding option to render html tags in tooltip contents

- components/calendar/calendar.ts
Returned date in calendar component should be in UTC format.
> Calendar date format as UTC - Fix #1113

- components/calendar/calendar.ts
Use date from parameter instead of this.pm when checking AM/PM.
Fixing: https://github.com/primefaces/primeng/issues/2359
> Fix FormatTime function for 12hr format ( fix for #2359 issue )

- components/gmap/gmap.ts
- package.json
- showcase/demo/gmap/gmapdemo.html
Implement issue #2435
Created onMapReady event emitter in GMap
> Make native google.maps.Map of GMap object available through @Output

- components/splitbutton/splitbutton.ts
> SplitButton icon position fix

- components/dropdown/dropdown.ts
> Set the width of the dropdown panel in order to support appendTo=body.

- components/slidemenu/slidemenu.ts
https://github.com/primefaces/primeng/issues/2578
> SlideMenu Show method not working

- components/calendar/calendar.ts
https://github.com/primefaces/primeng/issues/2693
> Calendar's TimePicker AM/PM fix

- components/spinner/spinner.ts
- showcase/demo/spinner/spinnerdemo.html
> Add onBlur to spinner (feature #2524)

- components/tieredmenu/tieredmenu.ts
> TieredMenu activeItem fix

- components/accordion/accordion.css
> Fix fontawesome formatting in accordion subcomponents

- components/datatable/datatable.ts
Fix for CSV export with enabled filtering
> Fixed #982

- components/dialog/dialog.ts
Added the ability to position the dialog where indicated by the top and left style attributes.
#1913
> Fixed #1913

- components/inputmask/inputmask.ts
> Fixing inputmask cursor on Android

- components/fileupload/fileupload.ts
Check file type even not wildcard is present
> Fix #2699 - check file type even not wildcard is present

- components/schedule/schedule.ts
Added timeFormat to customize timeColumn: https://fullcalendar.io/docs/text/timeFormat/
> feature(schedule): Added timeFormat to customize timeColumn.

- components/listbox/listbox.ts
- showcase/demo/listbox/listboxdemo.html
Add list box index property on template
> Feature #2772 - listbox index attribute

- components/togglebutton/togglebutton.ts
https://github.com/primefaces/primeng/issues/1980
> ToggleButton icon only classes fix

- components/fileupload/fileupload.ts
- showcase/demo/fileupload/fileuploaddemo.html
Callback onItemClear for when user remove individual file.
> Feature #2822 file upload onItemClear callback

- components/slider/slider.ts
Fixed issue: https://github.com/primefaces/primeng/issues/2429
> Fixed: onSlideEnd event is not getting values #2429

- components/multiselect/multiselect.ts
> Fixed - #2823 - Multiselect container misaligned on filtering with appendTo="body"

- components/contextmenu/contextmenu.ts
Fixed #2785 
Visible property need work for context menu items.
> Fixed #2785 (visible attr ignored by context menu items)

- components/fileupload/fileupload.ts
> add method option to fileUpload. upload file by POST or PUT request

- components/datatable/datatable.ts
> fix(DataTable): check all pages value null check

- components/password/password.ts
The password feedback panel should be dynamically updated like any other overlays
> Password z-index issue

- package.json
Noticed this small thing in `package.json` after installing the dependencies.
> Minor update to package.json

- src/app/showcase/components/growl/growldemo.html
Fix for missing source code for Success button on [this page]( https://www.primefaces.org/primeng/#/growl). I guess it's not worth to create separate issue for this.
> Add missing source code for growl showcase

- src/app/components/schedule/schedule.ts
- src/app/showcase/components/schedule/scheduledemo.html
This PR adds the viewDestroy event to the Schedule component. Documentation has also been added to the showcase for the Schedule.
Please let me know if there is anything thing else I can do to help get this PR merged. Thanks!
> Adds onViewDestroy event to Schedule component

- README.md
> Fix PrimeNG Logo URL

- src/app/components/treetable/treetable.ts
- src/app/showcase/components/treetable/treetabledemo.html
> Added double click event for TreeTable

- src/app/components/gmap/gmap.ts
- src/app/showcase/components/gmap/gmapdemo.html
- src/app/showcase/components/gmap/gmapdemo.ts
I needed these events to change the display based on changed map bounds.  Raising these events seem to accomplish the task even though I have seen some posts which indicate otherwise.  I also added the events to the demo project.  I also sorted the documented events in alphabetical order since there seemed to be no order.
> Added events zoom_changed and map dragend

- src/app/showcase/components/growl/growldemo.html
Method name in html template  (`clear()`) didn't match ts name (`hide()`)
> doc(growl): fix broken code sample

- src/app/components/common/shared.ts
- src/app/components/datatable/datatable.ts
- Added support for column ids in table column headers
- While reordering columns, make dragover handler run outside of angular and not trigger detect changes cycle on whole application
> DataTable improvements

- src/app/components/calendar/calendar.css
> Bug fixed: #3423

- src/app/components/datatable/datatable.ts
- src/app/showcase/components/datatable/datatabledemo.html
> Allow choosing of loading icon

- src/app/components/button/button.ts
> Fix for Button.ts class name typo

- src/app/components/spinner/spinner.ts
> Clearing out the text always sets the value to null now.

- src/app/components/calendar/calendar.css
Issue: https://github.com/primefaces/primeng/issues/3501
Remove duplicate property in `.ui-calendar button` class
> remove second position property

- src/app/showcase/components/growl/growldemo.html
Fix escaped html markup in demo
> doc(growl)

- src/app/showcase/components/setup/setup.component.html
The existing code sample didn't mention the `BrowserAnimationsModule` which is the main purpose of this paragraph
> doc(setup): improve "Animations with Angular 4+"

- src/app/showcase/components/panel/paneldemo.html
Fix a wrong curly bracket in the code exemple
`[style]="{'float':'right'{"` => `[style]="{'float':'right'}"`
> doc(panel): fix curly bracket in exemple

- src/app/components/datatable/datatable.ts
> Added valueChange event to datatable

- src/app/components/datatable/datatable.ts
I believe this is the fix needed for the TypeError mentioned by @stefvardalos in issue #3553.
> Remove class on found element instead of this.editingCell which is null. (see issue #3553)

- src/app/components/panel/panel.ts
Adds new event onEndToggle on Panel component, in order to trigger an event just after the panel changed its status and after the animation ended.
> Adds onEndToggle event on Panel

- src/app/components/tree/tree.ts
Related issue: https://github.com/primefaces/primeng/issues/3458
> Add dropNode parameter in onDropPoint.

- src/app/components/fileupload/fileupload.ts
Added the ability to change the list of files to download from component
How to use
`html = '
<p-fileUpload [files]="files">';
`
In component 
`
this.files = File[];
testFunction(){
this.files.push(generateFile())
}
`
> FileUpload should have files as a property as well

- src/app/showcase/components/schedule/scheduledemo.html
Update the documentation to match the event emitter call.
> Fixes #3881 Update scheduleDemo.html

- src/app/showcase/components/treetable/treetabledemo.html
Update Tree Table Documentation to include the three types of selection modes.
> Fixes #3824 Update treetabledemo.html

- src/app/components/multiselect/multiselect.ts
Include space after a comma in selected labels list
https://github.com/primefaces/primeng/issues/3858
> Update Multiselect to Include Space After Comma

- src/app/components/dropdown/dropdown.ts
> Fix Label not shown when selected

- src/app/components/slider/slider.ts
In this PR i fixed an performance issue in the Slider component.
The changedetection was triggered on mousemove, which causes high cpu usage. For Example i you use three Slider components the changedetection fired three times. So i excluded it.
> Fix slider change detection performance issue

- src/app/components/autocomplete/autocomplete.ts
> fix(autocomplete): clear search timeout on every input

- src/app/components/dropdown/dropdown.css
> fix(dropdown): fixed dropdown filter container width

- src/app/components/orderlist/orderlist.ts
#3933 
Added a condition for checking if at least one item is selected from the list to move it.
> 3933 OrderList reorder of an empty array

- src/app/components/tieredmenu/tieredmenu.ts
Clear documentClickListener and appendTo separated.
4056
> Possible correction for issue #4056

- package-lock.json
- src/app/components/calendar/calendar.ts
> fix(calendar): error with updateUI for ranges #3996

- src/app/components/chips/chips.ts
- src/app/showcase/components/chips/chipsdemo.html
#3998 Chips
added events:
`onBlurEvent` and `onFocusEvent`
> 3998 chips: added events onFocusEvent and onBlurEvent

- src/app/components/multiselect/multiselect.ts
- src/app/showcase/components/multiselect/multiselectdemo.html
#3999 Multiselect:
added property `resetFilterOnHide` that clear filter value when dropdown closing
added EventEmitter `onPanelHide`
> 3999 added flag resetFilterOnHide and EventEmmiter with name onPanelHide

- src/app/components/picklist/picklist.ts
- src/app/showcase/components/picklist/picklistdemo.html
Add onSourceSelect and onTargetSelect events to picklist component, so you can use the picklist also as a filter.
> Feature Request: add onSourceSelect and onTargetSelect events to picklist component

- src/app/components/tabmenu/tabmenu.ts
> Fix #3980 (visible boolean on TabMenu)

- src/app/components/rating/rating.ts
> #3795 p-rating component with custom icons

- src/app/components/menubar/menubar.css
- src/app/components/menubar/menubar.ts
#3942 added property `visible` for each item in MenuBar
> 3942 menubar: flag visible

- src/app/showcase/components/calendar/calendardemo.html
The calendar showcase was with some syntax errors.
> Fixed up calendar example page.

- src/app/components/confirmdialog/confirmdialog.ts
ConfirmDialog: added ngIf for cases when icon is empty
> #3776 ConfirmDialog: added predicate to hide empty element icon

- src/app/components/panelmenu/panelmenu.ts
- src/app/showcase/components/panelmenu/panelmenudemo.html
#3303 added flag "hasSingleItemExpanded" to collapse excess menu items
> Added flag to expand single menu item

- src/app/components/calendar/calendar.ts
> Allow to choose same date for the start and the end of range

- src/app/components/slider/slider.ts
Related to this issue: https://github.com/primefaces/primeng/issues/4257
> add ngzone.run() to Slider onSlideEnd so events are emitted

- src/app/components/calendar/calendar.ts
fixes https://github.com/primefaces/primeng/issues/4179
> Support UTC parameter in formatDate function

- src/app/components/datatable/datatable.ts
Refactor to use objectUtils provider.
> Refactor datatable: Reuse ObjectUtils.resolveFieldData

- src/app/components/picklist/picklist.ts
As any other elements of user's form It should have opportunity to disable control elements.
> Added ability to disable buttons of PickList component

- src/app/components/lightbox/lightbox.ts
> Lightbox has duplicate template variable

- src/app/components/autocomplete/autocomplete.ts
- src/app/showcase/components/autocomplete/autocompletedemo.html
> fix for #4298

- src/app/showcase/components/dropdown/dropdowndemo.html
- src/app/showcase/components/schedule/scheduledemo.html
This PR fixes a tiny mistake in the documentation regarding the proper use of `button`s.
> Minor update in the documentation

- src/app/components/tristatecheckbox/tristatecheckbox.ts
- src/app/showcase/components/tristatecheckbox/tristatecheckboxdemo.html
This PR is used to add label for TriStatecheckbox component.
> Add label for Tristatecheckbox

- src/app/showcase/components/dropdown/dropdowndemo.html
##Syntax error
Add a comma to the array to make it copy-pastable.
> Minor fix for showcase.

- src/app/showcase/components/chart/chartdemo.html
Updated Chart.js supported version to 2.7.x in docs
> Fixed #4649 (minor docs update)

- src/app/components/datatable/datatable.ts
> Test next element minWidth when resizing a column.

- src/app/showcase/components/sidebar/sidebardemo.html
**#125;"**  appear in the wrong position
This is a quite small feature. It's just a change of demo
> sidebar demo

- src/app/components/inputmask/inputmask.ts
> Fix InputMask caret moving on Android Chrome 4.x.

- src/app/components/table/table.ts
> Added default value for lazy as stated in the documentation.

- src/app/showcase/components/datatable/datatabledemo.html
- src/app/showcase/components/keyfilter/keyfilterdemo.html
- src/app/showcase/components/progressspinner/progressspinnerdemo.html
https://github.com/primefaces/primeng/issues/4895
> Fix #4895 - Docs typos

- src/app/components/calendar/calendar.ts
This is to fix the defect described in issue #4775 
The UI is not being updated when [minDate], [maxDate], [disableDates], or [disableDays] are changed due to `this.currentMonth` being falsey in the month of January. It seems to work as expected for months Feb-Dec.
> Defect/fix issue #4775

- src/app/components/autocomplete/autocomplete.ts
> fix for #4332

- src/app/components/calendar/calendar.ts
> Attempt to support range and multiple selection with showTime=true. 

- src/app/components/calendar/calendar.ts
#4632 
Updating calendar input field after showTIme change.
> Fix #4632 - Updating calendar input field after showTIme change.

- src/app/components/datagrid/datagrid.ts
The footer is being displayed like a header for the DataGrid.
#5156
> Fix for #5156

- src/app/components/calendar/calendar.ts
Fix for issue #5137 "Calendar won't accept user input when UTC is selected and the date is different from local zone"
> Fix for issue #5137

- src/app/components/panelmenu/panelmenu.ts
> Add visible flag to panelmenu

- src/app/components/autocomplete/autocomplete.ts
#4753 
- Update the filled state when remove one item
- A lot of spaces that WebStorm removes following TSLint.
> #4753 Fix AutoComplete input state

- src/app/components/menu/menu.ts
Add styleClass and style properties from MenuItem on Menu component.
https://github.com/primefaces/primeng/issues/5253#issuecomment-370252604
@cagataycivici
> Add support of styleClass and style for menu item in p-menu

- src/app/components/table/table.ts
> Attach rowIndex to event object for onRowSelection event.

- src/app/showcase/components/carousel/carouseldemo.html
https://github.com/primefaces/primeng/issues/5513
Doc correction...
> Correction Showcase Carousel

- src/app/showcase/components/table/tablerowexpansiondemo.html
Corrected view; Updated Year to the in table expansion view
> Updating showcase view for table expansion view

- src/app/components/dataview/dataview.css
- src/app/components/dataview/dataview.ts
> Added loading and loadingIcon to DataView

- src/app/showcase/components/dialog/dialogdemo.html
> Correct typing in example use of `modal` property

- src/app/components/tieredmenu/tieredmenu.ts
Defaults to the current hardcoded value of 250.
> Make tieredMenu hide delay user configurable.

- src/app/components/picklist/picklist.ts
- src/app/showcase/components/picklist/picklistdemo.html
> added trackBy to PickList

- e2e/growl.e2e-spec.ts
- src/app/components/growl/growl.ts
> Use setTimeout within runOutsideAngular for p-growl timeout

- src/app/showcase/components/progressspinner/progressspinnerdemo.html
> update progress spinner link

- src/app/showcase/components/multiselect/multiselectdemo.html
Interface syntax Error double curly braces {{ }}
> Syntax Error

- src/app/showcase/components/dialog/dialogdemo.html
> Resolves #5755

- src/app/components/spinner/spinner.ts
> Fixed #4409

- src/app/components/accordion/accordion.ts
inspired by:
https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel
> accessibility(accordion): use correctly tab and tablist relationship

- src/app/components/calendar/calendar.ts
> Minute validation does not consider hours

- src/app/components/slider/slider.ts
see "handleStepChange" funtion.
issue: Slider with step 0.1 don't working #5581
>  Fixed bug with step <1 in Slider

- src/app/components/multiselect/multiselect.ts
I added an another template to multiselect component, to make customizable the displaying of selected items.
In our particular case, it was necessary to internationalize it, but it could be good at other times.
> Add selectedItem template to multiselect.

- src/app/components/table/table.ts
https://github.com/primefaces/primeng/issues/5777
> Fix multiselect with shift key with filtered table

- src/app/components/schedule/schedule.ts
The switchView function of the scheduler component called the wrong base function.
> switchView function does not work on Schedule

- src/app/components/message/message.ts
> #5894 - corrected the icon class name for warning message

- src/app/components/calendar/calendar.ts
> p-calendar Month Picker rejects text input

- src/app/components/calendar/calendar.ts
(The same as dropdown)
When I use appendTo="body", I must have the ability to add a inline style to the calendar component
> Inline style to the calendar

- .travis.yml
Have been changed karma test run-script.
I switch ng test --single-run to ng test --watch=false and it is works good.
#10711
> Attempt to fix travis

- src/app/components/schedule/schedule.spec.ts
- src/app/components/schedule/schedule.ts
- src/karma.conf.js
> Fixes static event rendering on component init

- src/app/components/dialog/dialog.ts
this PR should fix https://github.com/primefaces/primeng/issues/5974 and https://github.com/primefaces/primeng/issues/5336
> Update dialog.ts, fixes for 5974 and 5336

- src/app/components/orderlist/orderlist.ts
Issue #6473 - OrderList incorrect multiple items reorder on move top\bottom.
> OrderList multiple items move top\bottom reorder fix

- src/app/components/utils/objectutils.spec.ts
- src/app/components/utils/objectutils.ts
###Defect Fixes 
Different dates are considered equal.
Issue #6469
> Different dates are considered equal

- src/app/components/table/table.ts
> Resize columns to min-width if resize was smaller than that

- src/app/showcase/components/splitbutton/splitbuttondemo.ts
>  update font awesome icons to prime icons

- src/app/showcase/components/selectbutton/selectbuttondemo.html
> [doc] - Selectbutton, missing the multiple attribute

- src/app/showcase/components/table/tablecolresizedemo.html
update filename, and github link
> [doc] Update tablecolresizedemo.html

- src/app/components/picklist/picklist.ts
Fixes https://github.com/primefaces/primeng/issues/6523
> Add triggering of onSourceReorder/onTargetReorder callbacks (fix #6523)

- src/app/components/multiselect/multiselect.spec.ts
- src/app/components/multiselect/multiselect.ts
Changes to defaultLabel where not detected.
Fixes #6665
> Fix multiselect defaultLabel change detection

- src/app/components/carousel/carousel.ts
added firstVisible setter and getter. changed render funciton added firstVisible control. changed firstVisible varaibles to _firstVisible.
> Carousel firstVisible property not working

- src/app/components/confirmdialog/confirmdialog.ts
positionTop and positionLeft property added. positionOverlay function added.
> fixed #5534 - positionTop and positionLeft for ConfirmDialog

- src/app/components/multiselect/multiselect.ts
readonly added an readonly controls added in onMouseclick and onInputKeydown.
> fixed #5506 - readonly support for MultiSelect

- src/app/components/multiselect/multiselect.ts
Fixed this issue: https://github.com/primefaces/primeng/issues/6740
> fixed #6740 - multiselect with resetFilterOnHide: input clears on hide, but objects are not re-filtered

- src/app/components/multiselect/multiselect.ts
- src/app/showcase/components/multiselect/multiselectdemo.html
> fixed #5950 - Header/Footer template for MultiSelect

- src/app/components/message/message.ts
Similar to #3486 which added it to p-messages
> Display HTML content in p-message

- src/app/components/selectbutton/selectbutton.ts
> Remove select button options transformation when template is provided

- src/app/components/tabview/tabview.spec.ts
While answering to question in issue #6770 i wrote test for feature of header templates in TabView implemented here #2462. Also issues #6770 can be closed i think.
> Test for issue #6770 and feature

- src/app/components/slider/slider.ts
> fixed #4173 - Slider onSlideEnd does not fire on touch end

- src/app/components/inputtextarea/inputtextarea.css
- src/app/showcase/components/inputtextarea/inputtextareademo.html
> fixed #5560 Floating label support for textArea

- src/app/components/accordion/accordion.ts
- src/app/showcase/components/accordion/accordiondemo.html
Deleted lazy property and added content statement. Demo updated.
> fixed #5621 Lazy loading doesn't work on the Accordion

- src/app/showcase/components/dropdown/dropdowndemo.html
Hi, I've opened a Issue for this at #7078.
Fixed little typo at the documentation.
Do you also accept code refactors of the demo code?
> Fix - dropdown preview wasn't equal to it's sourcecode demo

- src/app/components/table/table.ts
> Fix incorrect unbinding of scroll event

- src/app/showcase/components/organizationchart/organizationchartdemo.html
Just another simple typo in example code
> Added missing ' so the organizationchart example code works

- src/app/components/picklist/picklist.ts
- src/app/showcase/components/picklist/picklistdemo.html
Improvement #6967 
Add template for empty source and target list
> Empty message for PickList #6967

- src/app/components/fileupload/fileupload.spec.ts
- src/app/components/fileupload/fileupload.ts
Also see https://forum.primefaces.org/viewtopic.php?t=53229
> Fix whitespace issues mentioned in #2564, add tests

- src/app/components/autocomplete/autocomplete.ts
I have created a Github Issue titled -- Autocomplete control does not validate properly when you empty the control
> Autocomplete does not validate when emptied

- src/app/components/spinner/spinner.ts
Fixes the issue #7115 where for p-spinner with step bigger than 1 the decimal value was truncated on blur.
> Fixed #7115: p-spinner truncates decimal part for step bigger than 1

- src/app/showcase/components/sidebar/sidebardemo.html
Property [ng Style] don't work here, [style] is working!
> property [ng Style] don't work here, [style] is working!

- src/app/components/password/password.ts
- src/app/showcase/components/password/passworddemo.html
Added property named showPassword to display the password, when set to true the input type is changed to text, when false to password, where its default value is false.
> Added property to display the password #7083

- src/app/components/lightbox/lightbox.ts
Adjustment of dynamic image centering.
> Responsive Lightbox #2318

- src/app/components/multiselect/multiselect.css
- src/app/components/multiselect/multiselect.ts
Changed the html elements of label to span.
> Adjusted semantic use of HTML label element in multiselect #2306

- src/app/components/dialog/dialog.ts
- src/app/showcase/components/dialog/dialogdemo.html
Added the following input properties for the dialog component, iconClose, iconMinimize, and iconMaximize.
> Expose Dialog icons for easier customization #6102

- src/app/components/menu/menu.ts
This way you can subscribe and do stuff on menu close or on menu open
> Add visibleChanged event emitter in menu component

- src/app/components/multiselect/multiselect.ts
- src/app/showcase/components/multiselect/multiselectdemo.html
Change utilized array in p-multiSelectItem displaying actual filter results for users.
#7251 
> fix(multiselect): filter with virtualscroll enabled.

- src/app/components/dropdown/dropdown.spec.ts
- src/app/components/dropdown/dropdown.ts
- src/app/components/paginator/paginator.spec.ts
- src/app/components/table/table.spec.ts
- src/app/showcase/components/dropdown/dropdowndemo.html
- src/app/showcase/components/dropdown/dropdowndemo.ts
After reviewing the code of Multiselect "Virtual Scroll", I translated the implementation to the Dropdown with the same codeStyle. 
The performance gain is really good.
I fixed also the Tests.
> Dropdown VirtualScroll feature

- src/app/components/fileupload/fileupload.ts
- src/app/showcase/components/fileupload/fileuploaddemo.html
Added Response Event to onUpload call #7179
> Added Response Event to onUpload call #7179

- src/app/components/slider/slider.spec.ts
- src/app/components/slider/slider.ts
> Resolved issue #7202

- src/app/components/editor/editor.ts
"Element not found" error mhile run angular-universal build
https://github.com/primefaces/primeng/issues/7122
Temporary fix until angular merge related depencies issue fix in [domino](https://github.com/vikerman/domino/pull/1)
> fix(editor): Fix angular-universal build run error 'Element not found'

- src/app/components/toast/toast.css
> fix incorrect css

- src/app/showcase/components/multiselect/multiselectdemo.html
> fix(multi-select): remove duplicate filter input.

- src/app/components/checkbox/checkbox.spec.ts
- src/app/components/checkbox/checkbox.ts
- src/app/showcase/components/checkbox/checkboxdemo.html
Added option to provide custom checkboxIcon for p-checkbox.
> Add checkbox checkboxIcon option

- src/app/components/tieredmenu/tieredmenu.ts
Fix submenu not hiding when onPush enabled - #7518
> Fix submenu not hiding when onPush enabled - #7518

- src/app/components/contextmenu/contextmenu.ts
> Fixed submenu unexpectedly disappears.

- src/app/components/table/table.ts
https://github.com/primefaces/primeng/issues/7335
https://github.com/primefaces/primeng/issues/7363
added null check for parentElement in handleRowClick
> fix: Cannot read property 'nodeName' of null

- src/app/components/dropdown/dropdown.ts
> Dropdown: autoWidth property wrong name FIX

- src/app/components/multiselect/multiselect.ts
Added headerFacet for to display header content
> Added headerFacet for to display header content in Multiselect

- src/app/components/keyfilter/keyfilter.ts
Android devices don't support the 'keypress' event;
https://stackoverflow.com/questions/21055270/javascript-keypress-event-not-raised-on-android-browser
http://therealmofcode.com/posts/2014/03/where-is-keypress-event-chrome-android.html
> Fixed #5925 - KeyFilter is not working on Chrome Android

- src/app/components/button/button.ts
Use typed values on input variables. Typescript language service will show the available values for each one.
> Use type fixed values on inputs

- src/app/components/paginator/paginator.ts
Fixed issue with  0 based indexing for the current page in currentPageReport template value setting.
> primeng-7684: fix issue with 0 based index

- src/app/components/calendar/calendar.ts
> 6970 & 7130- Fixed error when using Calendar month view with range or multi selection.

- src/app/components/contextmenu/contextmenu.ts
- src/app/showcase/components/contextmenu/contextmenudemo.html
> Add ContextMenu onShow / onHide events. Closes #7934

- src/app/components/calendar/calendar.ts
https://github.com/primefaces/primeng/issues/7996
> set private yearRange in setter method

- src/app/components/table/table.ts
- src/app/showcase/components/table/tabledemo.html
> add originalEvent to cellEdit events

- src/app/components/sidebar/sidebar.css
> Fixes #8159: Adds cursor: pointer to the :hover for .ui-sidebar-close

- src/app/components/autocomplete/autocomplete.ts
> Fixes issue #8096

- src/app/components/dropdown/dropdown.ts
check if disabled dropdown is destroyed when hidden before detecting changes
fixes #7970 
> check if disabled dropdown is destroyed when hidden before detecting changes

- src/app/showcase/components/fileupload/fileuploaddemo.html
Changed the name of variable
No features, just a fix
> fixed incorrect name

- src/app/components/autocomplete/autocomplete.ts
> Multiple autocomplete ignore maxlength attribute #8232

- src/app/components/contextmenu/contextmenu.ts
> ContextMenu Behaviour Fixed

- src/app/components/tieredmenu/tieredmenu.ts
- src/app/showcase/components/tieredmenu/tieredmenudemo.html
> TieredMenu Behaviour Fixed

- src/app/showcase/components/confirmdialog/confirmdialogdemo.html
https://github.com/primefaces/primeng/issues/8291
Corrected the spelling
> ConfirmDialog Doc -'Specifices' to 'Specifies'

- src/app/components/tooltip/tooltip.ts
#8323 - adjusted tooltip alignment after text changed.
> #8323 - adjusted tooltip alignment after text changed

- src/app/showcase/components/fullcalendar/fullcalendardemo.html
> Fix #8286, deconstruction syntax

- src/app/showcase/components/toast/toastdemo.html
> Corrected message object

- src/app/components/menu/menu.ts
> Popup menu does not hide on document click when parent uses OnPush change detection #8226

- src/app/components/dialog/dialog.spec.ts
- src/app/showcase/components/dialog/dialogdemo.html
Fix usage of non existing icon pi-close
> Fix usage of non existing icon pi-close

- src/app/showcase/components/table/tableeditdemo.html
The example found in the documentation for [Table - Edit](https://www.primefaces.org/primeng/#/table/edit) is not working properly since it uses the messageService but it's not declared on the constructor.
> Repair on "Table - Edit" documentation

- src/app/components/inputswitch/inputswitch.ts
> Fix bug when inputSwitch is inside a label

- src/app/showcase/components/tooltip/tooltipdemo.html
Documentation:
* fix switched row content
* add missing end points
> [doc] Tooltip - fix switched row content

- src/app/components/tooltip/tooltip.css
PR to correct component flickering. Problem documented in issue #8335.
> Fixed #8335- Correct component flickering

- .travis.yml
This pr updates the travis script so it works with new updated travis environment.
Changes:
* pin to defined distribution version
* fix required services
* fix wrong path to `ng`
* `sudo` not required anymore
**It does not fix the test fails.**
fixes #8508
> [ci] update test script

- src/app/showcase/components/calendar/calendardemo.html
> Fix sample source bug in Calendar

- src/app/components/spinner/spinner.ts
> Modify "tabindex" of spinner buttons to static value "-1"

- src/app/showcase/components/treetable/treetableeditdemo.html
> Small spelling change

- src/app/components/api/confirmation.ts
- src/app/components/confirmdialog/confirmdialog.ts
> Accept and Reject icons to Confirmation

- src/app/showcase/app.module.ts
BrowserAnimationModule export BrowserModule according to. https://angular.io/api/platform-browser/animations/BrowserAnimationsModule
> delete unnecesary modules

- src/app/showcase/components/card/carddemo.html
> Changed extra 'src' property to 'alt' for image

- src/app/showcase/components/slider/sliderdemo.html
- src/app/showcase/components/table/tablebasicdemo.html
> Fix typo in documentation

- src/app/showcase/components/formlayout/formlayoutdemo.html
This is the documentation for PrimeNG, so mentioning PrimeVue here is irritating.
> Adapt documentation for PrimeVue to PrimeNG

- src/app/showcase/components/inputnumber/inputnumberdemo.html
Fix letter case in inputNumber doc - from p-inputnumber to p-inputNumber
Fix Github url - previous 'inputmask', should be 'inputnumber'
Fix locale examples
Fix issue #8882
> Fixed #8882 inputNumber doc

- src/app/showcase/components/dialog/dialogdemo.html
#8929 Remove deprecated positionLeft and positionTop from Doc
> Remove positionLeft and positionTop from Dialog Showcase

- src/app/components/button/button.ts
https://github.com/primefaces/primeng/issues/8996
hi 
my vscode style is deferent
> fix_bugs:add initialStyleClass

- src/app/components/slider/slider.ts
> #9066 check disabled in onHandleKeydown

- src/app/showcase/components/sidebar/sidebardemo.html
I'm submitting a ... (check one with "x")
> [ x ] bug report => Search github for a similar issue or PR before submitting
> [ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
> [ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
proper closing tag in docs html - p-button
> proper closing tag in docs - p-button

- src/app/components/contextmenu/contextmenu.ts
Avoid top and botton css be 0px same time
> Fix css error when submenu of a context menu change direction.

- src/app/components/carousel/carousel.ts
This PR fixes the issue [9153](https://github.com/primefaces/primeng/issues/9153).
> fixed carousel manual page transition

- src/app/components/table/table.ts
> misspelled class name breaks virtual scroll + frozen columns

- src/app/showcase/components/tabview/tabviewdemo.html
fix #9434 There is an error in the document  [activeIndex] -> [(activeIndex)]
> fix #9434 tabviewdemo.html document errors 

- src/app/showcase/components/table/tableeditdemo.ts
Solution for: https://github.com/primefaces/primeng/issues/9382
> Fixed #9382 | onRowEditCancel method flaw

- src/app/components/tabview/tabview.ts
> Fixes #9685 - Programmatic changes of header not showing

- src/app/components/messages/messages.ts
Emitting the event after removing a message
> Fixed #9623 - Messages 2way binding is not working

- src/app/components/multiselect/multiselect.ts
> Fixed #9579 - adding onChange emit

- src/app/showcase/components/fileupload/fileuploaddemo.html
> fix typo in fileupload showcase

- src/app/components/chip/chip.ts
https://github.com/primefaces/primeng/issues/9735
> refactor: use onRemove rather than remove to match documentation

- src/app/showcase/components/button/buttondemo.html
> issue-#9777

- src/app/components/inputmask/inputmask.ts
- src/app/showcase/components/inputmask/inputmaskdemo.html
> Fixed #9718 - Expose InputMask OnKeyDown event

- src/app/showcase/components/card/carddemo.html
Fixed a little error you get, when copy & paste from your website
> Fixing CardDemo documentation output

- src/app/showcase/components/inputnumber/inputnumberdemo.html
Duplicated parameter in documentation
I don't think that need any additional info for this change. Will add if needed
> Remove duplicated inputId in inputNumber example

- src/app/components/accordion/accordion.ts
version: "11.2.2-SNAPSHOT"
The problem the same as in #4458, but should be reopened after  #9496 
Stackblitz: https://stackblitz.com/edit/primeng-accordion-demo-uhpgkp?file=src/app/app.component.ts
> fix ExpressionChangedAfterItHasBeenCheckedError error in p-accordion

- src/app/components/editor/editor.ts
Fixing editor component header template to work as documented. 
Fixes #8905
> Fixed #8905 - Update Editor Custom Toolbar Documentation

- src/app/components/password/password.ts
- src/app/showcase/components/password/passworddemo.html
Minor feature request to make the Password component's input element's placeholder attribute accessible on the <p-password> tag
> Fixed #10030 - Placeholder support for Password Component

- src/app/components/scrollpanel/scrollpanel.ts
…l bar and triggering the REFRESH function did not work
Fixed bug where external changes to the width and height of the scroll bar and triggering the REFRESH function did not work
> Fixed #9727 - Scroll Panel Bars not displaying correctly when the scrollpanel loses/gains width

- src/app/components/multiselect/multiselect.ts
Fix for issue #9673 (MultiSelect Not Displaying Pre-Selected Items Upon Load).
> Fixed #9673 - MultiSelect Not Displaying Pre-Selected Items Upon Load

- src/app/components/table/table.ts
> Fixed #9654 - PColumnFilter's apply and clear button arent hiding if [showApplyButton] or [showClearButton] are set to false

- src/app/showcase/components/primeflex/displaydemo.html
> using the wrong class name:  p-print-block to p-d-print-block  and p-print-none to p-d-print-none

- src/app/showcase/components/calendar/calendardemo.html
Fixed incorrectly reversed brackets in the documentation's code source example of DateFormat
> Correct Backet Direction

- src/app/components/sidebar/sidebar.ts
> Fixed #10261 - Sidebar wrong animation and close button display

- src/app/showcase/components/tag/tagdemo.html
Updated the text from `con` to `icon` to refer to the correct attribute.
> p-tag: Fix typo in documentation

- src/app/components/speeddial/speeddial.ts
Bugfix for an issue 
###Defect Fixes #10831
> Fixed #10831 - SpeedDial items visible even if MenuItem object property "visible" is false

- src/app/components/menu/menu.ts
#10675 
menu tooltip was working only if the menu item wasn't had any sub-items so I enabled it in another cases also
> Fixed #10675 - Menu | Submenu Tooltip Support

- src/app/showcase/components/avatar/avatardemo.html
fix documentation bug
a small documentation bug in the avatar section.
> Fix documentation bug

- src/app/components/table/table.ts
https://github.com/primefaces/primeng/issues/10792
> :bug: 10792 Resolve console console errors on table load

- src/app/showcase/components/theming/theming.component.html
> Update obsolete panel class in theming guide

- src/app/showcase/components/fileupload/fileuploaddemo.html
customUpload="true" --> [customUpload]="true"
> documentation fix

- src/app/components/toast/toast.ts
> Fixed #11313 - Toast | z-index shouldn't removed when other toasts are shown

- src/app/showcase/components/checkbox/checkboxdemo.html
> change binary to [binary]

- src/app/components/fieldset/fieldset.ts
Hello!
I provide the [correct animation callback type](https://angular.io/api/animations/AnimationEvent) for the Fieldset component.
> refactor: animation callback type for Fieldset component

- src/app/components/api/primeicons.ts
> Fixed #11472 - typo in class PrimeIcons

- src/app/components/image/image.css
- src/app/components/image/image.ts
> Fixes #11527 - Image | Zoom in and out buttons do not work properly (Firefox & Chrome)

- src/app/components/sidebar/sidebar.ts
> SideBar | update closeOnEscape option

- src/app/components/dynamicdialog/dynamicdialog-config.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
> feat(primeng/dynamic-dialog): add new option for dynamic dialog config

- src/app/components/tabmenu/tabmenu.ts
> fix(primeng/p-tabmenu): with routerLink items doesn't show offscreen item when reloaded

- src/app/components/tabmenu/tabmenu.ts
> fix(primeng/p-tabmenu): show the `forward` button when necessary

- src/app/components/calendar/calendar.ts
- src/app/showcase/components/calendar/calendardemo.html
> fix(primeng/calendar): `yearpicker` wont show value with reactive forms

- src/app/components/overlaypanel/overlaypanel.ts
> fix(primeng/overlay): handle multiple fast call toggle\show\hide methods

- src/app/components/image/image.css
Issue: #11561 
Updated the z-index for p-image-toolbar to make Image Preview Toolbar visible over the images
> Issue: #11561 - Image Preview Toolbar fix

- src/app/components/image/image.css
Reverts primefaces/primeng#11562
> Revert "Issue: #11561 - Image Preview Toolbar fix"

- src/app/components/dropdown/dropdown.ts
> Fixed #11648 - Dropdown method "show" not working in version > 13.4.0

- src/app/components/cascadeselect/cascadeselect.ts
> fix(primeng/cascadeSelect): fix clear button logic

- src/app/components/calendar/calendar.ts
> fix(primeng/calendar): fix error in mode `touchUI="true"` and `inline="true"`

- src/app/components/autocomplete/autocomplete.ts
- src/app/components/autofocus/autofocus.ts
- src/app/components/autofocus/ng-package.json
- src/app/components/autofocus/public_api.ts
- src/app/components/dropdown/dropdown.ts
- src/app/components/inputmask/inputmask.ts
- src/app/showcase/app-routing.module.ts
- src/app/showcase/app.menu.component.ts
- src/app/showcase/components/autofocus/autofocusdemo-routing.module.ts
- src/app/showcase/components/autofocus/autofocusdemo.component.html
- src/app/showcase/components/autofocus/autofocusdemo.component.ts
- src/app/showcase/components/autofocus/autofocusdemo.module.ts
Add pAutoFocus directive, fixes #11807
> Issue 11807

- src/assets/components/themes/lara-dark-blue/theme.css
- src/assets/components/themes/lara-dark-indigo/theme.css
- src/assets/components/themes/lara-dark-purple/theme.css
- src/assets/components/themes/lara-dark-teal/theme.css
- src/assets/components/themes/lara-light-blue/theme.css
- src/assets/components/themes/lara-light-indigo/theme.css
- src/assets/components/themes/lara-light-purple/theme.css
- src/assets/components/themes/lara-light-teal/theme.css
Remove unnecessary css causes malfunction of inkbar
> Fixed #11855 - TabView | inkbar does not work correctly

- src/app/components/dropdown/dropdown.ts
> fix(primeng/dropdown): fix clear button logic for empty string value

- src/app/components/editor/editor.ts
> fix(primeng/editor): fix quill editor inside dialog

- src/app/showcase/components/checkbox/checkboxdemo.html
- src/app/showcase/components/radiobutton/radiobuttondemo.html
- src/app/showcase/components/tristatecheckbox/tristatecheckboxdemo.html
> Replaced p-chkbox-* to p-checkbox-*

- CHANGELOG.md
This fixes wrong issue links in the CHANGELOG.md
> Fix issue links

- src/app/components/dynamicdialog/dynamicdialog-config.ts
- src/app/components/dynamicdialog/dynamicdialog-ref.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
- src/app/showcase/components/dynamicdialog/dynamicdialogdemo.html
- src/app/showcase/components/dynamicdialog/dynamicdialogdemo.ts
> Issue 7811

- src/app/components/confirmpopup/confirmpopup.ts
> fix(primeng/confirmPopup): fix visible for different target

- src/app/components/tieredmenu/tieredmenu.ts
- src/app/showcase/components/tieredmenu/tieredmenudemo.html
> Add TieredMenu onShow / onHide events (fix #11727)

- src/app/showcase/components/setup/setup.component.html
The style descriptions in the Get Started document are clearer for beginners.
> docs: get started

- src/app/components/slider/slider.ts
fix defect #11749
I added updateDiffAndOffset, getDiff and getOffset functions. Now range slider with step size works correctly.
> range slider fix

- src/app/components/slider/slider.ts
Issue related - #11790 
Updated [Stackblitz Example](https://stackblitz.com/edit/primeng-slider-demo-4ueh8v?file=src/app/app.component.html)
> 11790 p slider decimal fix

- src/app/showcase/components/i18n/i18n.component.html
JSON does not allow single quotes.
> Fix invalid JSON in i18n showcase

- src/app/components/selectbutton/selectbutton.ts
+ Check if value is array to fix error when multiple mode is changing
issue-11915
> issue-11915 Check for Array

- src/app/showcase/components/editor/editordemo.html
Replace the removed `angular-cli.json` with `angular.json`
> docs: editor

- src/app/components/avatar/avatar.ts
- src/app/components/chip/chip.ts
- src/app/components/fileupload/fileupload.ts
- src/app/components/image/image.ts
- src/app/showcase/components/avatar/avatardemo.html
- src/app/showcase/components/chip/chipdemo.html
- src/app/showcase/components/fileupload/fileuploaddemo.html
- src/app/showcase/components/image/imagedemo.html
> Issue 11945

- src/app/components/treeselect/treeselect.ts
Fixes issue reported in #11224
> Fixed #11224 - TreeSelect | Fix path array algorithm in selection expansion

- src/app/components/chips/chips.ts
> fix(primeng/p-chips): not unfocus input when disabled for firefox

- src/app/components/treeselect/treeselect.ts
> fix(primeng/p-treeSelect): reset partial selected tree item

- src/app/components/table/table.ts
https://github.com/primefaces/primeng/issues/11931
fix #11931 
Moving class ColumnFilter to prevent error "ReferenceError: Cannot access 'ColumnFilter' before initialization"
> fix issue #11931

- src/app/components/table/table.ts
Reverts primefaces/primeng#12042
> Revert "fix issue #11931"

- src/app/components/slider/slider.ts
> fix(primeng/p-slider): recalculate offset and diff, when changed form value

- src/app/components/badge/badge.ts
- src/app/components/button/button.ts
- src/app/components/panel/panel.ts
- src/app/components/splitbutton/splitbutton.ts
- src/app/components/togglebutton/togglebutton.ts
- src/app/showcase/components/panel/paneldemo.html
> Use explicit type for iconPos in components fixes #12097

- src/app/showcase/components/progressspinner/progressspinnerdemo.html
> ProgressSpinner: Added style and styleClass in Properties

- src/app/showcase/components/dataview/dataviewdemo.html
> Fixed Bad Typo in Showcase for p-dataview

- src/app/components/api/chips-separator.ts
- src/app/components/api/public_api.ts
- src/app/components/chips/chips.ts
- src/app/showcase/components/chips/chipsdemo.html
- src/app/showcase/components/chips/chipsdemo.ts
> feat(primeng/p-chips): update separator interface

- src/app/components/badge/badge.ts
- src/app/showcase/components/badge/badgedemo.html
> #12170 Badge: badgeDisabled

- src/app/components/dynamicdialog/dynamicdialog.ts
> Fixed dynamic dialog ref issue with the viewContainerRef

- src/app/components/fileupload/fileupload.ts
> fix(primeng/p-fileUpload): render uploadLabel for `basic` mode when is exist

- src/app/components/treeselect/treeselect.ts
> Fixed #12221 - TreeSelect: panelClass not working

- src/app/showcase/components/speeddial/speeddialdemo.html
The example code has an additional space which is not correct if someone copied it.
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.
> Fix to typo in speed dial documentation

- src/app/components/calendar/calendar.ts
> fix(primeng/p-calendar): recalculate language for calendar in runtime

- src/app/showcase/components/progressbar/progressbardemo.html
> Added STYLE and STYLECLASS in properties

- src/app/components/animate/animate.ts
- src/app/showcase/components/animate/animatedemo.html
Added leaveClass input property
> Fixed #12222 - pAnimate | Add leaveClass for leave animation

- src/app/components/multiselect/multiselect.ts
> Add selected value to original event on multi-select-item

- src/app/components/dataview/dataview.ts
> fix #12157 only show emptyMessage if dataView is not loading

- src/app/showcase/components/dropdown/dropdowndemo.html
> fixed #10595; Remove duplicated dropdown's property in doc

- src/app/components/tree/tree.ts
> fix(primeng/p-treeNode): double click on chevron makes subtree to be selected

- src/app/components/table/table.ts
Fix #12398 
Table: Resizable columns in expand mode with state feature. Column sizes not properly restored
> Fix #12398

- src/app/components/button/button.ts
> #12083 Fix Button class change

- src/app/components/password/password.css
> #12335 Eye icon duplicate problem fixed for IE

- src/app/components/tree/tree.ts
> Fixed #12351 - Tree with virtualScroll: Inconsistent focus

- src/app/components/chips/chips.ts
> Fix: #12419 - Remove extra bottom spacing.

- src/app/components/fileupload/fileupload.ts
> Fix: #12420 - Upload button does not expand when text is added.

- src/app/components/dom/domhandler.ts
> #12349 focus trap breaking on elements whose ancestors are hidden

- src/app/components/dom/domhandler.ts
Reverts primefaces/primeng#12402
> Revert "#12349 focus trap breaking on elements whose ancestors are hidden"

- src/app/components/table/table.ts
- src/app/components/treetable/treetable.ts
> fix: Table and TreeTable's filters indexer value might be undefined

- src/app/showcase/components/table/tabledemo.html
This is only a minor fix in the documentation.
> Fix default value of ColumnFilter suffix in docs

- src/app/components/calendar/calendar.spec.ts
- src/app/components/calendar/calendar.ts
Fixed #12330
Fixed following issue: 
[Calendar: wrong logic of disabling the month #12330](https://github.com/primefaces/primeng/issues/12330)
> #12330 Fix logic of disable months in month picker

- src/app/components/overlay/overlay.ts
Fixed #12382
Added additional if check to overlay.ts
> Fixed #12382 - MultiSelect: onPanelHide triggers twice

- src/app/components/dropdown/dropdown.ts
Fixed #12256 
PrimeNG dropdown not properly highlighting selected items when appendTo="body"
> fix: PrimeNG dropdown not properly highlighting selected items when appendTo="body" #12256

- src/app/components/dataview/dataview.ts
> fix: add gridStyleClass to dataview

- src/app/components/table/table.ts
> fix(primeng/p-table): remove unused `@Input` for `pReorderableRowHandle`

- src/app/components/dialog/dialog.ts
> fix(primeng/p-dialog): not removed mask element in `onPush` mode

- src/app/components/badge/badge.ts
> feat(primeng/p-badge): add size attribute to badge directive

- src/app/components/progressbar/progressbar.ts
- src/app/showcase/components/progressbar/progressbardemo.html
> Fix: #12374 - Color for the background of the progress.

- src/app/components/accordion/accordion.css
- src/app/components/accordion/accordion.ts
- src/app/showcase/components/accordion/accordiondemo.html
Fixes #12432 
New properties are added.
> Issue 12432

- src/app/components/api/overlayoptions.ts
- src/app/components/overlay/overlay.ts
> feat(primeng/p-overlay): add listener for close overlay by `escape` key

- src/app/components/tooltip/tooltip.spec.ts
- src/app/components/tooltip/tooltip.ts
- src/app/showcase/components/tooltip/tooltipdemo.html
Fixes #12477 
- Added autoHide support
> Fixed #12477 - Tooltip | Add autoHide support

- src/app/components/dom/domhandler.ts
- src/app/components/styleclass/styleclass.ts
- src/app/showcase/components/styleclass/styleclassdemo.html
- src/app/showcase/components/styleclass/styleclassdemo.module.ts
fixes #12429 
- Life cycle replaced by host listener
- "hideOnEscape" input property added
> Fixed #12429

- src/app/components/table/table.ts
> fix(primeng/p-tableRadioButton): update logic for component with `checked` and `focused` states

- src/app/components/dom/domhandler.spec.ts
- src/app/components/dom/domhandler.ts
> fixed: issue where focustrap was skipping over anchor tags when tabbing #12527

- src/app/components/calendar/calendar.ts
- src/app/components/dragdrop/dragdrop.ts
- src/app/components/messages/messages.ts
- src/app/components/selectbutton/selectbutton.ts
- src/app/components/table/table.ts
- src/app/components/toast/toast.ts
- src/app/components/tree/tree.ts
- src/app/components/treetable/treetable.ts
- src/app/components/utils/objectutils.ts
Fixes #12555.
I have replaced all uses of instanceof with a check which works also for iframes.
> Modify replace instanceof

- src/app/components/sidebar/sidebar.ts
> Fixed #12564 - Sidebar: onHide ist emitted twice

- src/app/components/contextmenu/contextmenu.ts
> Fixed #12532 - ContextMenu | triggerEvent=click does not have any effect

- src/app/components/dynamicdialog/dynamicdialog.ts
> Fixed #12319 - DynamicDialog need to steal focus

- src/app/components/password/password.ts
- src/app/showcase/components/password/passworddemo.html
> Fixed #12531 - Password | Add maxlength

- src/app/components/menubar/menubar.css
> Fix: #12549 Menubar: Overflow problem

- src/app/components/sidebar/sidebar.css
> Fix: #12833 Sidebar | Add flex-grow to p-sidebar-content

- src/app/showcase/layout/doc/code/app.code.component.ts
> CMD key triggering re-highlight

- src/app/components/tabmenu/tabmenu.css
> fix(primeng/p-tabmenu): not visible menu item, update style for .p-hidden

- src/app/components/inputnumber/inputnumber.ts
> fix(primeng/p-inputNumber): spinner button `right` click indefinitely recalculate

- src/assets/showcase/styles/layout/_doc.scss
> Fixed #12792: Z-index of code blocks over MegaMenu

- src/app/showcase/doc/galleria/importdoc.ts
I don't think there's need to create an issue :)
> docs(components): fix typo

- src/app/components/dom/domhandler.ts
> fix(primeng/p-overlay): not correctly condition for resize overlay container

- src/app/showcase/doc/defer/basicdoc.ts
> Closes #12936: Wrong Documentation for Defer

- src/app/components/table/table.ts
> fix(primeng/pFrozenColumn): update condition for a dynamic row

- src/app/components/multiselect/multiselect.ts
Fixes #12939
**selectedItems** template does not have any option to remove selected chip. Its is required sometime. Please review and confirm the merge
> Add removeChip event for custom selectedItems template

- src/app/components/common/common.css
- src/app/components/multiselect/multiselect.ts
> Fix: 12932 - MultiSelect | Alignment is broken if showClear is enabled

- src/app/components/autocomplete/autocomplete.ts
> fix(autocomplete): #13026 clear working properly in single mode

- src/app/components/button/button.css
Set pointer-events to none for disabled buttons
Resolved #13042
> disabled pointer events for disabled button

- src/app/components/toast/toast.interface.ts
- src/app/components/toast/toast.ts
This PR fixes #13079 (*Wrong type definition of ToastCloseEvent*)
> Fix #13079 - Wrong type definition of ToastCloseEvent

- src/app/components/tree/tree.ts
> Fix #13122 - Imported PlusIcon module to Tree component

- src/app/showcase/doc/tabview/controlleddoc.ts
fix [#13106](https://github.com/primefaces/primeng/issues/13106)
> fix(primeng/p-tabview): typo in p-tabview template

- src/app/showcase/layout/doc/app.doc.component.html
- src/app/showcase/layout/doc/docsectionnav/app.docsection-nav.component.html
- src/app/showcase/layout/doc/docsectionnav/app.docsection-nav.component.ts
> fix(primeng/documentation): change flow for sidebar for first child

- src/app/showcase/doc/picklist/basicdoc.ts
- src/app/showcase/doc/picklist/filterdoc.ts
> fix(primeng/p-pickList): documentation not render data

- src/app/components/menu/menu.ts
- src/app/showcase/layout/doc/docsectionnav/app.docsection-nav.component.ts
> fix(primeng/p-menu): render html via `DomSanitizer`

- src/app/components/button/button.ts
- src/app/showcase/doc/button/loadingdoc.ts
- src/app/showcase/layout/doc/docsectionnav/app.docsection-nav.component.ts
> fix(primeng/p-button): not working `loadingIcon` property, update loadingdoc example

- src/app/components/package.json
> fix: update angular version restriction

- src/app/components/confirmdialog/confirmdialog.ts
- src/app/components/contextmenu/contextmenu.ts
> fix(primeng/p-confirmDialog): not updated style in runtime

- src/app/components/accordion/accordion.ts
> fix in accordion tab icon Position

- src/app/components/autocomplete/autocomplete.ts
> Fixed #13116 Autocomplete dead animations code

- src/app/components/galleria/galleria.ts
https://github.com/primefaces/primeng/issues/13094
> Add optional chaining operator

- src/app/components/contextmenu/contextmenu.ts
- src/app/components/selectbutton/selectbutton.ts
- src/app/showcase/doc/selectbutton/templatedoc.ts
> fix(primeng/p-selectButton): with empty template not render default template

- src/app/components/galleria/galleria.ts
> fix #13124

- src/app/components/table/table.ts
resolves #13222 , resolves #13134 , resolves #12947
> fix in table- filter row clear icon not visible issue

- src/app/components/api/tooltipoptions.ts
- src/app/components/tooltip/tooltip.ts
- src/app/showcase/doc/apidoc/index.json
Fixes https://github.com/primefaces/primeng/issues/13220
> Fix: Default tooltip zIndex

- src/app/showcase/doc/table/paginatorprogrammaticdoc.ts
see https://github.com/primefaces/primeng/issues/13119
> fixes 13119, by tweaking the documentation of paginator examples for programmatic usage

- src/app/components/autocomplete/autocomplete.css
Added **fit-content** to autocomplete component to fix the issue: https://github.com/primefaces/primeng/issues/13271
> [#13271] - Added fit-content to autocomplete component

- src/app/showcase/doc/carousel/basicdoc.ts
- src/app/showcase/doc/carousel/circulardoc.ts
- src/app/showcase/doc/carousel/numscrolldoc.ts
- src/app/showcase/doc/carousel/responsivedoc.ts
- src/app/showcase/doc/carousel/templatedoc.ts
- src/app/showcase/doc/carousel/verticaldoc.ts
Fix the issue: https://github.com/primefaces/primeng/issues/13286 adding `changeDetectorRef()`.
> [#13286] Fixed carousel docs examples adding changeDetectorRef

- src/app/components/slidemenu/slidemenu.ts
> fix(primeng/p-slidemenu): use proper class name

- src/app/components/dom/domhandler.spec.ts
- src/app/components/dom/domhandler.ts
> #13273 ensure the right side of overlay does not exceed the right side of viewport

- src/app/components/treetable/treetable.ts
> Fix in treetable paginator icons not visible issue

- src/app/components/orderlist/orderlist.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/doc/orderlist/basicdoc.ts
- src/app/showcase/doc/orderlist/dragdropdoc.ts
- src/app/showcase/doc/orderlist/filterdoc.ts
Fix #13336.
Fixed examples on [orderlist's documentation](https://primeng.org/orderlist) and
> Fixed OrderList examples and added description on API docs

- src/app/components/tree/tree.ts
> Fix in Tree: Partially selected checkbox rendering
