primefaces/primeng

- showcase/demo/panelmenu/panelmenudemo.html
Hello primefaces team,
this pull request is a fixe in documentation of panel menubar. the p-panelMenu element is not closed properly.
> Fixe typo in documentation of panel menubar

- components/schedule/schedule.ts
It seems that in some cases, `ngDoCheck()` is called before `this.schedule` is initialized with `ngAfterViewInit()`.
This commit adds a check to prevent such failures.
Fixes: #226
> Schedule component: Fix uninitialized object

- components/panelmenu/panelmenu.ts
Child items of a PanelMenuSub were linking to their parent's url attribute.  Now link to child url attribute.
> PanelMenuSub child item url link fix

- components/paginator/paginator.ts
The onPageChange $event of Paginator doesn't expose the actual new page number.
> Add new page number to onPageChange $event

- showcase/demo/datatable/datatableselectiondemo.html
The commit for #284 changed the functionality of unselecting a row in single mode and dropped the requirement for having the metakey selected during the click. The documentation still referenced needing the meta key pressed. This PR updates the documentation.
If the intention was to still have the metakey selected to unselect a row in single selection mode (The original issue only made reference to multi selection mode) let me know and I can create a ticket and PR with the fix. Otherwise, this update to the docs should be good.
Thanks!
> Updated documentation to match change from #284.

- components/calendar/calendar.ts
- components/slider/slider.ts
- showcase/demo/slider/sliderdemo.html
- showcase/demo/slider/sliderdemo.ts
An application I've been working on uses a group of related sliders to assign a fixed quantity of something among a number of sliders. In this scenario, the maximum value for each slider should be the total quantity, since any slider could have the entire quantity assigned to it, but the range of each slider should be capped dynamically such that it cannot be increased past the point where the sum of all slider values is equal to the total quantity. (The payment slider at https://www.humblebundle.com is similar to what I'm trying to develop, though theirs readjusts the other sliders automatically).
To allow for this, I added "limitedMin" and "limitedMax" attributes as inputs to p-slider and changed the logic in the slide function to prevent the value of the slider from exceeding these …
> Added a "Limited Range" option for p-slider

- components/dropdown/dropdown.ts
Repro:
1. Create a Dropdown
2. Open your page in Firefox
3. Try to choose an element from the list
4. You will get an Exception
This is caused by an attempt to use `event ` variable in `onItemClick `function of `Dropdown `class, which is not defined.
> FIX: ReferenceError: event is not defined in Firefox

- components/fileupload/fileupload.ts
Hello,
I try your fileupload component with the beta14 and I can not add a header (authentication token) to the upload command.
After this modification, the upload works.
Could you include this proposition in your next release ?
Thanks,
Frederic.
> Open fileupload request before onBeforeUpload for header modification

- components/datascroller/datascroller.ts
It'd be nice to be able to use the DataScroller in such a way that it can reused for different data sets. For example, an infinite scrolling list that's searchable by the user.
When the user first arrives on the page, a set of search results appear. The user can then change the search criteria to provider better results for their specific need. The onLazyLoad handler is aware of the search criteria and returns the data accordingly. In order for this to work though, the scroller needs to be reset, so the loaded data starts again at the beginning.
> Allow resetting of the DataScroller

- components/datatable/datatable.ts
When you enter a whole number in the filter if installed 'endsWith' mode
there is an exception:
EXCEPTION: TypeError: value.indexOf is not a function vendor.bundle.js:46281
[filter]="true" filterMatchMode="endsWith">
https://github.com/primefaces/primeng/issues/582
> fix for: github.com/primefaces/primeng/issues/582

- components/overlaypanel/overlaypanel.ts
Hi !
Just a little method in OverlayPanel class for explicitly recalculate the panel position.
In my head, this is in the same philosophy that Dialog's center method.
For example (in my case), this can be use to refresh the OverlayPanel position when its content changes.
Actually in my case, without this PR, the "most beautiful" walkthrough that I found was to bypass the private TypeScript policy of _this.el_ to get the ElementRef of 
```javascript
(<any> this._overlayPanel).domHandler.absolutePosition (
(<any> this._overlayPanel).el.nativeElement.children[0], 
this._saveEvent.currentTarget || this._saveEvent.target
);
```
That's a bit disgusting...
I'm open to all your suggestions :)
> OverlayPanel : add refreshPosition

- components/dropdown/dropdown.ts
Changed to search instead of startsWith.
It's easier to find the available options in the dropdown.
> Use contains for dropdown filter

- components/accordion/accordion.ts
Clicking on a disabled accordion tab was following the anchor tag hash.
Not sure that was the desired behaviour. Just in case it helps, a small fix to return false when toggled & disabled.
> Disables click on disabled accordion tab

- package.json
PrimeNG is Published by MIT License, but "Apache 2.0" is written in package.json. so I revise this signage.
> Revise License

- index.html
Noticed that there's an error message in the console in Firefox related to the character encoding of the page. Because it was missing there was a possibility some of the text to be rendered incorrectly. See screenshot for reference.
> Add proper character encoding

- components/dom/domhandler.ts
It is assumed that padding and border widths can only be integral values in px units. But if CSS sets padding and border width in ems, this is likely to result in a floating value when converted to px.
Using parseInt can result in the height being overestimated by 0 to 4 px.
> Correct error in height measurement

- components/growl/growl.ts
Before change, some string like "first line. <br> and  here goes the second line." do not work as expected.
This revision brings the flexibility without security risks. (eg. 'first line <br> second line.<script>alert("lalala")</script>' comes with no alert dialogue.)
> Support HTML in growl message

- components/datatable/datatable.ts
Use ng2 elvis-operator style protection for data field sub-properties that could be undefined to help prevent `Cannot read property 'X' of undefined` exceptions.
**For example:**
In the following datatable column declaration, primeng datatables would throw a `Cannot read property 'c' of undefined` exception if `b` was `undefined`. It is often the case that extended field sub-properties are present for some collections/rows, and not present for others. This PR solves this problem, while still allowing primeng datatables' built-in features that rely on the fully-qualified `field` property (such as sorting and filtering) to work correctly:
`<p-column field="a.b.c" header="C"></p-column>`
> Field undefined extended sub-property protection

- components/progressbar/progressbar.ts
- showcase/demo/progressbar/progressbardemo.html
It would be nice to let user to define '%' as input parameter. It allows user to hide '%' or change it to some other unit e.g. 'MB' . With default '%' the backward compatibility should be preserved.
> Input parameter 'unit' added to ProgressBar component

- components/panelmenu/panelmenu.ts
PanelMenu allways fire event.preventDefault(), so anchor tag can't href to external tag
> Fix bug: PanelMenu not opening external links

- components/listbox/listbox.ts
Currently listbox's events don't behave according to their documentation: they just pass the original event instead of also passing the currently selected value.
> Listbox's events should pass the current value

- components/datatable/datatable.css
I found that when add a theme.css, the definition of `.ui-widget-header { border: 1px solid #d9d9d9; }` whihin the theme.css will override the definition of
`.ui-datatable-scrollable-header { border: 0px none; }`, so I just move the `border: 0px none;` from **.ui-datatable-scrollable-header** to **.ui-datatable-scrollable .ui-datatable-scrollable-header** to make sure that the .ui-datatable-scrollable-header having no border.
> Ensure no border of .ui-datatable-scrollable-header

- components/datatable/datatable.ts
Have one problem in fix #1182
```
null === undefined // false
null == undefined // true
null === null // true
```
We need use just "==" to check if have value in the field, it's wrong use "===".
If we try check a JSON with null values, the exception keep occurring.
> Revert #1182 patch 1

- components/fileupload/fileupload.ts
Issue https://github.com/primefaces/primeng/issues/1332
In documentation onBeforeUpload	 event is described:
`Callback to invoke before file upload begins to customize the request such as adding header and post parameters.`
But some frameworks require post parameters to be appended to FormData before files.
When onBeforeUpload event emits xhr and FormData, there is no way to "prepend" any data to FormData object, so some backend frameworks will return errors like this:
``` Unable to expose body parameter `exampleParameter` in streaming upload!
Client tried to send a text parameter (exampleParameter) after one or more files had already been sent.
Make sure you always send text params first, then your files.
(In an HTML form, it's as easy as making sure your text inputs are listed before …
```
> fileupload onBeforeUpload should be fired before appending files to FormData

- components/confirmdialog/confirmdialog.ts
acceptVisible and rejectVisible is initialized just by declaration, so, if you change the value first time to false, the (ternary if) ever fail and the value will never change again.
> Fixed #1505 - acceptVisible and rejectVisible not changing value

- components/fileupload/fileupload.ts
In auto mode, if a file doesn't pass validation, a POST is still being done with an empty files list. The test does a boolean check on the files array instead of checking the length. This change calls the hasFiles() function which performs the proper check.
> Only upload when files array is non-empty in 'auto' mode

- components/fileupload/fileupload.ts
- showcase/demo/fileupload/fileuploaddemo.html
Fileupload component didn't allow it's users to set headers anymore after 1.1.0. because of the moved onBeforeUpload event.
Added onBeforeSend event after the open method for the XMLHttpRequest to allow setting of headers once again.
> Added a new event to file upload

- components/datatable/datatable.ts
This fixes https://github.com/primefaces/primeng/issues/1613
---
Plunkr demo: http://plnkr.co/edit/25NZ7M?p=preview
**Current behavior**
If the table has `[scrollable]` set to `true`, the method passed to `[rowStyleClass]` is never called. If the table is _not_ scrollable, the method is called as expected.
**Expected behavior**
The method passed to `[rowStyleClass]` should be called for every row; even if the table is scrollable.
**Minimal reproduction of the problem with instructions**
Plunkr demo: http://plnkr.co/edit/25NZ7M?p=preview
1. Define a table with `scrollable` set to `true`:
1. Pass a method to `rowStyleClass` that should be called with row data:
```html
<p-dataTable [value]="items" [scrollable]="false" [rowStyleClass]="tableOneHighlight">
<p-column field="id" …
```
> Row should call getRowStyleClass even if table is scrollable

- components/datatable/datatable.ts
Same idea as the new expandableRowGroups functionality. Puts table rows into the tabIndex of page. The enter button now toggle rows. Add preventDefault to toggleRows() function.
> Keyboard accessibility for Row Expander

- components/dom/domhandler.ts
I had some issues with fading. i found out that in some of my browsers and in electron the value of opacity will have a comma instead of a dot as float separator. thats common for germany, because we write floats with comma instead of dot. maybe the local settings of the browser cause this issue but this code version is more stable in any case.
> Fade animations fails on some locales

- components/datatable/datatable.ts
Fixes #1206
Allows paged datatable header checkbox to behave correctly when programmatically selecting entire dataset
> Header checkbox may not always get checked

- components/treetable/treetable.css
- components/treetable/treetable.ts
- showcase/demo/treetable/treetabledemo.html
This PR enables TreeTables to be used via keyboard and screen readers for improved accessibility. 
It converts the expand/collapse toggle from a span-tag into a button tag. Adjusted css rules ensure that there is no visible difference. It adds two new attributes `labelExpand` and `labelCollapse` with appropriate defaults ("Expand" and "Collapse") in order to indicate the current state to screen readers.
> added keyboard and screenreader support to TreeTable

- components/calendar/calendar.ts
Drastically improves initial render times for Calendar component when there are a large number of calendars on the page (>100).
In a test rendering 100 calendars render speed dropped from >4seconds to render, to less than 400ms.
Fix involves only rendering the calendar component when the overlay is display (either when the input field has focus, or is set to inline mode).
Fixes remaining issues for #1785
> Improve Calendar initial render performance

- components/dropdown/dropdown.ts
- showcase/demo/dropdown/dropdown.html
**panelStyleClass**
Applying attribute `appendTo` to the dropdown element does not have any connection to the `original ui-dropdown` container element.
This means when we want to style a different look to a dropdown, we cannot apply the same style to its `ui-dropdown-panel` element since it is attached for instance to the body and they have no custom class on them.
This is why, we have to introduce `panelStyleClass` to make sure we can collaborate with the original `ui-dropdown` element.
**panelStyle**
Attribute `panelStyle` is very useful when we want to apply a custom width or any other style to `ui-dropdown-panel` element when `appendTo` is also applied.
> Added panelStyle and panelStyleClass attributes to dropdown component

- components/dropdown/dropdown.ts
Current state:
1. panelVisible is used in ngClass - changing it starts angular change detection
2. n-time dropdowns will create n-time global body listeners which when clicked on body will start n-time change detection 
Fix:
1. When panel hides - unbind global listener
2. it will be initialized once again when dropdown is shown.
> Unbind global listener when dropdown panel hides issue #1749

- components/button/button.ts
This simple change closes #1685 and #1719. I don't know what was the point of this change, but it was okay before commit b976a9d.
> Fixed #1685 and #1719

- components/common/api.ts
`DomHandler` was a missing provider when one wanted to subclass and
modify some of primeng components. When we export it in public API
it'll be possible to subclass any component or subcomponent.
> Expose `DomHandler` in library API.

- components/multiselect/multiselect.ts
Making sure that the label is updated after ngModel changes, and writeValue function gets called.
Submitted as fix for issue #1696
> Fixed label rendering issue with dynamic ngModel

- components/inputmask/inputmask.ts
When setting the autoClear value to "false" we want to preserve the value entered by the user.
> Inputmask autoclear bug fix

- components/tabview/tabview.css
This is invalid CSS and breaks in the browser.
issue: https://github.com/primefaces/primeng/issues/1900
> Invalid css in tabview

- components/schedule/schedule.ts
Not sure if this counts as a defect fix or a minor feature. I believe issue #1942 is caused by the missing attribute that this PR adds.
At the moment it is not possible to pass the timezone attribute to Fullcalendar through the Schedule component. Please consider including this feature in 2.0 final.
> Add timezone property to Schedule

- components/common/api.ts
- components/tree/tree.ts
This adds the styleClass property for ui-treenode elements. The documentation shows 'styleClass' as a property of the TreeNode API, however the current codebase does not include this.  Issue #1963 describes this further.
> Implement styleClass for ui-treenode element on Tree

- components/autocomplete/autocomplete.ts
To be able to customize your template to display the selected item from the list. For example, to add your event handlers to the selected item.
> Added support template for selected item in Autocomplete

- components/chart/chart.ts
If you destroy and re-init the chart every time it needs to be refreshed, it will not smoothly animate between data sets. Chart.js provides an `update()` method for exactly this purpose.
#2102
> Use chart.js's `update()` method when refreshing

- components/dialog/dialog.ts
Fixing bug where large dialog content or small screens would cause the dialog to be positioned outside the viewport. See issue #1925
> Dialog positioning fix

- components/schedule/schedule.ts
This change will make it possible to dynamically update the editable property of the schedule using the fullcalendar methods [https://fullcalendar.io/docs/utilities/dynamic_options/](https://fullcalendar.io/docs/utilities/dynamic_options/)
Using the ngOnChanges hook, we can dynamically update most fullcalendar options.
Closes #2020
> Schedule: enable dynamically updating all input properties

- components/autocomplete/autocomplete.ts
Render options just after open autocomplete for better performance when have multiples componentes in the same page. 
Fix #2166
> Render just after visible - fix #2166

- components/dropdown/dropdown.ts
In case of appendTo property is used on p-dropdown when typing into the filter the container of the options goes to the upper left corner. This is because appendTo property is not checked and position is always calculated as a relative position. In the proposed fix i check if this.appendTo property is used and if so, absolutePosition function is called instead of the relativePosition.
> Dropdown panel misaligned on filtering with appendTo

- components/datalist/datalist.css
- components/datalist/datalist.ts
- showcase/demo/datalist/datalistdemo.html
See #2255 
Not sure if I'm following the css conventions of the framework.
> Fix for #2255

- showcase/demo/chart/chartdemo.html
The missing "dot" for element._index added time to debugging events. Removed extraneous 't' from sample code
#2371
> Spelling fixes on chart documentation

- components/autocomplete/autocomplete.ts
- components/calendar/calendar.ts
- components/checkbox/checkbox.ts
- components/chips/chips.ts
- components/inputmask/inputmask.ts
- components/inputswitch/inputswitch.ts
- components/multiselect/multiselect.ts
- components/radiobutton/radiobutton.ts
- components/spinner/spinner.ts
- components/togglebutton/togglebutton.ts
- components/tristatecheckbox/tristatecheckbox.ts
- showcase/demo/autocomplete/autocompletedemo.html
- showcase/demo/calendar/calendardemo.html
- showcase/demo/checkbox/checkboxdemo.html
- showcase/demo/chips/chipsdemo.html
- showcase/demo/inputmask/inputmaskdemo.html
- showcase/demo/inputswitch/inputswitch.html
- showcase/demo/multiselect/multiselectdemo.html
- showcase/demo/radiobutton/radiobuttondemo.html
- showcase/demo/spinner/spinnerdemo.html
- showcase/demo/togglebutton/togglebuttondemo.html
- showcase/demo/tristatecheckbox/tristatecheckboxdemo.html
This PR adds `inputId` property in most input components. This allows the developer to use them with a label:
```
<label for="checkbox">Checkbox</label>
<p-checkbox inputId="checkbox"></p-checkbox>
```
> Add inputId property where it makes sense.

- components/calendar/calendar.ts
I have added this fix so that when you are opening the calendar and you have set the attribute [selectOtherMonths]="true", you will be able to select the next month grayed out dates. Without this fix you will get NaN/NaN/NaN.
> Next month grey date was throwing Nan/Nan/Nan

- components/dropdown/dropdown.ts
- showcase/demo/dropdown/dropdown.html
Add the ability to set a placeholder to the `<input>` used to filter entries in the list.
Example for `<p-dropdown filterPlaceholder="type here...">`:
> Dropdown: Add `filterPlaceholder` attribute

- components/datatable/datatable.ts
- showcase/demo/datatable/datatabledemo.html
- showcase/demo/datatable/datatableselectiondemo.html
- showcase/demo/datatable/datatableselectiondemo.ts
Add `headerCheckboxToggleAllPages` DataTable property to allow the header checkbox on paged DataTables with checkbox multiple selection enabled to toggle the selection of items across all pages. Previously this was only possible via the `onHeaderCheckboxToggle` event--however, doing so produced strange results where the header checkbox would remain checked even if only the current page's items were selected. This change provides the expected results. This is an improvement over the original fix provided in #1412.
Update demo/documentation to reflect new property.
I created a new property for this so as to not alter the previous behavior of the header checkbox on paged DataTables--however, if that isn't a concern we could simplify this and remove the new property by just having the header …
> Feature Request: Add DataTable Checkbox Header Toggle All Pages Option

- components/fileupload/fileupload.ts
- showcase/demo/fileupload/fileuploaddemo.html
Defect Number
#2745
Fileupload class calls the url without sending auth cookie or Kerberos token, I have created a boolean variable which will fix this issue. its a minor change and is working as expectedly.
`withCredentials: boolean;`
if set to true on the component it will add Authentication cookie/Kerberos token.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
I have also created the issue on stackoverflow which i will close
http://stackoverflow.com/questions/43866580/angular-4-primeng-upload-url-windows-authentication-cookie
> fixed xhr request not sending credentials onupload

- components/datatable/datatable.ts
Previously, table fields/cells with commas would throw off the CSV export formatting. This change surrounds fields with double quotes in case they contain commas or other special characters that would throw off the CSV formatting (following RFC 4180 (see https://tools.ietf.org/html/rfc4180#section-2)).
Fixes #2460
> fix(DataTable): Support comma fields in CSV export

- components/datatable/datatable.ts
Use dt.visibleColumns().length rather than columns.length for colspan
on subheader mode row grouping.
#2814
> Fixed #2814 - rowgroupheader colspan not tracking visible columns

- components/dialog/dialog.ts
Added the ability to simply center and position the dialog just based on the screen top position. Helps with dialogs with dynamically generated content that don't center in the screen well since their height is not known at the time the dialog is initially rendered.
> Center dialog horizontally if only positionTop is used

- components/calendar/calendar.ts
We need to remember two points to know the reason for this change
1. this.pm code snippet always give time zone based on default date or current time zone.
2. this.hours is always less than 11 due to previous code lines
> Calendar always populates AM

- components/calendar/calendar.ts
Hello, Team.
Calendar's icon (viewed with set binding `[showIcon]="true"`) is focused when use [Tab] key without set binding `[tabindex]` .
And, cannot see the effect focused on the icon, in ULTIMA Theme.
(That is what I am in trouble)
When the Tab key is pressed continuously, calendar is shown when focus into textbox part.
So, I think that there is no need to focus on the icon.
Please scrutiny it.
> Prevent focus on calendar icon

- components/growl/growl.ts
Fix #2846
The item was removed from values before emit onClose with the value, so in this case index of value is the next (if is the last, return undefined).
> Fix #2846 (event onClose receiving wrong element)

- components/captcha/captcha.ts
captcha component now registers a callback that can be triggered through onload parameter of reCAPTCHA
This fixes https://github.com/primefaces/primeng/issues/2584
now you can add reCAPTCHA script as follows:
`<script src="https://www.google.com/recaptcha/api.js?render=explicit&onload=recaptchaLoaded" async defer></script>`
once its loaded, it will call recaptchaLoaded which will be registered globally by captcha component and it will render the captcha.
Also, the callback name is configured through the "callback" attribute
> Captcha component can now be triggered through onload parameter of reCAPTCHA

- components/calendar/calendar.ts
When selectOtherMonths is enabled on the calendar, and a date on a different month is selected, it will now switch to that month
> Improve selectOtherMonths to switch current month displayed

- src/app/components/calendar/calendar.ts
Check style.display of this.overlay in case of IE9/10 ==> because offsetParent will _not_ get null when datepicker (=overlay) gets hidden.
> fix(calender): make button clickable on  IE9/10

- src/app/components/autocomplete/autocomplete.ts
Hi,
After clearing an autocomplete input - it's very useful to emit an event.
From a personal prespective - this change is crucial for my project.
Thanks,
Ohad.
> feat(autocomplete): Add cleared input event emitter (OnClear)

- src/app/components/dom/domhandler.ts
fix #3195 
- When use `resizableColumns` it register mousemove event so every mouse move it `ngAfterViewChecked`. 
- And in `ScrollableView` if it not frozen, it call `alignScrollBar` and it use `calculateScrollbarWidth`. 
- `calculateScrollbarWidth` create a element for calculate scrollbar width (it touch a dom)
- So every mouse move. it create and remove element every time.
- cache `calculateScrollbarWidth` result. so it calculate only once
> cache calculateScrollbarWidth for improve performace

- src/app/components/datatable/datatable.ts
Neither a JS literal nor a variable use `this `context. This mades `notEquals `unable to access equals. Simplest way to fix it was rewrite `notEquals`. Converting the litteral to a true object would also fix the problem but require more redesign.
[#3388](https://github.com/primefaces/primeng/issues/3388)
> Fixed filterConstraints.notEquals

- src/app/components/datatable/datatable.ts
> Make sure datatable has a loadingIcon input

- src/app/showcase/components/messages/messagesdemo.html
The `showSuccess()` function called by `Success` button was missing from demo code
> doc(messages): add missing function in demo

- src/app/components/treetable/treetable.ts
DataTable has these `tableStyleClass` and `tableStyle` input so users can customize the class and styles of the table, the TreeTable also use table but don't have these inputs, this makes it hard to make the treetable match the style of our own design.
So this PR add these two input to TreeTable.
> add tableStyleClass and tableStyle to TreeTable

- src/app/components/tooltip/tooltip.ts
- src/app/showcase/components/tooltip/tooltipdemo.html
Essentially, if tooltip has hideDelay, mouseenter handler will manually clear the hideTimeout and destroy() tooltip before activating. Fix for [issue #3462](https://github.com/primefaces/primeng/issues/3462).
> Tooltips - fix for hideTimeout bug due to rapid mouseenter/mouseleave events

- src/app/components/picklist/picklist.ts
Found this feature in Roadmap. So if it will be done in next release remove pull request.
> Emit moveAllToSource/Target only after input arrays are changed

- src/app/components/datatable/datatable.ts
https://github.com/primefaces/primeng/issues/1827
I have already made PR for this ugly bugs in April. You promised to solve it in a next release, yet this ugly bug is here. Now I reduced the PR to only two line changes, without feature to use rowStyleMap. You can continue to use rowStyleClass which is run out of scope and breaks Angular concept, this fix only stops to introduce extra bug, for binding to class and ngClass at the same time (which should be done also).
This is old PR: https://github.com/primefaces/primeng/pull/2583
> Fixing #1827 Again!

- src/app/components/multiselect/multiselect.ts
Change to the way the label is built to handle cases where the label is null
> Safer MultiSelect label display with null check

- src/app/components/schedule/schedule.ts
- src/app/showcase/components/schedule/scheduledemo.html
This PR adds the official `editEvent(event)` method of FullCalendar to the Schedule component. It renames the internally used `editEvent` method to `_editEvent()` and also renames the internal `findEvent()` method as well. Updates to showcase documentation are included.
Please let me know if there is anything I can do to help get this change merged. Thanks so much for all your hard work!
> Add official editEvent method in Schedule component

- src/app/components/fileupload/fileupload.ts
Fix for #3664 
The issue was a missing ***#fileinput*** template reference variable when mode is *'basic'*.
```html
<span class="ui-button ui-fileupload-choose ui-widget ui-state-default ui-corner-all ui-button-text-icon-left" *ngIf="mode === 'basic'" . . .
. . .
<input #fileinput type="file" . . . 
```
> Fix #3664 Added the missing template reference

- src/app/components/dropdown/dropdown.ts
Spaces are no longer blocked when the dropdown is open. If the dropdown is closed, space will still open it, preserving the intended functionality.
> Bug fix for #3657 -

- src/app/showcase/components/chart/doughnutchart/doughnutchartdemo.html
Simple typo fix for tab headers
I am not changing anything about the code, but a simple typo at documentation :)
> fixing typo at doughnutchartdemo.html

- src/app/components/checkbox/checkbox.ts
- src/app/components/radiobutton/radiobutton.ts
https://github.com/primefaces/primeng/issues/3578: I've added unique dynamic classes to the checkbox and radio button features, so that the labels for these components can be styled based on checked, focused, and inactive states. I've searched through all of the components and have only found these two to be using ```<label>``` tags.
###Defect Fixes When submitting a PR, please also create an issue documenting the error.
###Feature Requests Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes. Smaller scaled feature implementations such as adding a property to a component will be considered for merging.
> add state css classes on checkbox and radio labels

- src/app/components/autocomplete/autocomplete.ts
current input when tabbing out of the control without highlighting a new value
> AutoComplete should clear highlight option on suggestions change

- src/app/components/datatable/datatable.ts
1. Add 'expandedIcon' and 'collapsedIcon' as @Input property to Datatable with default values
2. Use these input properties to add class to the <a> link of expander in pTableBody
> #3744 - Make expand/collapse icon configurable in DataTable

- src/app/components/radiobutton/radiobutton.ts
Currently the onClick event only gets fired only when the user clicks on the radio-button.
When toggling the button using the label, the event does not get fired.
Here's the fix.
> Label click should trigger Radio onClick event

- src/app/components/datatable/datatable.ts
While using filter with datatable the setTimeout is not cancelled before a new one is created. As a result if you type n characters fast enough (faster than filterDelay property value) the this._filter() method is called n times instead of one.
> Bug with filtertimeout cancellation on DataTable and Bug with footer column template now showing

- src/app/showcase/components/inputtext/inputtextdemo.html
In the input text documentation under the source tab there is written **{text}}** instead of **{{text}}**
> Fix small typo in the input text showcase

- src/app/components/colorpicker/colorpicker.ts
When the HTML page is scrolled, the color/hue selection does not work : there is a vertical offset between the mouse click location and the selected zone in the color picker
> Bad color/hue selection with scrolled page

- src/app/components/calendar/calendar.ts
I'm sumitting a small fix.
Following modification in primeng introduce date template in calendar component:
89e7d3aee0d4ca1dea870af01458d36b62d88513
In our app we don't use date template but upgrading primeng we had a regression on the display:
Not completly sure why, it's seems than the new `span` level introduced by 89e7d3aee0d4ca1dea870af01458d36b62d88513 for the 'no custom template case' didn't do any good.
I believe that's not our app, as we don't have many style on calendar, but primeng css rules for `.ui-datepicker-calendar td a` and `.ui-datepicker-calendar td span` that are applied two times now (once for the `a` and once for the new `span`).
Anyway, angular `ng-container` are here for that. It's good to used them, and recommended by angular doc, instead of adding span or div …
> fix(calendar): use ng-container instead of span

- src/app/components/calendar/calendar.ts
###Feature Request
I added an output event to the calendar component that will fire when the user changes the date inside the calendar using the previous and next buttons.
In my application only 14 specific dates in the calendar should be selectable. There is only an input for black listing dates. I would have to input all possible dates that are not my 14....forever/eternity.
I created an event that lets the parent know when the calendar view has changed months and provides the current month and year. The parent can then use that data to create a small list of unavailable dates inside that scope and update the disabled dates input property.
> Added `onMonthChange` output event to calendar component

- src/app/components/datatable/datatable.ts
#3930 
The problem was that the HTML markup of the footer element was located above the element of the expanded item.
> #3930 fixed wrong order of footer and expanded rows

- src/app/components/multiselect/multiselect.ts
When multiselect is used as datatable column filter, clicking on multiselect option triggers the column sort.
> MultiSelect as a table filter triggers sort

- src/app/components/orderlist/orderlist.ts
…re-order has occurred consistent with the current move functionality.
Currently the callback only occurs when clicking the move buttons. On drop, the list is re-ordered but the callback is not called.
https://github.com/primefaces/primeng/issues/3820
> #3820 on drop in orderlist call the onReorder.emit method

- src/app/showcase/components/tree/treedemo.html
The documentation of the Tree API shows a wrong name for the attribute that sets the horizontal/vertical orientation of the tree. The attribute name is "layout", not "orientation".
> Small fix in the documentation for the Tree API

- src/app/components/datatable/datatable.ts
Removed [ngClass] property, 'max-height' from .ui-datatable-scrollable-wrapper. This looks like it was originally intended to be [ngStyle], as it is adding a style (max-height), not a class. The scrollHeight property is already correctly added as a max-height style on another element, .ui-datatable-scrollable-body.
Issue: #4213
> Removed non-functional template code.

- .travis.yml
This configuration file sets Travis up to execute primeng tests. In order to execute tests automatically on commits and pull requests, it needs to be enabled on https://travis-ci.org by a github repository admin. (Travis is free of charge for open source projects).
> Travis configuration for running tests

- src/app/components/datatable/datatable.ts
I believe this will address the issue #4119.  The problem is that the datatable was emitting the selection after it fired the onRowSelect event.  This makes it seem like the selection array never got updated.
datatable radio/checkbox selections not updating selection array #4119
> Update datatable to emit selection before rowselect

- src/app/showcase/components/datatable/datatabledemo.html
The property should be expandedRowsGroups not expandedRowGroups.
[issue: 1721](https://github.com/primefaces/primeng/issues/1721)
> Fix doc typo: expandedRowsGroups

- src/app/components/multiselect/multiselect.ts
Protect this.value in ngDoCheck function.
If I modify  option property and then try to unselect an item I get an error in ngDoCheck
Hard to create a plunker but I can try if it is needed
> Protect this.value in ngDoCheck function

- src/app/showcase/components/dropdown/dropdowndemo.html
Fix typo in dropdown showcase. Change "optionField" to "optionLabel" as featured on 4,3 release.
> Fix typo "optionField" dropdown showcase

- src/app/components/calendar/calendar.ts
Addresses #3798 #4312 
The basic issue was that the 'hour' field was showing up as `0` when crossing back and forth between `12` and `1`. I was also seeing the `AM` / `PM` field not properly updating.
As a side note, this really isn't how I wanted to address this fix, but I didn't want to turn this into a refactor effort. I think the existing calendar code solves the problem of showing 12-hour time in a very inefficient way, and could gain long-term sustainability with a little bit of refactoring.
The current implementation keeps track of some offset that is calculated differently whether you are in 12 or 24-hour mode. It then sets the actual `Date` object value with the inverse calculation of the stored hour. I feel like a more proper implementation would save the `Date` value object the …
> fix calendar 12-hour format for switching between AM/PM

- src/app/components/dom/domhandler.ts
In Chromium with German locale element.style.opacity returns a string with a comma instead of a dot – as in "0,15" instead of "0.15". This results in a bug in the animation, making it stop after running tick() once. Replacing "," with "." fixes the problem.
See https://github.com/primefaces/primeng/pull/1491#issuecomment-342158634
> Fade animation issue with some locales

- src/app/showcase/components/tree/treedemo.html
This fixes only three small typos...
> Fix minor typos in the Tree documentation

- src/app/showcase/components/datatable/datatabledemo.html
Fix error in example code of the simple table example.
When using the code of the example without modifying - the loading circle does never disappears, because the binding is fixed to true. Although in the running code sample the binding is correct.
> Correct example code.

- src/assets/showcase/css/site.css
The last items of sidebar were not be visible because 100% value on height property.
When height property was 100% without subtract top property value, the last items of sidebar was hidden.
> Adjust site.css to show last items of sidebar.

- src/app/components/datatable/datatable.ts
Both of these methods reference 'event' without it being defined.
> DataTable uses an event without referencing it

- src/app/showcase/components/autocomplete/autocompletedemo.html
Fixed small mistake in the docs.
Closes #4604
> Fixed docs class name for autocomplete list item

- src/app/components/utils/objectutils.spec.ts
- src/app/components/utils/objectutils.ts
In order to avoid infinite recursion, the method added a "visited" flag as property to the compared objects. This caused the method to raise an error when "frozen" (read only) objects were compared that cannot be extended. This fix uses a stack to memorize visited objects instead of setting a property on the objects, and therefore allows frozen objects to be compared as well.
In real life, this can happen when feeding a PrimeNG data table with data queried using the Apollo GraphQL client (see issue #4600).
This fix also adds some unit tests to confirm proper behavior of ObjectUtils.equals().
> Make ObjectUtils.equals() work with frozen objects (fix #4600)

- src/app/showcase/components/schedule/scheduledemo.html
This fixes issue https://github.com/primefaces/primeng/issues/4645
It updates the schedule documentation by adding the instructions required to activate the fullcalendar i18n functionality as per https://fullcalendar.io/docs/text/locale/
> Fix issue #4645: update localization documentation

- src/app/components/growl/growl.ts
I just came across a requirement that the Growl panel needs to be sticky if the message is not successful.
With current version, if you set sticky property on the fly, it won't take effect immediately because the timer is already running.
I think this could be a common one and this pr will fix it.
> Make sticky property work immediately in Growl when set to true

- src/app/showcase/components/checkbox/checkboxdemo.html
I believe this is a typo - myFormGroup.get is a method, not an array.
> Checkbox demo syntax error fix

- src/app/showcase/components/checkbox/checkboxdemo.html
.get['cities'] should be .get('cities') according to https://angular.io/guide/reactive-forms#inspect-formcontrol-properties
I've tested this and can aprove this.
> Fixed angular formGroup example

- src/app/components/inputmask/inputmask.ts
When updating model value, synchronize component's `value` with model.
InputMask.value same with initialized value, and not updated after component was initialized.
So, cannot get current, latest value from my component.
> InputMask component's value not synced

- src/app/components/selectbutton/selectbutton.spec.ts
- src/app/components/selectbutton/selectbutton.ts
Currently, preselection only works by reference, not by value. Added this change in line with other components.
With this change, user will be able to pass match key and compare the properties against it. So it will be preselected.
> Preselection by value for SelectButton

- src/app/components/picklist/picklist.ts
Fixes #[5046](https://github.com/primefaces/primeng/issues/5046) Picklist multi select and move does not work if selecting items in reverse order.  Let us sort the items in the visual order before performing the move operations.
> Fix 5046: sort PickList items before move

- src/app/showcase/components/chart/chartdemo.html
* Previously, it was up to the user to know that the charts.js library was not included with PrimeNG and that it had to be installed using npm.
* The proposed changes let the user know that they must install the 'chart.js' library and provides instructions on how to do so.
> Clarified the 'Charts.js' documentation.

- src/app/components/calendar/calendar.ts
- src/app/showcase/components/calendar/calendardemo.html
onMonthChange emitted when year and month dropdowns are changed
Attempt to resolve comment from previous PR relating to this issue
https://github.com/primefaces/primeng/pull/5264#issuecomment-370665886
#4708 - Calendar onMonthChange is not triggered when change in yearNavigator or monthNavigator
> Add onYearChange to Calendar

- src/app/components/inputmask/inputmask.ts
#5045 
- Prevent to update model when actually is not updated, applying the same behaviour of angular inputs 
- A lot of spaces that WebStorm removes following TSLint.
> #5045 Fix InputMask dirty state

- src/app/components/table/table.ts
Table header nested under `direction: rtl` ancestor behave currently unexpected:
After fix:
> RTL Support for Scrolling Table

- src/app/components/megamenu/megamenu.ts
**Feature Requests**
**Current behavior**
Currently, the MegaMenu ignores the "_visible_" attribute of the MenuModel being passed. So the user is not able to hide the menu items based on the Model attribute values.
**Desired behavior**
A user should be able to hide menu elements by passing _"visible": false_ in the MegaMenu.
> MegaMenu ignores visible property of MenuItem API

- src/app/components/spinner/spinner.spec.ts
- src/app/components/spinner/spinner.ts
The error: If decimal part was more than three digits than the decimal part was formated with thousand separator. After this bug fix only integer part is formated with thousand separator
> #2993 - Spinner: decimals are separated by the thousand separator

- src/app/components/orderlist/orderlist.ts
Current functionality prevents using inputs within the order list as part of a form when ability to remove from list is present. Removing from the list and then adding to the list will cause the item above to lose its current input value.
Lack of trackBy functionality prevents some common usage scenarios.
> Add TrackBy to OrderList

- src/app/showcase/components/dialog/dialogdemo.html
The documentation of dialog 
There was  word width instead height in minHeight property documentation
> #5356 - PrimeNG DialogBox Property

- src/app/components/galleria/galleria.ts
Partial fix for issue #5345. Added input variable  effectDuration disclosed in documentation, but not available. Set default to existing value in code. Although documentation states default value of 250. Passed new input variable to domHandler.fadeIn().
> Implement effectDuration for Galleria

- src/app/components/autocomplete/autocomplete.ts
#5369
- When remove items through backspace the ui-state-filled css class now is removed
> #5369 Fix AutoComplete ui-state-filled management

- src/app/components/calendar/calendar.ts
Change code to invoke function instead of return it.
Example:
`<p-calendar [timeOnly]="true" hourFormat="12" [utc]="true"></p-calendar>`
If `timeOnly` is true then the hours column displays the following text instead of the hours:
```function getUTCHours() { [native code] }```
The method was being returned instead of invoked.
Bug is only present for 12 hour time (24 hour code is OK).
> Wrong return value in calendar

- src/app/components/table/table.ts
Fixes issue #5095 - "disabled" property not working on tableRadioButton and tableCheckbox.
> Prevent Disabled p-tableRadioButton and p-tableCheckbox from Selecting Row

- src/app/showcase/components/dialog/dialogdemo.html
documentation update
remove duplicate autoAlign attribute in the doc.
> duplicate autoAlign attribute

- src/app/components/multiselect/multiselect.ts
When strickNullChecks is true in tsconfig.json, webpack returns an error in production environment if the MultiSelectModule is imported: "Type 'null' is not assignable to type 'HTMLInputElement'".
> Update multiselect.ts to avoid nullCheck errors

- src/app/components/inputtext/inputtext.css
Selector was using .input, which imho doesn't make any sense here. 
When (chromes) autofill feature happened, the label should have the same style as when the input if filled.
Fixes [#5472](https://github.com/primefaces/primeng/issues/5472)
> Fix style of floating label and (Chromes) autofill

- src/app/components/dom/domhandler.ts
This PR is going to simplify the work with the DOM. 
This function (`replaceElementWith`)  can be successfully used along with Angular directives to replace `element.nativeElement` with your own created element, and so on.
> Extend DomHandler with new method

- src/app/components/dialog/dialog.ts
The dialog focus functionality forces focus on the first button in the dialog. That functionality often isn't desired.
In our use case, we use a variety of text inputs in our dialogs which need focus instead of the cancel and confirmation buttons at the bottom of the dialog. This PR allows a consumer to disable the focus functionality and to handle it in the parent component.
> Allow disabling dialog button focus

- tslint.json
As Component suffix is never used in component classes in the whole project,
we expect this rule disabled in tslint.
Partially Fixes #5598
> [Fix #5598] ignore no-inferrable-types rule on class properties.

- tslint.json
As Component suffix is never used in component classes in the whole project,
we expect this rule disabled in tslint.
Partially Fixes #5598
> [Fix #5598] Disable component-class-suffix rule.

- src/app/components/table/table.ts
Fixes issue #5660 
Filter function modified to store the filter value immediately, instead of on timeout.  
This ensures that ALL calls to filter within the same timeout are applied, not just the last one.  
The filter is still not executed until the timeout.
> Fix table component only applying the last filter before timeout (#5660)

- src/app/components/multiselect/multiselect.ts
- src/app/showcase/components/multiselect/multiselectdemo.html
Add ui-multiselect-open class to ui-multiselect and typo fix for multiselect documentation.
Implements feature request in #5680 
> Add ui-multiselect-open class - Fix for #5680

- src/app/components/chart/chart.ts
ChartJS needs to return the generated legend HTML string.
Fixes https://github.com/primefaces/primeng/issues/5669.
Refers back to issue https://github.com/primefaces/primeng/issues/2035, the fix never seems to have been merged.
> Fixes ChartJS generateLegend. Needs to return the HTML string.

- src/app/components/table/table.ts
Very simple PR to fix the turbo table scrollbar appearing on top of the paginator due to it using padding instead of margin.
The documenting issue is https://github.com/primefaces/primeng/issues/5566.
> Frozen Table scrollbar overlaps paginator

- src/app/components/chart/chart.ts
- src/app/showcase/components/chart/chartdemo.html
See issue https://github.com/primefaces/primeng/issues/5126.
Also https://github.com/primefaces/primeng/issues/5748.
1) Fixes typo in doc that responsive mode is set to false by default.
2) Fixes typo in doc about using width="40w" height="80w" in responsive mode.
3) Fixes that width and height have no effect on the charts sizing in responsive mode.
> Fixes ChartJS responsive mode sizing

- src/app/components/breadcrumb/breadcrumb.ts
If `MenuItem` structure specifies an icon, let's draw that on the Breadcrumbs.  Applying a class of `ui-menuitem-icon` would allow user to customize display, if desired.
Additional fix is provided for customizing `home.icon` in the case where `home.routerLink` is defined.
It can solve #4891
> Support icon field of MenuItem

- src/app/components/steps/steps.ts
This css class can be used to skin all the previous steps of a wizard differently.
In our case we wanted to show checkmarks:
> add ui-state-completed class to steps

- src/app/components/table/table.ts
pi pi-arrow-down and  pi-arrow-up ui are visble when table is redered for first time
> pi pi-arrow-down and pi-arrow-up ui are visble when table is redered for first time  for orderableColumns

- src/app/components/multiselect/multiselect.ts
this.visibleOptions is already there
On line 521 onFilter already filters this.visibleOptions.
Later in line 546 getVisibleOptions used the same logic again to create the visibleOptions.
Here we can just return the existing this.visibleOptions or this.options.
> Don't repeat yourselfe

- src/app/components/fileupload/fileupload.ts
If the `accept` property is set for example to '.txt,.pdf', then file upload won't accept files like `test.PDF` or `logs.Txt`, that is not expected behavior.
> FileUpload accept should be case insensitive

- src/app/showcase/components/toast/toastdemo.html
The GitHub link was directing to the growl page, which was probably a copy-paste mistake.
> Corrected the GitHub link

- src/assets/showcase/data/countries.json
Campaign for rectifying the name of Taiwan (R.O.C)
> country rename

- src/app/components/dialog/dialog.ts
- src/app/components/overlaypanel/overlaypanel.ts
We have a panel on layout, subscription to onHide. Once we navigate to another form, onDestroy is triggered and then onHide is emmited, but it was not supposed to as dialog was not even shown.
N/A
> Update overlayPanel and dialog. Emit onHide only if panel/dialog is visible.

- src/app/components/inputmask/inputmask.ts
This PR addresses the accessibility improvements outlined in [issue #6465 ](https://github.com/primefaces/primeng/issues/6465).
This PR adds "aria-label" and "aria-required" attributes to applicable PrimeNG input components. The changes are small, but impactful for visually impaired users with screen readers. This will improve PrimeNG's overall accessibility.
The biggest change made to any of the input components was the addition of the following code to the typescript:
The addition of [attr.aria-label]="ariaLabel" [attr.aria-required]="ariaRequired" to the input element in the template and the addition of @Input() ariaLabel: string; and @Input() ariaRequired: boolean; to the list of inputs.
NOTE - The "required" attribute does a lot of what the "aria-required" attribute does, but the …
> input mask accessibility improvement

- src/app/components/calendar/calendar.ts
This resolves `currentMonth` and `currentYear` not being properly updated in `onDateSelect`.
https://stackblitz.com/edit/github-uggfuf-fuzz2b?file=src/app/app.component.html
1) Go forward 2 months `October`
2) Press "Today", you'll be at `August`, control will close
3) Open control, press forward
4) You'll be at `November`. Expected result: `September`
This is because `otherMonth` is undefined when clicking "Today". Only if `otherMonth` is `true` will the model be set properly.
https://github.com/primefaces/primeng/blob/master/src/app/components/calendar/calendar.ts#L724-L732
Also removed createMonths line;
- Not required if `otherMonth` is `false`
- Called in `onDateSelect` when otherMonth is `true`
> Calendar - Specify otherMonth when clicking "Today"

- src/app/components/chart/chart.ts
- src/app/showcase/components/chart/chartdemo.html
Chart.js allows (since version 2.5) per chart plugins but Primeng does no allow passign of this parameter. This PR adds input to chart component to allow passing of this parameter to underlying Chart.js object.
> Allow passing of per-chart plugins

- src/app/components/carousel/carousel.ts
We discovered that the carousel component is not working when you get the data asynchronously from a service (The previous and next buttons won't do anything).
This is caused by the property 'columns' which is set to NaN if you don't supply data at the components' creation time. Assigning a default value of 0 fixes this issue.
> Fix carousel when data is loaded async

- src/app/components/table/table.ts
The related issue is at https://github.com/primefaces/primeng/issues/6634
> Make TurboTable not slice rows list if lazy loaded (fix #6634)

- src/app/showcase/components/multiselect/multiselectdemo.html
This just adds a missing `,` in the example code for MutliSelect.
> Simple typo: added missing ,

- src/app/showcase/components/multiselect/multiselectdemo.html
Fixed Issue [#6809 - Documentation typo on MultiSelect](https://github.com/primefaces/primeng/issues/6809)
Corrected property name from _styleClass_ to _panelStyleClass_.
> fixed #6809 - Documentation typo on MultiSelect

- src/app/components/table/table.ts
The currently rejected PR had a very large and complex fix. I have created a much simpler one that also works, by removing it from the ngAfterViewInit() and moving it straight to the attributes, which makes changes in the width trigger a re-render.
> Make frozen width work dynamically

- src/app/components/contextmenu/contextmenu.ts
Prevents contextmenu sub menu from going off screen if it's longer than the base menu.
See issue: [https://github.com/primefaces/primeng/issues/3261](https://github.com/primefaces/primeng/issues/3261).
> Fixed #3261 - prevent contextmenu sub menu going out of view

- src/app/components/picklist/picklist.ts
This is a small feature request, which is hereby also immediately implemented. Due to a need for server-side filtering when using the Prime picklist, I have added event emitters when the text in the text boxes has changed. There are many use cases for these emitters, of which the server-side filtering is only one. Another use case would be to observe the values in the filters to bind another element in the view to it, e.g. to show a message when no items are found, etc. 
Having these event emitters available, I was able to perform server-side filtering in a list of thousands of users, and then select relevant users quickly. Sending all users to the client and using the prime pick list as it was caused huge problems with performance.
> Add onFilter events for picklist

- src/app/components/common/menuitem.ts
- src/app/components/tabmenu/tabmenu.css
- src/app/components/tabmenu/tabmenu.ts
- src/app/showcase/components/tabmenu/tabmenudemo.html
Adds a 'closable' feature to the TabMenu API by exposing an input to display the 'close' icon, along with exposing an 'onTabCloseClick' output to allow developers to react to closures. Should fix #3018 if implemented.
Rather than mutating the list of MenuItems, I opted to simply expose an output that would allow developers to determine what kind of "closing" needs they may have. I'd be open to suggestions if this isn't too big of a feature for a non-employee to implement.
> Adds 'Closable' Feature to TabMenu

- src/app/showcase/components/dataview/dataviewdemo.html
This patch simply adds two missing brackets in the docs for DataView.
> Add missing brackets in DataView docs

- src/app/components/fileupload/fileupload.ts
- src/app/showcase/components/fileupload/fileuploaddemo.html
Changed the XHR request to now use the HookpClient of the Angular, so that it is possible to use the interceptors. The onBeforeUpload, onBeforeSend, onUpload and onError events were also changed, in the first 3 events the XHR object was removed, and in the 4 event the request error was added.
> Use HTTPClient in FileUpload #4945

- src/app/components/menubar/menubar.ts
Menubar now doesnt close on mouseenter if autodisplay is set to false and will remain open until focus is taken elsewhere, as expected. Also the menu will reopen with 1 click, as opposed to 2 as brought up in #7084.
Fixes #6657 and fixes #7084
> Fixed #6657 and #7084 - mouseenter closes menubar with autodisplay false

- src/app/components/spinner/spinner.ts
Fix bug ticket https://github.com/primefaces/primeng/issues/6798 where spinner with min value on blur automatically set the value to min.
> Fix bug where spinner with min value on blur automatically set the value to min

- src/app/components/table/table-editing.spec.ts
- src/app/components/table/table.ts
- src/app/showcase/components/table/tabledemo.html
When opening a table cell for editing inside a TurboTable, `input` and `textarea` elements are automatically focused. This allows for quick navigation between cells using the Tab and Shift+Tab keys. There is currently no focus support for `select`, `button`, or any custom edit control. This prevents keyboard navigation from working as expected when using other element types.
Since `input` and `textarea` are supported automatically, I think it makes sense for `select` to also focus by default. This will improve the user experience for a common use case. Additionally, I recommend providing a simple parameter for overriding the selector that is used to focus the cell the user is editing. I suggest `pFocusCellSelector` on the `pEditableColumn` directive.
There are currently no unit tests …
> eyboard Navigation Support for Custom Edit Controls

- src/app/components/dom/domhandler.ts
- src/app/components/overlaypanel/overlaypanel.css
- src/app/components/overlaypanel/overlaypanel.ts
- src/app/showcase/components/overlaypanel/overlaypaneldemo.html
This PR fixes #7218 and #7220.
The problem was that OverlayPanels on the right side of the screen are automatically shifted to the left side by the DomHandler so that they are not cut off on their right side. This however causes the little triangle on the left side of the panel to point to an empty space or a different element, instead of pointing to the target element. This can be pretty confusing for the user. So in this case, the little triangle should be shifted to the right side. This PR contains three very simple commits:
1. Fix the actual issue by shifting the little triangle to the right if the element is shifted left.
2. Make the demo page show the effect and fix a small issue with the demo.
3. Fix the additional problem that in the case that the panel is wider than the viewport, …
> Fix issue #7128 regarding shifted overlays

- src/app/components/autocomplete/autocomplete.ts
It turns out the overlay can disappear before the callback fires.
> fix #6259: check if overlay still exists

- src/app/showcase/components/editor/editordemo.html
Example in documentation for custom header was using old Quill template (v0.2.0).
Copied the markup from Source tab.
Incorrect documentation in Editor Demo #7503
> Update editordemo documention for custom header

- src/app/components/autocomplete/autocomplete.ts
This issue similar to #6259 and fixes in #7182.
but i found that sometime overlay not exists in highlightOptionChanged too. it error like 
`Cannot read property 'querySelector' of null`
> check if overlay still exists

- src/app/components/confirmdialog/confirmdialog.ts
This defect is similar to https://github.com/primefaces/primeng/issues/7123 but for confirmDialog.
> closeOnEscape property not working on p-confirmDialog

- src/app/components/multiselect/multiselect.ts
Set the visible selected items label to `selectedItemsLabel` parameter in case no occurrences of pattern are found in the selectedItemsLabel string passed by user.
#7324
> Fixed #7324 Text selectedItemsLabel Multiselect

- src/app/components/common/confirmation.ts
I have included this line of code in my app.component.ts (root). So, i can use confirm dialog in all child components:
`<p-confirmDialog message="Are you sure you want to perform this operation?" header="Confirm"></p-confirmDialog>`
As you can see, i have specified message and header inputs because i want to use them as default values.
But i can not create confirm dialog without specifying 'message' property, because it is required.
So i have to create dialog like this way every time when i want to use default message:
```
this.confirmationService.confirm({
message: null,
accept: onAcceptCallback
});
```
Doing it every time i use confirm dialog is annoying.
This looks much better:
```
this.confirmationService.confirm({
accept: onAcceptCallback
});
```
> Possibility to use default message

- src/app/components/fileupload/fileupload.css
The icon in the "Choose" button of the advanced fileupload button is
positioned absolute and is defined after the <input type="file">
element, which is also position=absolute.
So when a click is done in the region of the icon, the event is not
recorded on the file upload element, but on the icon and thus swallowed.
The solution is to raise the file element over the other elements via
a z-index style. This is considered to be save, as the button creates
a new stacking context.
The referenced issue was created independend of my analysis, but we
reached the same conclusion.
A sample project demostrating the problem can be found here:
https://github.com/matthiasblaesing/primengupload-icon-insensitive
> #7149 Clicking icon in advanced fileupload button does not open filechooser

- src/app/components/menubar/menubar.ts
Fixed menubar with auto display false where clicking an item would not properly reset the state of the menubar.
Fixes #7600
> Fixed #7600 - menubar clicks would not properly reset state of menubar when autodisplay false

- src/app/components/calendar/calendar.ts
This PR fixes problems which are described in #6937 issue. 
Currently it's impossible to manually edit input value for p-calendar component in case of "range" mode.
> fixed #6937 user input when calendar in rage mode

- src/app/components/multiselect/multiselect.css
- src/app/components/multiselect/multiselect.spec.ts
- src/app/components/multiselect/multiselect.ts
- src/app/showcase/components/multiselect/multiselectdemo.html
When filter in p-multiselect returns 0 results there are no empty filter message, on the other hand p-dropdown has this functionality. So in this PR I've added filter no results message support similar to what p-dropdown has.
> Add empty filter message property support for multiselect

- src/app/components/multiselect/multiselect.spec.ts
- src/app/components/multiselect/multiselect.ts
Filter in p-multiselect is not applied automatically when you update options input property, firstly this brings some inconsistency with p-dropdown where it's applied in that way, secondly filter in p-multiselect persists by default which is why most probably consumer will update an options input array during that time especially if getter is used to map an array.
Please take a look on this example on stackblitz:
https://stackblitz.com/edit/angular-7-master-qg8xbb?file=src%2Fapp%2Fexample.component.ts
The solution is to apply filter, if it is set, on every options property update (as it's done in p-dropdown).
> Add filter autoapply for multiselect on options update

- src/app/components/chart/chart.ts
- src/app/components/editor/editor.ts
When importing primeng/chart, the chart component fails with error: `chart_js_1.default is not a constructor`
This was caused by commit 8fddfcba75702adf60c23342448fb80961ab1a78
> Fix chart.js and quill library imports

- src/app/components/inputtext/inputtext.css
Closes #6957
See #6957 - the floating label does not work in Firefox.  This applies the same style that is applied to input to textarea.
> Fix textarea floating label in Firefox

- src/app/showcase/components/inputswitch/inputswitchdemo.html
Missing closing tag in documentation  for input switch
> Fix closing tag for input switch

- src/app/components/accordion/accordion.ts
> fixed #8044 AccordionTab throwing ViewDestroyedError during unit testing

- src/app/components/table/table.css
> Fixed #6757 TurboTable responsive with colgroup breaks column width

- src/app/showcase/components/codehighlighter/codehighlighterdemo.html
When you use this component and you are not using any of the default languages ( markup, css, clike and javascript) none of the code will be highlighted. In order to highlight the code an import is needed, likely in the app module for most. It will save others a lot of time if we flag this in the documentation.
> Update demo to include importing languages

- src/app/components/treetable/treetable.ts
Fix error when user uses Tab key to move between treetable cells.
> fix(treetable): Fix error when moving between cells

- src/app/showcase/components/carousel/carouseldemo.html
Defect fix - "View on Github" link in carousel document is pointed to buttons module
https://github.com/primefaces/primeng/issues/8254
> Updated "View on Github" link in carousel doc

- src/app/components/menubar/menubar.ts
- src/app/showcase/components/menubar/menubardemo.html
> MenuBar Behaviour Fixed

- src/app/components/paginator/paginator.ts
When totalRecords is 0 not yet set, then don't try to correct the page. This is a solution for issue #8358.
> Don't decrease page when totalRecords is not (yet) set (fix #8358)

- src/app/components/colorpicker/colorpicker.ts
#8334 colorPicker - wrong color rendered
**Issue**
Due to irrationnal numbers manipulation, method HSBtoRGB in ColorPicker component is not accurate as expected.
**Fix**
- Avoid Math.round in h,s,v values initialization.
- Use type number instead of var to have an accurate value needed in the process.
> Fix HSBtoRGB from ColorPicker component

- src/app/showcase/components/table/tablestatedemo.html
The [TableStateDemo](https://www.primefaces.org/primeng/#/table/state) shows how the current table page is restored when reloading the page. However, it does not show how the current table page size is restored as well. This PR adds a rowsPerPageOptions attribute so that we have a test/demo for this funtionality, which was broken until recently (see #8356).
> Add rowsPerPageOptions to TableStateDemo

- src/app/components/inputmask/inputmask.ts
[#8032 InputMask always setting class ui-inputwrapper-focus](https://github.com/primefaces/primeng/issues/8032)
> InputMask - updated host binding for ui-inputwrapper-focus

- src/app/components/multiselect/multiselect.ts
Updated updateFilledState method to check for a non-empty value, instead of checking the label.
Since there is always a label (unless you add defaultLabel="") this was always returning true.
#8279 
> Fix multiselect filled state

- src/app/components/multiselect/multiselect.ts
`allSelected` field is changed to `isAllChecked()` method call because of error below:
https://github.com/primefaces/primeng/issues/8486
> refactor allSelected -> isAllChecked()

- src/app/components/carousel/carousel.ts
Fix #8498 Carousel - Invalid Array Length error
Fix 6909edbb1f0d663f23d053e3ed1af7650ae49502
Current:
Just a case match if array length is 0 but not on negative numbers.
Fixed:
Now matches if array length is 0 or lower.
Edit:
This pr does not fix all problems of carousel if provided data contains less items 
than carousel should show.
> Fix #8498 Carousel - Invalid Array Length error

- src/app/components/carousel/carousel.ts
use runtime calculation isCircular() instead of initial variable circular
Fix  #8500
> Carousel: fix enabled navigation if not enough items on circular #8500

- src/app/components/dynamicdialog/dynamicdialog.ts
- Wrap close button with div with ui-dialog-titlebar-icons class
to have the same layout as the normal dialog
- Simplify ngIf expression for close button
Fixes #8587
> Fixed #8587 DynamicDialog close button alignment is broken

- src/app/components/confirmdialog/confirmdialog.ts
- src/app/components/dialog/dialog.ts
fix https://github.com/primefaces/primeng/issues/8573
as per intention of https://github.com/primefaces/primeng/issues/8475 
rewrite of dialogs in primeng should comply the way of primereact
and in primereact, Dialog append the wrapper to body, not the container:
https://github.com/primefaces/primereact/blob/95f5dc3dcc500080f05a4cc93ead44b0f4dfbff0/src/components/dialog/Dialog.js#L378
> Fix #8573: dialog covered by mask

- src/app/components/fileupload/fileupload.ts
It's displayed wrong.
For example 5MB are 5242880 and not 5000000
Setting it as [maxFileSize]="5242880" the validation is correct but the message says that the limit is:
5.242880 MB
> FileUpload size formatting is incorrect

- src/app/showcase/components/table/tableselectiondemo.html
###Documentation Fix
Here I have removed a piece of code,
As [pSelectableRow]="rowData" and p-tableCheckBox together conflict each other and both row and checkbox gets selected when clicked on a checkbox!
Note: It is not a defect nor a feature request.
> fix: corrected docs for p-table checkbox selection

- src/app/components/scrollpanel/scrollpanel.ts
This fixes https://github.com/primefaces/primeng/issues/8400
Bug: If ownHeight is less than 10% of totalHeight, the bar height is restricted to 10% but the css top for the bar does not take that into consideration which makes the bars go out of the container box.
Fix: Consider bar height when calculating its top.
> Fix positions of the scroll bars

- src/app/components/toast/toast.ts
This allows users to decide which direction that they want the toast to appear from. The default is translateY(100%) for show  and translate(100%) for hide as before. For example, if user wants to specify slide in from left, showTranslateOptions="translateX(100%)" can be added.
Issue: https://github.com/primefaces/primeng/issues/8136
> Added showTranslateOptions to p-toast

- src/app/components/api/confirmationservice.ts
- src/app/components/confirmdialog/confirmdialog.ts
Implementation to close ConfirmDialog via ConfirmationService.
Needed for closing the confirmationbox while browser-based navigation events.
Otherwise popup stays opened.
> ConfirmDialog close via service feature

- src/app/components/tooltip/tooltip.ts
In very rare cases it is possible that a new tooltip is created without destroying the old one.
This PR ensures that the old is destroyed before creating a new one.
fixes #8516
> Fix #8516 Tooltip - on create ensure that old tooltip is removed

- src/app/components/treetable/treetable.ts
TreeTables were only sorting the root level of children, and not all levels in the data.
Can be reproduced in example (https://www.primefaces.org/primeng/#/treetable/sort) by sorting first by 'Name', and then ctrl+clicking on 'Size'. If you continue to ctrl+click on 'Size', you can see only the ordering of Documents/Documents(folder) changes, when you'd expect the note-meetings.txt and note-todo.txt records to change order as well.
Resolves opened opened issue [#8530 ](https://github.com/primefaces/primeng/issues/8530)
> Fix: TreeTable multi-sort functionality

- src/app/components/dialog/dialog.ts
Until container position has been changed (by dragging), container maintains centering on resize due to flexbox parent, causing it to resize in each direction equally, thus doubling size increase (as the right side is being resized, the left side also expands, maintaining centering). Therefore we add a second deltaX and deltaY distance, accounting for the other side.
Once container position has been changed, resize behavior changes and resizing causes only one side to resize. 
Because dragging causes the container to add css style "top" and "left", we can assess whether centered resizing behavior is active, storing it in "hasBeenDragged".
Behavior can be demoed here
https://stackblitz.com/github/qgnirxral
or naturally, here
https://www.primefaces.org/primeng/showcase/
> dialog resize not scaling when centered

- src/app/showcase/components/table/tabledemo.html
In the table demo, updated `pEditableRowIndex` to the property `pEditableColumnRowIndex` as it is the input property on the EditableColumn directive.
https://github.com/primefaces/primeng/blob/6f1c6c30a67b78c2b5979a0656a917fb7be3a494/src/app/components/table/table.ts#L3110
https://github.com/primefaces/primeng/issues/8972
> Fixed #8972 incorrect property pEditableRowIndex

- src/app/components/inputmask/inputmask.ts
By default @ViewChild is set to static: false, which means that corresponding value is set only after ngAfterViewInit. Setting @ViewChild('input') to static: false in inputMask makes it miss writeValue call from FormGroup, because it happens before ngAfterViewInit and this.inputViewChild is still undefined at the time of call.
You might want to review the rest of the [9908406e1e8078ccc433d152c0dae25c627be43e](https://github.com/primefaces/primeng/commit/9908406e1e8078ccc433d152c0dae25c627be43e) commit (specifically removing static: true option) to make sure that nothing else is broken.
#8727
> Fix for #8727

- src/app/showcase/components/table/tabledemo.html
`closeCellEdit` is no longer a public method on the table component.
Possible solution to https://github.com/primefaces/primeng/issues/8974 .  If there is no immediate intent to restore the `closeCellEdit` method to the table component, this fix would remove the confusion in the documentation.
> Remove deprecated method from table docs

- src/app/components/autocomplete/autocomplete.ts
- src/app/components/calendar/calendar.ts
- src/app/components/colorpicker/colorpicker.ts
- src/app/components/confirmdialog/confirmdialog.ts
- src/app/components/contextmenu/contextmenu.ts
- src/app/components/dialog/dialog.ts
- src/app/components/dropdown/dropdown.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
- src/app/components/focustrap/focustrap.ts
- src/app/components/inputmask/inputmask.ts
- src/app/components/lightbox/lightbox.ts
- src/app/components/menu/menu.ts
- src/app/components/multiselect/multiselect.ts
- src/app/components/overlaypanel/overlaypanel.ts
- src/app/components/sidebar/sidebar.ts
- src/app/components/slidemenu/slidemenu.ts
- src/app/components/slider/slider.ts
- src/app/components/tieredmenu/tieredmenu.ts
Fixes #9181 
Allows focus checks to work correctly regardless of which document object is hosting the element.
> Use el.ownerDocument.activeElement to check for focus where possible.

- src/app/components/tristatecheckbox/tristatecheckbox.ts
Fixes the behavior described in #9085 - now no keyboard pops up on mobile devices, when clicking on a TriStateCheckbox.
The used tag is well defined: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode
> inputmode="none", so no keyboard pops up on mobile devices

- src/app/showcase/components/setup/setup.component.html
Documentation Fix
Code example shows `.../themes/saga-blue/theme.css` in use, but the documentation has "Nova Light" instead.
This update fixes the text to also be: Saga Blue.
> Doc. fix for the expected theme

- src/app/components/table/table.ts
For #8046  - Table cell editor not switching correctly from input to output with OnPush
> #8046 Table cell editor not switching correctly with OnPush

- src/app/components/dynamicdialog/dialogservice.ts
Fixes bug when opening multiple dynamic dialogs from a single service and then trying to close them.
Multiple dynamic dialogs would not close at all, only the last opened dynamic dialog would close properly.
With this fix all opened dynamic dialogs now close properly.
> Fixed #8801 - Multiple DynamicDialogs are not closing programmatically

- src/app/components/radiobutton/radiobutton.ts
#9162 
Fix radiobutton for template-driven forms. Cause of the problem: writeValue is not called on controls other than control that is changed by user. If there are 3 radio buttons and user clicks on the first one, 2nd and 3rd controls will not receive updated value through writeValue call. It'is not really a bug, but rather made on purpose by angular team. To work around the problem we need a singleton service that will keep registry of all buttons in all groups. When user changes value of one of the button, corresponding control propagates this changes to all sibling buttons in the same form through registry.
The solution and code is borrowed from angular's RadioControlValueAccessor (https://github.com/angular/angular/blob/c0523fc3b45cdb5ba52109f7ae0e4dab555b7d72/package …
> Fixed radiobutton with template-driven forms #9162

- src/app/showcase/components/radiobutton/radiobuttondemo.html
In stackblitz dynamic radio example clicking on label was not working. Fixed the variable name and make it as attribute
https://github.com/primefaces/primeng/issues/9417
> Fixed #9417 - Label clicking in dynamic radio

- src/app/components/confirmdialog/confirmdialog.ts
- src/app/showcase/components/confirmdialog/confirmdialogdemo.html
Added accessibility label support for accept and reject button on the confirmation dialog.
The element documentation has also been updated.
> Fixed #8947 - Accessibility: Dialog close button needs aria- label

- src/app/components/overlaypanel/overlaypanel.css
Re-added CSS for p-overlaypanel-shifted class so that the arrow points to the correct location when the panel is up against the right edge of the screen. This CSS was (unintentionally?) removed in commit: https://github.com/primefaces/primeng/commit/c7dd064da6e05d549a1a91f33ac3a9b5aa5dd267#diff-4166dfa8da6660ec4e195e891b761a9ce8f5e49db19ace3613ac9d66ad8e4f94L56 
Note this CSS was also removed (ui should be renamed to p):
```
.ui-overlaypanel-shifted:after {
margin-right: -8px;
}
.ui-overlaypanel:before {
margin-right: -10px;
}
```
But I chose not to add it back, because with it, the arrow overlaps the close button slightly. Without it though, the arrow is offset from the edge on the right side of the panel slightly more than it is when it appears on the left. Perhaps this could be made …
> Issue #9441: Re-add CSS for p-overlaypanel-shifted

- src/app/showcase/components/inputtext/inputtextdemo.html
Fixed: InputText documentation wrong usage for i element  [#9614](https://github.com/primefaces/primeng/issues/9614)
> Fixed #9614 InputText documentation wrong usage for i element

- src/app/showcase/components/inputtext/inputtextdemo.html
This PR makes a small improvement to the showcase for InputText:
> docs(showcase): fix formatting typo in showcase for InputText

- src/app/components/editor/editor.spec.ts
- src/app/components/editor/editor.ts
Issue is [here](https://github.com/primefaces/primeng/issues/9664)
When I tried to run the editor, there were compile errors for the cascadeselect.ts file. I did a quickfix locally to remove those errors and test my own changes, but didn't push them here, since I wasn't a 100% sure of the quickfix was also correct.
> Fixed #9664 - fix so that editor doesnt automatically autofocus

- src/app/components/confirmdialog/confirmdialog.ts
Checks if the ChangeDetectorRef instance "destroyed" the flag before the call to avoid the exception (EXCEPTION: attempt to use a destroyed view: detectChanges).
Resolves the issue related in #8661 and #8585
> Fixed #8585 - ConfirmDialog throws exception during onDestroy

- src/app/showcase/components/splitter/splitterdemo.html
Showcase refers to the property for the initial size as 'sizes', which does not exist. Should be 'panelSize'.
Fixes #9807
> fixed #9807  - Splitter property for initial size should be called panelSize on the showcase

- src/app/components/avatar/avatar.css
Fixes: https://github.com/primefaces/primeng/issues/9895
> Fixed #9895 - Avatar-Images are overflowing circle-shaped parent-Div

- src/app/showcase/components/codehighlighter/codehighlighterdemo.html
- src/app/showcase/components/toast/toastdemo.html
The titles in the demo pages for [Toast](https://primefaces.org/primeng/showcase/#/toast) and [CodeHighlighter](https://primefaces.org/primeng/showcase/#/codehighlighter) do not show up properly any more, because the `feature-title` CSS class has been removed. This PR fixes this to use the semantic h1 tag like in the other demos.
Btw, it seems the menu entry for the CodeHighlighter demo is missing, so that this feature is kind of undocumented currently.
> Fix titles of Toast and CodeHighlighter demos

- src/app/components/tabmenu/tabmenu.ts
Template binding for MenuItem.styleClass is missing in TabMenu component
> Fixed #10044 - Menuitem style and styleClass should applied to the TabMenu

- src/app/components/carousel/carousel.ts
Assigning new reference to prevState.value when new item is added to value array
This fixes the bug https://github.com/primefaces/primeng/issues/10051
Carousel does not always display dynamically added items
> Fixed  #10051 - Carousel does not always display dynamically added items

- src/app/components/tristatecheckbox/tristatecheckbox.ts
- src/app/showcase/components/tristatecheckbox/tristatecheckboxdemo.html
Added icons in the tristatcheckbox. Two parameters were created to define the correct icons. 
- By default, strings (pi-check and pi-pi-times) remain.
> Fixed #10052 - Icon support for TriStateCheckBox

- src/app/components/tristatecheckbox/tristatecheckbox.ts
Fixes #10101 
Now the null state should be empty again as expected
> Fixed #10101 - TriStateCheckbox null state has false state icon 

- src/app/showcase/components/chip/chipdemo.html
Change removeIconClass to removeIcon, because the showcase page does not fit with the actual implementation.
> Change removeIconClass to removeIcon. 

- src/app/components/inputnumber/inputnumber.spec.ts
- src/app/components/inputnumber/inputnumber.ts
- src/app/showcase/components/inputnumber/inputnumberdemo.html
- Defaults to false
- Does not display buttons when readonly is set
- Updates the showcase documentation
- Adds tests for p-inputNumber default displayability as done in other inputs
- Adds tests for readonly rules
- closes #9827
> Adds readonly attribute to p-inputNumber

- src/app/showcase/components/table/tabledemo.html
Fixes #10756   according to the corrections and updates I saw worth changing.
Several spelling changes, and grammar changes (updating sentence structure). Also a few additions of `<i>`s to note properties and directives
> Fix #10756 - spelling and grammar updates in Table Docs

- src/app/components/dynamicdialog/dynamicdialog.ts
#10882 
Class `p-component-overlay` was missing.
> Fixed #10882 - DynamicDialog does not block interaction with elements behind the mask

- src/app/components/dialog/dialog.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
Proposed Fix for: https://github.com/primefaces/primeng/issues/10909
> Fixed #10909 - TypeError: Cannot read properties of undefined (reading 'classList') at Function.addClass

- src/app/components/calendar/calendar.ts
Calendar's firstDayOfWeek's getter returns the number of months since 13.0.4.
Introduced by 9c6682c7e17ea7238b015a9419da8de08ba2e231, related to #9635.
> Fixes #11070 - Regression on Calendar's firstDayOfWeek getter

- src/app/components/multiselect/multiselect.ts
This fixes the overlay bug from issue #11191
> Fixed #11191 - Multiselect overlay bug - baseZIndex property is unused

- src/app/components/colorpicker/colorpicker.ts
Fixes a bug in Primeng `colorPicker` when will try open manually by `ViewChild` ref.
Fixes #11438.
> Fixed #11438 - p-colorPicker onInputClick using a button not working

- src/app/components/tieredmenu/tieredmenu.ts
Process the keyboard `enter` event for a menu item if it is not `routerLink'.
Fixes #11514.
> TieredMenu | Fix keyboard enter event

- src/app/components/confirmdialog/confirmdialog.ts
fixes https://github.com/primefaces/primeng/issues/11523
Remove the moveOnTop from mousedown because it if it's there it keeps
raising the z-index of the modals in the application. It was removed
from dialog already in https://github.com/primefaces/primeng/issues/6857
> fix(primeng/confirmDialog): remove moveOnTop call from confirmdialog mousedown

- src/app/components/contextmenu/contextmenu.ts
> fix(primeng/contextmenu): reset the status of the active item when the cursor is placed over the disabled item

- src/app/showcase/components/chart/chartdemo.html
When you add this line to your angular.json-file, you get a "An unhandled exception occurred: Script file ./node_modules/chart.js/dist/Chart.js does not exist." error while building on linux systems.
https://github.com/primefaces/primeng/issues/11554
> Fixed typo in charts.js-documentation

- src/app/components/tabview/tabview.ts
- src/app/showcase/components/tabview/tabviewdemo.ts
> fix(primeng/p-tabview): error on adding an item to an empty tab panel

- src/app/components/fileupload/fileupload.ts
Fixes #11799.
The error message did not disappear correctly when removing file(s), to match your file limit.
> Fixed #11799 - FileUpload | The error message does not disappear correctly when removing file(s), to match your file limit.

- src/app/showcase/components/autocomplete/autocompletedemo.html
The default `emptyMessage` was incorrect.
> fix: Fixed autocomplete empty message in the documentation

- src/app/components/galleria/galleria.ts
This PR introduces using a getter for the `GalleriaItem.activeItem` to prevent the case where the `value` array has been changed, but the reference is still pointing to the previous value. This occurs because the `activeItem` reference is only changed whenever the `activeIndex` is set. 
Fixes #11882
> GalleriaItem activeItem getter to avoid stale references

- src/app/components/table/table.ts
- src/app/components/treetable/treetable.ts
Currently, an exception occurs if an empty multiSortMeta array is passed. However, there are use cases where the sort criteria are set after rendering. Therefore, it should be possible to pass an empty multiSortMeta array and change it during the lifecycle.
This PR fix issue #11868.
> Table: Catch exception if multiSortMeta array is empty

- src/app/components/cascadeselect/cascadeselect.ts
All form components are affected by `p-inputtext-lg` css class and become larger except the `cascadeSelect`. Based on css styles, I add a `p-inputtext` class to `cascadeSelect` component.
> add p-inputtext class to cascadeSelect component

- src/app/components/listbox/listbox.ts
Fixed binding of "aria-multiselectable" for "ul.p-listbox-list" to use evaluated boolean value instead of string containing variable name.
#11743
> Listbox: Fixed aria-multiselectable attribute binding. Fixes #11743

- src/app/components/inputnumber/inputnumber.ts
Allow the `Enter` key press event to bubble up from InputNumber. This is more in line with the behavior of other controls (e.g. InputText). Also, this allows for submit form on `Enter` key press.
> Do not swallow Enter key press event

- src/app/components/dynamicdialog/dynamicdialog-config.ts
Add support for custom typing the `data` property of a `DynamicDialogConfig` with a generic.
#11665
> Generic data property of DynamicDialogConfig

- src/app/showcase/components/button/buttondemo.html
Example button component included the `p-button-text` class twice.
> fix: remove duplicate class in button example

- src/app/components/dropdown/dropdown.spec.ts
- src/app/components/dropdown/dropdown.ts
As many Angular developers provide empty string to an input's value it's good to have check on empty string too to avoid visual issues.
new FormControl('') would lead to filled getter to be true.
> #10964. Fix dropdown is filled when an empty text value is provided.

- src/app/components/package.json
Fixes #11172 
Added resources to package.json exports field according to Angular docs about managing assets https://angular.io/guide/creating-libraries#managing-assets-in-a-library
> fix: added resources to package exports

- src/app/components/accordion/accordion.css
Issue #11848 was fixed in 4.1.0 but was reintroduced in 4.1.1+ after PR #11935 (see https://stackblitz.com/edit/angular-ivy-q8x2la?file=package.json). This PR should now fix #11848 again while also making sure #11924 (which PR #11935 aimed to fix) is not reintroduced.
The active accordion tab should only affect the styling of the .p-toggleable-content for the direct children and not of any sub-accordions, which is what this css change fixes.
> Fix issue 11848 - Accordion Panel within an Accordion Panel is broken

- src/app/components/contextmenu/contextmenu.ts
> Fix primefaces#12011: align contextmenu properly when body is scrolled

- src/app/showcase/components/toast/toastdemo.html
I fixed a small error in the documentation / showcase of the toast component.
I got the correct classes from the [actual component](https://github.com/primefaces/primeng/blob/master/src/app/components/toast/toast.ts#L51)
I didn't open an issue first for this, because it seems like a very small documentation error, but I can create and link one if necessary.
> Fixed wrong style classes in showcase of toast component

- src/app/showcase/components/inputtextarea/inputtextareademo.html
The documentation has autoResize as a string in the example, it should be a boolean
Issue #12239
> autoResize is a wrong type in docs

- src/app/components/carousel/carousel.ts
> fix(primeng/p-carousel): carousel wrong pagination, if data is loaded dynamically

- src/app/components/blockui/blockui.ts
[#12224](https://github.com/primefaces/primeng/issues/12254)
> fix(primeng/p-blockui): Check if mask exists before trying to interact with it when blockUi component is been destroyed

- src/app/components/editor/editor.ts
> fix(primeng/p-editor): change logic setValue when quill is not attached for DOM

- src/app/components/tabmenu/tabmenu.ts
- src/app/showcase/components/tabmenu/tabmenudemo.html
The tab menu currently does not let outside components know when the tab inside has changed. While it is possible to bind commands to the menu items, it could still be very useful to have the ability to react to a different tab being selected. The event emitter is named to support two way binding on the activeItem property.
Fixes #12310
> Add output to TabMenu on item selection

- src/app/components/ripple/ripple.ts
This will fix #9853
When using font-awesome pro this replaces the icon with a SVG and therefore `children[i]` becomes a SVGElement which means that `children[i].className` is a object which you cannot perform .indexOf on.
> allow Ripple class to handle icons being SVGs

- src/app/components/table/table.ts
fixes #11466
This PR adds all relevant properties to be able to fully customize the `ColumnFilter` **filter** template to the `ColumnFilterFormElement` **ngTemplateOutlet context**. 
Without this, it is for example _not even possible to recreate/customize_ the `#builtInElement` `ColumnFilterFormElement` template. 
**This adds no breaking change!**
The formatting style of the context is the same as https://github.com/primefaces/primeng/blob/v14.2.1/src/app/components/table/table.ts#L2502-L2513
> Add additional properties to the ColumnFilterFormElement ngTemplateOutlet context

- src/app/components/table/table.ts
fixed #12436 
Current behavior
Does not have options to generate the whole data in generating CSV in filter time 
Expected behavior
giving the user options to export the whole entire data even if the table is filtered
- Angular version: 13.3
- PrimeNG version: 13.4.1
> generateCsv option to generate the whole entire data

- src/app/components/menubar/menubar.ts
> feature(primeng/p-menubar): add customizable autoHide timeout

- src/app/components/multiselect/multiselect.ts
- src/app/showcase/components/multiselect/multiselectdemo.html
- src/app/showcase/components/multiselect/multiselectdemo.ts
Fixes #12460 
- onRemove event emitter added.
> Fixed #12460 - MultiSelect: Add event onRemove

- src/app/components/toolbar/toolbar.ts
#12494 by @carcigenicate
Correcting the typo in the source code from `rightTemplate` to `endTemplate`
> Correcting the template name typo

- src/app/components/tooltip/tooltip.ts
- This change was implemented to help tooltips comply with (WCAG Success Criterion 1.4.13)[https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html]
- It adds a flag to tooltip options that simply allow the user to close the tooltip when pressing Escape (using a HostListener)
- The relevant issue is available [here](https://github.com/primefaces/primeng/issues/12603)
> Added basic option to close tooltips with Escape

- src/app/components/table/table.ts
> fix(primeng/p-table): `onEditComplete` event data

- src/app/showcase/doc/icons/constantsdoc.ts
fixes #12785 
- 🐛 Move typescript block first so that it is the one that is displayed by default.
> Fixed #12785: Icon constants code block not accurate on new docs

- src/app/components/inputnumber/inputnumber.ts
- src/app/showcase/doc/inputnumber/propsdoc.ts
Fixes #12915 
- add updateOn input property
> Fixed #12915 - p-inputNumber | ngModelOptions is not taken into account

- src/app/components/tabmenu/tabmenu.ts
Fix for #12744 
Marking for change detection after all values are updated and the command is run should fix this.
> Fixed #12744 - Adding change detection in TabMenu

- src/app/components/table/table.ts
Fixes #12493
Fixes #10003
Apparently the `rowY` value was being offset by the window scroll twice:
Which wouldn't allow the condition `pageY < rowMidY` to be `true`, so no bottom slots would work after a certain scroll amount.
Both sections trace back to the [same commit](https://github.com/primefaces/primeng/commit/94e7c5b3fdf816e3cd4f20afcf36467adb15a6bc).
However, no other occurrence of `getOffset` on the project required an extra `getWindowScrollTop`:
There were no tests related to this to be updated, but manual tests on the `showcase` indicate the fix works.
> Fix Issue 12493: Last slot of reorderable table breaks when page is scrolled

- src/app/components/table/table.ts
Fixes https://github.com/primefaces/primeng/issues/12903
I have implemented that the clear function does now iterates over all filter keys and clears them
> Fix clear function not resetting all filters

- src/app/components/scroller/scroller.ts
When attempting to retrieve the height and width of our content to calculate the num items, it would sometimes return NaN when the computation failed.
To resolve this issue, I added a check to return 0 whenever the result of the computation was invalid number.
> Autocomplete: Issue with Virtual Scroll #12568

- src/app/components/table/table.ts
Fixes #12880
The scroller is initialized in the template when `virtualScroll = true`. However, during the initial load, when filters are set and the filter method is called, the scroll moves to the initial position. At the moment, the scroller is not yet created. 
In this line, checking for `scroller != undefined` is equivalent to checking for `virtualScroll != undefined`.
> fix(primeng/p-table): the scroller is on initial load undefined when filters are set

- src/app/components/fileupload/fileupload.ts
> Fix #13129 - FileUpload | File limit does not fire error

- src/app/components/autocomplete/autocomplete.ts
This fixes a problem with validation grouped options. AutoComplete.onInputChange now also looks at grouped options when deciding on validity of the selected option.
This fixes https://github.com/primefaces/primeng/issues/12624
> Take into account that options can be grouped when validating input.

- src/app/components/menu/menu.ts
The SafeHtmlPipe class was not exported, which made it impossible to use it in other components. Exporting the class makes it available for use in other components.
https://github.com/primefaces/primeng/issues/13218
> 🚀 chore(menu.ts): export SafeHtmlPipe class to be able to use it

- src/app/components/table/table.ts
The import path for FilterSlashIcon was incorrect and has been fixed to 'primeng/icons/filterslash'.
File '/home/runner/work/primeng/primeng/src/app/components/icons/filterslash/filterslash.ngtypecheck.ts' is not under 'rootDir' '/home/runner/work/primeng/primeng/src/app/components/table'. 'rootDir' is expected to contain all source files.
> 🐛 fix(table.ts): fix import path for FilterSlashIcon

- src/app/components/dropdown/dropdown.spec.ts
- src/app/components/dropdown/dropdown.ts
addresses https://github.com/primefaces/primeng/issues/12637
test added to cover this issue, confirmed it fails prior to fix
there may be a remaining bug if the first group does not have any children but it is out of scope for what i wanted to resolve here
> resolves #12637 -- uses proper group children property in dropdown autoselect

- src/app/components/tooltip/tooltip.ts
- src/app/showcase/doc/apidoc/index.json
Fixed the issue: https://github.com/primefaces/primeng/issues/13238
- Following the same concept of `tooltipEvent`, I added `string` on `tooltipPosition` and the problem was solved.
- I updated the docs adding the default `right` to `tooltipPosition` and adding the new type `string` too.  
In `tooltipEvent` I added the type (before was indicated like `any`) and I following the same concept as `tooltipPosition` adding `"hover" | "focus" | string`
> [#13238] Fixed tooltip position and updated documentation

- src/app/components/inplace/inplace.ts
- src/app/showcase/doc/apidoc/index.json
Fix the issue: https://github.com/primefaces/primeng/issues/13277
I deleted the default value of  `preventClick` following the same concept in the others properties that doesn't have an init value (`style`, `styleClass`, `closeIcon`).
> Fix inplace close icon

- src/app/showcase/doc/avatar/avatargroupdoc.ts
- src/app/showcase/doc/avatar/importdoc.ts
- src/app/showcase/layout/doc/codeeditor/templates.ts
> [#13292] - added import AvatarGroupModule to docs

- src/app/components/image/image.ts
Fix #13305.
Added Hostlistener to close preview when the user press `ESC`.
> [#13305] - Fixed ESC button close preview on image Component

- src/app/components/button/button.ts
- src/app/showcase/doc/button/loadingdoc.ts
Fix [#13342 ](https://github.com/primefaces/primeng/issues/13342).
Fixed documentation for `<p-button>` examples, replacing `click` with `onClick`. Also, added comments in the Button API.
For example: If you use `<p-button>` with `(click)` with the property disabled, the click is triggered. And for that is better specify in the docs the correct use.
> Button Docs Update: <p-button> examples should use onClick instead of click

- src/app/components/orderlist/orderlist.ts
Fix #13322.
Fixed functions itemClick and isSelected. 
-  If **metaKeySelection** is set to **true**, the user can click on a row, and while holding down the meta key (e.g., Ctrl, Cmd, or Meta), they can continue clicking on other rows to select multiple rows simultaneously.
- If **metaKeySelection** is set to **false**, the user can only select one row at a time. Clicking on a new row will deselect the previously selected row.
(By default and adding **metaKeySelection="true"** or **metaKeySelection="false"** the behaviour was select multiple rows)
> [13322] - Fixed OrderList component (multiple selection and metakey)

- src/app/components/tieredmenu/tieredmenu.ts
Fix #13389 SplitButton menu options not working correctly in v16.1.0
Fix: The position was getting set as 'absolute' as the 'relativeAlign' was null.
https://www.youtube.com/watch?v=56PQLJgv9-s
> SplitButton menu options not working correctly in v16.1.0

- src/app/components/organizationchart/organizationchart.ts
Fix #13368
Changed the changeDetector to `Default`.
> [#13368] Fixed OrganizationChart is not refreshing

- src/app/components/tieredmenu/tieredmenu.ts
> [#13433] - Fixed double tap to open submenu in tieredmenu component

- src/app/components/inputtextarea/inputtextarea.spec.ts
This is a very quick fix for a broken test. I did not check whether this pattern is used in other tests because this is the only test that fails for me.
> fixed test failure "Expected '133px' to be greater than '37px'"

- src/app/components/button/button.css
- src/app/components/button/button.ts
Fix #13250
Fix #13345
Fix #13195 
All the details are in the screenshot gif. 
I'm not sure if it's the best solution, but it works. 
It was a little bit tricky to find a solution because when it was solved in `<p-button>,` it was broken in `<button pButton>` and vice versa.
> Fix Button Component: Loading and iconPosition

- src/app/components/tieredmenu/tieredmenu.ts
Fixes: https://github.com/primefaces/primeng/issues/13455
To fix the problem the `isDirty` flag needs to be set to `true` when the popup is shown or an item is clicked. 
This will ensure that `onItemChange(..)` is called when a `MenuItem` is hovered by the mouse, which will mark the `MenuItem` as active and therefore uncover the sub `MenuItem`s (children).
> Fixed #13455 - TieredMenu does not show sub menus when mouse is hovered over the parent menu item

- src/app/components/dynamicdialog/dynamicdialog.ts
Fix #13497
Changed the changeDetection to `onPush` solves the problem. I don't know if it's the best solution. If you have another, let me know.
Note: Ignore the warning message `responsive property is deprecated as table is always responsive with scrollable behavior.`
> Dynamic Dialog: Fixed errors when is opened

- src/app/components/sidebar/sidebar.ts
This commit addresses the issue where a `TypeError` was occurring due to an incorrect function name. The `onKeydown` function in the `Sidebar` component has been correctly renamed to `onKeyDown` to match its definition. This fix resolves the error and ensures the proper execution of the keyboard event handling in the component.
> 🐛 Fix: Resolves TypeError by renaming onKeyDown function to match its definition

- src/app/components/calendar/calendar.ts
When maxDate or minDate is used, particular date or month gets disabled but there is no way to disable years outside the range of max or min date.
Related issue id: #12151, #12583
> In primeng calendar, date can be lined through or disabled using date… there is no way to disable years

- src/app/components/dynamicdialog/dynamicdialog.ts
This PR is linked to issue #12720. This exists since the fix for #12319, as [autofocus] elements were no longer taken into account; only the first focusable element is considered now.
> autofocus by default dynamic dialog

- src/app/components/chips/chips.ts
- src/app/showcase/doc/apidoc/index.json
> fix(primeng/p-chips): docs and type of property `separator`

- src/app/components/panel/panel.css
Fixes #12713 
When one toggleable panel has another toggleable panel inside, expanding the outer panel SHOULD NOT set the content of the inner panel to be visible when it is collapsed.
#12713
> Fix issue 12713 - Toggleable Panel inside another toggleable panel

- src/app/showcase/doc/speeddial/accessibilitydoc.ts
- src/app/showcase/doc/speeddial/tooltipdoc.ts
- on hober => on hover
- actives => activates
> docs(primeng/p-speeddial): typos in tooltip and accessibility sections

- src/app/components/dynamicdialog/dynamicdialog.ts
I did this PR previously https://github.com/primefaces/primeng/pull/13502 and was merged but [MarcinBorowski95](https://github.com/MarcinBorowski95) recommend don't change the `changeDetectionStrategy` to `onPush` because It could bring some unforeseen consequences. I returned again to `Default`.
I did [MarcinBorowski95](https://github.com/MarcinBorowski95)'s  way and works good.
Also I think is better than my previous solution.
Thanks
> Refactor dynamic dialog: Errors when is opened #13497

- src/app/components/tieredmenu/tieredmenu.ts
> Fix #13522 - SplitButton [NG]: Menu is not closing when click on outside

- src/app/components/dropdown/dropdown.ts
When closing the dropdown overlay via 'Escape' key the event should also be default prevented to give parent elements a chance to detect that the event was already processed
Fixes #13463
> Dropdown escape key event default prevented

- src/app/components/calendar/calendar.spec.ts
- src/app/components/calendar/calendar.ts
- make sure `udateModel` is called in `onUserInput` with keepInvalid=true even though date is outside valid range.
Defect Fixes
Fixes #13132
> Fixed #13132 : Calendar: onModelChange not called with keepInvalid=true if user enters a well-formatted date but outside allowed range

- src/app/components/dialog/dialog.ts
Fixed an issue where dialogs with `breakpoints` set were unable to successfully be maximized using the maximize button when `[maximizable]="true"`.
#13268
> fix(dialog): maximizable responsive dialog

- src/app/components/dynamicdialog/dynamicdialog.ts
This is a fix on top of https://github.com/primefaces/primeng/pull/13502
@SoyDiego the github action for formatting was failing due to minor formatting issues: https://github.com/primefaces/primeng/actions/runs/5901308653
The test suite fails big-time locally, hopefully, is some misconfig on my side.
Lastly, not sure if I could/should bump the version to `16.2.1` to have this tagged and published in the registry.
Cheers
> DynamicDialog missing prettier

- src/app/components/table/table.ts
No issue reported but removing duplicated code in selectRange method.
> Remove duplicated code in selectRange method of Table component 

- src/app/components/inputtextarea/inputtextarea.ts
Fix #13484 
After extensive testing, I found that the 2 removed hostlisteners caused the problem. When removing them, I have not noticed that they affect anything else, except fixing the scrollup problem
> inputTextArea: Fixed on click, makes scroll up

- src/app/components/splitter/splitter.css
Fixes: https://github.com/primefaces/primeng/issues/13323
More info about flex-basis and min-width: https://stackoverflow.com/questions/49747825/flex-basis-behavior-not-as-expected-but-max-width-works
> Fix #13323 - Splitter: added min-width: 0 to nested panels

- src/app/components/selectbutton/selectbutton.ts
Fix #13553 I have refactored the access of optionValue.
> Modify refactor selectButton

- src/app/components/calendar/calendar.ts
- src/app/components/fileupload/fileupload.ts
Fix for Issue #13566 
The calendar changes are a result of running "npm run format"
> Fix fileUpload: choose button is disabled #13566

- src/app/components/dropdown/dropdown.ts
Addressing issue || #13560
After solution video for details and test result
[Video for details ](https://www.awesomescreenshot.com/video/20319610?key=85c4631d632aa11cfba66d782ebb670c)
Previously  we was checking ONLY 
``DomHandler.hasClass(event.target, 'p-dropdown-clear-icon')``
this case event  don't get all the time same element, some time it's also get path from svg element or others .
So I also check closest class has '.p-dropdown-clear-icon'
> fix: #13560 || DropDown clear or close icon on click dropDown option show

- src/app/components/calendar/calendar.ts
- src/app/components/inputnumber/inputnumber.ts
Fix for issue #13525 
If we want the option of treating 0 as falsy, maybe we can add another property for that option. As it exists, I think 0 should be treated as a value and the clear icon should show. 
SOLVED:
https://github.com/primefaces/primeng/assets/104391407/170c5ea7-84ae-4099-9c70-0063d51f9063
> Fix #13525 inputNumber not showing clear when 0

- src/app/components/dynamicdialog/dynamicdialog.ts
- src/app/components/picklist/picklist.ts
Fix #13513
Added `dragConfig` to assign a `zIndex` value. More info here: https://material.angular.io/cdk/drag-drop/api#DragRefConfig
I added `1200` because dynamic modal and others always init in `1100, 1101, 1102`.
If you consider another number, let me know and I will change.
Note: Also I formatted the file dynamicdialog.ts to pass the test.
> Picklist: Added dragConfig to assign zIndex

- src/app/components/overlaypanel/overlaypanel.ts
Fix #13462 
https://stackblitz.com/edit/ppug2d?file=src%2Fapp%2Fdemo%2Foverlay-panel-template-demo.html
(The .GIF doesn't help here, but I'm doing one click outside to close)
> OverlayPanel: Fixed does not hide after scrolling

- src/app/components/autocomplete/autocomplete.ts
Fix #13344
The problem was related to the dropdown click event triggering multiple requests when opening the country list.
> [#13344] - Fixed double call autocomplete component

- src/app/components/autocomplete/autocomplete.ts
Fix || #13572
I just add condition `!loader`to show close icon so close or clear icon will not show if is loading.
> fix: #13572 || AutoComplete showClear close icon overlap with loader icon

- src/app/components/autocomplete/autocomplete.ts
Fix: #13578 
Previously we check just two string that's why it was return not equal.
So know I am doing lowercase item and input value before check so both it ensure same case.
> fix: #13578 || Autocomplete Force Selection case sensitive issue

- src/app/components/tieredmenu/tieredmenu.ts
fixes for  #12945 (ReferenceError: Cannot access 'TieredMenu' before initialization)
Referring solution from #13429
> Fix jest test TieredMenu error

- src/app/components/inputnumber/inputnumber.ts
> Issue #13588 inputNumber maxlength ignored paste

- src/app/components/speeddial/speeddial.ts
Error in the console log when the SpeedDial is onBlur
```
Error: NG0600: Writing to signals is not allowed in a computed or an effect by default. Use allowSignalWrites in the CreateEffectOptions to enable this inside effects.
```
> fix: SpeedDial onBlur issue #13499

- src/app/components/menu/menu.ts
#13568
When all menu items are disabled, `links` is an empty array. When `this.focusedOptionIndex.set(links[order].getAttribute('id'));` is invoked, this caused a typeError of `Cannot read properties of undefined (reading 'getAttribute')` when a click occurs anywhere on the document.
This PR adds a short-circuit to prevent the invoking of `getAttribute` if there are no enabled menu items.
> Issues #13568/typeerror disabled menus

- src/app/components/image/image.ts
Issue Fixed:
#13611 p-image: preview image execute ngSubmit
I have a form
``` <form (ngSubmit)="onFormSubmit()">
<p-image [src]="imageURL" width="90" height="90" alt="image" [preview]="true"></p-image>
</form>
```
When I click to preview image, onFormSubmit method is executed it and It's wrong.
ngSubmit form must not be executed when I click on preview image.
<div class="p-image-preview-indicator"...>
was changed
<button class="p-image-preview-indicator" .... >
type="button" must be present
type="button" added to button
> p-image: preview image execute ngSubmit #13611 fixed

- src/app/showcase/doc/dynamicdialog/basicdoc.ts
According to the current documentation for Dynamic Dialogs, it is stated that entryComponents are required for dynamic dialogs. However, with Angular 9 and above, using the Ivy rendering engine, entryComponents are generally no longer necessary. This could lead to confusion for developers using newer versions of Angular.
Fix #13679
> docs: remove entryComponents from DynamicDialogs

- src/app/components/tieredmenu/tieredmenu.ts
This fixes issue #13582 
set the [autoDisplay] property equal to false to disable this feature.
> Issue #13582 TieredMenu not showing items on hover

- src/app/components/multiselect/multiselect.ts
fix: #13571 
The code for MultiSelect and Dropdown components closely resembles each other. However, I observed that the bug was occurring exclusively in the MultiSelect component. Upon comparing their respective code, I identified that a particular section of the MultiSelect code was never executed due to the constant state of the `filtered` variable being set to `false`. To address this issue, I introduced a code modification that ensures `filtered` is set to 'true' whenever the `onFilterInputChange` method is invoked.
```ts
onFilterInputChange(event: KeyboardEvent) {
this._filterValue = (<HTMLInputElement>event.target).value;
this.activateFilter();
this.filtered = true; // I add this line
this.onFilter.emit({ originalEvent: event, filter: this._filterValue });
this.cd.detectChanges(); …
```
> fix: #13571 | Multiselect not repositioned

- src/app/showcase/doc/blockui/importdoc.ts
- src/app/showcase/doc/dynamicdialog/basicdoc.ts
- src/app/showcase/doc/megamenu/basicdoc.ts
- src/app/showcase/doc/treetable/columnresizefitdoc.ts
- src/app/showcase/doc/treetable/columnresizescrollabledoc.ts
- src/app/showcase/layout/app.component.ts
- src/app/showcase/pages/megamenu/megamenudemo.ts
Removed wrong paragraph.
**Note:** I modified only `src\app\showcase\doc\blockui\importdoc.ts`. 
The rest of the files were formatted.
> BlockUI: Removed wrong paragraph in demo

- src/app/components/button/button.ts
> Fix button loading issue #13489

- src/app/components/confirmpopup/confirmpopup.ts
Fix #13652 
Now if you use `closeOnEscape: true` when you press `ESC` close the popup.
I added only the `hostlistener`. The rest of the code was formatted by Prettier.
> ConfirmPopup: Add hostListener to closeOnEscape

- src/app/components/autocomplete/autocomplete.css
- src/app/components/fileupload/fileupload.ts
- src/app/components/menu/menu.ts
- src/app/components/tieredmenu/tieredmenu.ts
Fix #13532 
I added only the line: `display: flex;`. The rest of files and lines was the `npm run format`.
> Autocomplete: Fixed alignment token icon

- src/app/showcase/doc/carousel/circulardoc.ts
Fix #13728
Changed `autoPlayInterval` to `autoplayInterval` in docs and now is animated again too.
> Carousel: Typo documentation autoPlayInterval

- src/app/components/utils/zindexutils.ts
Fix #13498 
Increased the zIndex position as propoused by [@dkhrunov](https://github.com/dkhrunov) in this issue: https://github.com/primefaces/primeng/issues/13498#issuecomment-1678490312
> Increased zIndex Position when Sidebar and Modals work together

- .eslintrc.json
- package-lock.json
- package.json
Fixes #13641
ESLint was not working because of few miss configurations, and it is fixed with this PR
PS: I see a lot of unused code and unused imports on code after this fix. Please consider merging this PR so that maintaining code will be easier. Also, we might have to consider a separate ESLint config for showcase folder as the prefix for those components are different from the actual library (app- vs p-)
BEFORE FIX
AFTER FIX
> Fix: Es Linter Issue 

- src/app/components/dynamicdialog/dialogservice.ts
- src/app/components/dynamicdialog/dynamicdialog-config.ts
- src/app/components/dynamicdialog/dynamicdialog-injector.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
Fix #13646
step_1: [ComponentFactoryResolver is DEPRECATED since v13]
step_2: [add a duplicate flag to DynamicDialogConfig]
step_3: [two overload method are deprecated]
----------
issue fixed:
dynamic dialog module (same instances on top of each other) #13646
https://github.com/primefaces/primeng/issues/13646
----------
> Fix #13646 dynamic dialog module same instances on top of each other/get rid of deprecated implementation

- src/app/components/confirmpopup/confirmpopup.ts
Fix #13714
Now when you add `dismissableMask: false` in your `confirmationService` the `confirmPopup` will not close.
By default continue working as always, if you don't add the property, if you click outside, will close.
**Note:** In the following gif, I am clicking many times and it does not close after have applied `dismissableMask: false`
> 13714 - fix dismissableMask on confirmPopup component

- src/app/components/tabview/tabview.ts
Fix #13746
Also fix for https://github.com/primefaces/primeng/issues/9475 "latter half", where dynamic changes on tabpanel style are not detected.
> Fix for #13746, tabview style changes are not immediately registered

- src/app/showcase/doc/inputnumber/buttonsdoc.ts
Fix #13752
Added `are` instead `is`
> fix typo inputnumber

- src/app/components/confirmpopup/confirmpopup.ts
Fixes #13761. The changes I made in #13035 worked for me locally, but when I updated our application to use the 16.0.1 release, there was a different error with the same cause. This pull request fixes that error and should properly fix #13034. 
Added a new bug report #13761 so it can have its own milestone, although the underlying issue is the same.
> Fixes #13761. Breaking out early in the align() method when the confirmation is null.

- src/app/components/table/table.ts
Fixes #13392 
Merge pull request #13392 fixed issue #13361 but caused filters not to automatically close when clicking different filter icon buttons.
This pull request fixes "properly" issue #13361 and as a result fixes the bug that was induced by the original attempted fix.
This pull request reverts the original changes to fix issue #13361.  Instead of stopping the click event propagation,   the original isFilterElement method is reinstated and is improved by calling a new  isFilterElementIconOrButton method.
**The following demonstrates step by step the original issue, the incorrect fix, and the improved fix.**
Movie 1) shows the original issue #13361  in v16.0.2
https://github.com/primefaces/primeng/assets/45439491/80014fc3-d7ef-4bdf-9a53-49bd75bf0d81
Movie 2) shows proper filter …
> properly fix issue #13361

- src/app/components/api/tooltipoptions.ts
- src/app/showcase/doc/dataview/importdoc.ts
Fix #13794
This import is not necessary
> Dataview / Tooltip: Fix wrong documentation

- src/app/components/selectbutton/selectbutton.ts
- src/app/showcase/doc/apidoc/index.json
Fix #13853 - SelectButton: Add allowEmpty property
> Fix #13853 - SelectButton: Add allowEmpty property

- src/app/components/menu/menu.ts
fix #13766 a missed break; modified
> fix #13766 a missed break; modified

- src/app/components/carousel/carousel.ts
- src/app/components/galleria/galleria.ts
- src/app/components/image/image.ts
- src/app/components/multiselect/multiselect.css
Fixes #13816 
- Add missing css.
Ignored unnecessary files, run code format and re-opened the PR
> Issue 13816

- src/app/components/carousel/carousel.ts
- src/app/components/galleria/galleria.ts
- src/app/components/image/image.ts
- src/app/components/tooltip/tooltip.css
- src/app/components/tooltip/tooltip.ts
Fix #13828
I have reverted the problem caused by this commit: https://github.com/primefaces/primeng/commit/bc98f435587562e234b36d035e0a544884232813.
[This was the issue](https://github.com/primefaces/primeng/issues/13680) before but I have not be able to reproduce the flickering in the tooltip and for that I think the best solution was remove the `pointer-events`.
Finally I added a conditional to avoid the flickering. I cannot reproduce it but just in case now I added `pointer-events: none` when is `autoHide=true` and `pointer-events: unset` when `autoHide=false`. All works perfectly.
> 13828 fix autohide tooltip

- src/app/components/image/image.ts
- src/app/components/password/password.css
- src/app/showcase/doc/inputnumber/verticaldoc.ts
Fix #13817
I tried two or three solutions but this was the best alternative and works perfectly with all the cases:
- `[showClear]="true"` && `[toggleMask]="true"`
- `[showClear]="true"` && `[toggleMask]="false"`
- `[showClear]="false"` && `[toggleMask]="true"`
Note: The others files were formatted. Only I modified the `password.css` file.
> Password: Fix alignment icons

- src/app/components/toolbar/toolbar.ts
- src/app/showcase/doc/toolbar/basicdoc.ts
- src/app/showcase/doc/toolbar/templatedoc.ts
- src/app/showcase/doc/toolbar/toolbardoc.module.ts
- src/app/showcase/pages/toolbar/toolbardemo.ts
Fixes #13814 
There is generally an inconsistency regarding the naming of the templates (left vs. start, right vs. end). Additionally the documentation doesn't reflect the implementation of the Toolbar, means it only accepts right and left as template names.
The Toolbar now **additionally** accepts the template names `start` and `end`.
> Toolbar: Accept documented template names #13814

- src/app/components/accordion/accordion.ts
> fix: accordionTab.toggle() with no args

- src/app/components/api/menuitem.ts
- src/app/components/breadcrumb/breadcrumb.ts
- src/app/components/contextmenu/contextmenu.ts
- src/app/components/megamenu/megamenu.ts
- src/app/components/menu/menu.ts
- src/app/components/menubar/menubar.ts
- src/app/components/panelmenu/panelmenu.ts
- src/app/components/tabmenu/tabmenu.ts
- src/app/components/tieredmenu/tieredmenu.ts
- src/app/showcase/doc/menu/customdoc.ts
- src/app/showcase/doc/menu/menudoc.module.ts
- src/app/showcase/doc/tabmenu/templatedoc.ts
> Fixed #13910 - Menu Templating

- src/app/components/accordion/accordion.ts
- src/app/components/carousel/carousel.ts
Fixed #13974 - Fixed carousel circular not working on init in some cases
Added more change detection so initial state is working correctly.
(Also contains prettier fix)
> Fixed #13974 - Fixed carousel circular not working on init in some cases

- src/app/components/overlaypanel/overlaypanel.ts
Fixes #13601 #13605 
Starting from version **16.2.0** the component OverlayPanel suffered a significant regression when it contains a component through the template directive.
It would close after a random number of clicks inside the contained component, making the component unusable. The problem is reproducible by inserting any PrimeNg component inside the OverlayPanel and rendering it through Template directive.
Restored part of the check previously modified in PR #13480 to solve problem where OverlayPanel component would not close when user clicks outside the panel.
> Fixed OverlayPanel containing component

- src/app/components/dropdown/dropdown.ts
Fixed #14007 dropdown has Cannot read properties of undefined (reading 'length') when this.label() is null
> Fixed #14007 - Dropdown empty label error

- src/app/components/confirmdialog/confirmdialog.ts
In Confirmdialog component , defaultFocus 'none' type is missing.
> Fix Confirmdialog defaultFocus type

- src/app/components/dropdown/dropdown.ts
Fix for issue: Dropdown: In PrimeNG 16.7.1 interacting with dropdown causes panel to scroll #14039
Video after the fix:
https://github.com/primefaces/primeng/assets/45439491/f757b663-2795-4c9f-910f-34626f621981
> Fix  for PrimeNG 16.7.1 interacting with dropdown causes panel to scroll #14039

- src/app/components/selectbutton/selectbutton.ts
Fixes #14048
Added a check to see if allowEmpty  equals false before updating selected to null
> Enforce allowEmpty for SelectButton, fixes issue #14048

- src/app/components/accordion/accordion.ts
- src/app/components/splitbutton/splitbutton.ts
> SplitButton: Hide menu on click on default button.

- src/app/showcase/doc/messages/closabledoc.ts
This is a very simple fix as there is no error/defect. This is just something I noticed when searching for "warning" in the files, but not being able to find the string. 
edit: Forgot to create an issue first. 
Fix https://github.com/primefaces/primeng/issues/14009
> Fix closabledoc.ts typo for messages component

- src/app/components/fileupload/fileupload.ts
Closes #13722
Here's a summary of the changes made
- Previously, we were using a generic mouseup event to detect the click event on the FileUpload component
- I've now refined it to specifically detect left mouse clicks, making our event handling more precise
- This change ensures that our component responds correctly to left mouse clicks without interfering with other mouse actions.
Please review the code changes, and if everything looks good, consider merging this update.  Kindly let me know if any changes required.
> Fix #13722: FileUpload click instead of mouseup

- src/app/components/table/table.ts
> fix(primeng/pEditableColumn): update column data in runtime

- src/app/components/chips/chips.ts
- src/app/showcase/doc/chips/chipsdoc.module.ts
- src/app/showcase/doc/chips/maxvaluesdoc.ts
- src/app/showcase/pages/chips/chipsdemo.ts
Fixes https://github.com/primefaces/primeng/issues/14062
Added documentation for max items functionality
> fix: p-chips do not work with reactive forms

- src/app/components/tooltip/tooltip.ts
> Bug fix: #14014 - p-tooltip : autohide="false" does not work every time

- src/app/components/sidebar/sidebar.ts
> Bug fix: #13933 - SideBar onHide Not trigger

- src/app/components/multiselect/multiselect.ts
> fix: #14058 || MultiSelect onPanelShow is not fired when there are no options

- src/app/components/listbox/listbox.interface.ts
- src/app/components/listbox/listbox.ts
- src/app/components/multiselect/multiselect.interface.ts
- src/app/components/multiselect/multiselect.ts
- src/app/showcase/doc/listbox/virtualscrolldoc.ts
- src/app/showcase/doc/multiselect/virtualscrolldoc.ts
Fixes #13993 
- `SelectAllChange` event added,
- `selectAll` boolean input added
Users can manage the selection state of all items from outside of the component without looping through options array and update selection state which causes browser freeze on select/deselect actions.
> Fixed #13993 - Performance update for virtualScroll selection

- src/app/components/multiselect/multiselect.ts
> fix: #14057 || MultiSelect Empty Filter Message / Template is not working when you have options

- src/app/components/table/table.css
Fix: #13781 
I apologize for any oversight in my previous pull request. In this new pull request, I've taken steps to ensure that the changes won't adversely affect any other parts of the codebase.
The primary change in this PR involves adjusting the z-index values for various elements. Specifically, I've set the z-index of datatable-thead and rowgroup-header to level 2, and the datatable-loading-overlay now has a z-index of 3.
I also considered raising the z-index of datatable-tfoot to level 2, but after thorough testing, I couldn't identify any issues with the current setup. I'm somewhat uncertain about whether this adjustment is necessary, so I'd appreciate any guidance or suggestions in this regard.
Please review the changes, and I'm open to any feedback or additional adjustments to …
> fix: #13781 || dataTable: frozenColumn header overlap with frozen body

- src/app/components/autocomplete/autocomplete.ts
- src/app/components/image/image.ts
- src/app/components/toast/toast.ts
- src/app/showcase/doc/Image/accessibilitydoc.ts
Fix #14262
I only modified the `autocomplete.ts` file. The rest of the files were formatted.
> Fix(AutoComplete): Change Detection Issue

- src/app/components/multiselect/multiselect.ts
#14194
Replaced `searchFields` variable with `searchFields()` method and also added `label` as default field to search if no `filterBy` or `optionLabel` is present.
> 14194: Fixed filter with default 'label' field

- src/app/components/autocomplete/autocomplete.ts
Fix #14300
If you are using `AutoComplete` inside a `overlayPanel`, when removes the autocomplete option, it close the overlayPanel because is propaganding events.
> fix(autocomplete): Stop event propagations on remove option

- src/app/components/dropdown/dropdown.ts
> fix: #14051 || applyFocus() method is working only when dropdown is editable.

- src/app/components/overlaypanel/overlaypanel.ts
Fixes #14120 introduced with #13480
See [stackblitz reproduction](https://stackblitz.com/edit/ixhekz-mkfatr?file=src%2Fapp%2Fdemo%2Foverlay-panel-template-demo.html)
> OverlayPanel: Fix regression #14120 detect click on scrollbar, prevent hiding when selecting dropdown options

- src/app/components/picklist/picklist.ts
https://github.com/primefaces/primeng/issues/14339
Only allow to lists greater than 0 to be focused to prevent 'Cannot read properties of undefined' by not allowing function to try to get an item from an empty array.
> 14339 - Picklist

- src/app/components/autocomplete/autocomplete.ts
Fix #14389 
ForceSelection flag set to true at p-autocomplete waits for actual selection to change model value of associated form control.
**Before:**
**After:**
<note, on the element I've added the flag, at demo it isn't there>
Values seen in console are from subscription on form control associated with the element.
> Fix #14389: ForceSelection does not force selection - formControl value is changed even without selection

- src/app/components/dropdown/dropdown.ts
This PR fix issue with displaying "No results found" / "Empty filter message template" for Dropdown component. The same issue was fix for Multiselect component under this PR: https://github.com/primefaces/primeng/pull/14096
right now `isEmpty` method checking filtered list, not the one provided in input.
> fix: Dropdown Empty Filter Message not displayed

- src/app/components/autocomplete/autocomplete.ts
Fix #14281 
When Autocomplete has a long list of options `p-hidden-accessible` element is rendered outside of the viewport, and because of that the whole page becomes scrollable. For additional info check out attached issue.
With this fix accessibility element now is rendered in the bottom-left corner of overlay, same as in Dropdown and MultiSelect components.
> Fix #14281 - Autocomplete with long list of options make the whole page scrollable

- src/app/showcase/doc/dataview/sortingdoc.ts
sortField was noted twice. If you want me to make an issue for this, I will. Seemed a bit excessive since it doesn't touch any features.
Edit: created issue: https://github.com/primefaces/primeng/issues/14391
> Fix documentation typo

- src/app/components/table/table.ts
When you do a mouse selection that ends outside the filter frame, with "click"event it close the column filter. This change the event listener to mousedown to avoid this issue.
#14410
> columnFilter: hide on mousedown instead of click

- src/app/components/togglebutton/togglebutton.ts
For `ToggleButton` component the `tabindex` attribute value is not set as expected.
#14443
> Fix setting tabindex attribute on ToggleButton

- src/app/components/dropdown/dropdown.ts
Fixes #14323 created with  https://github.com/primefaces/primeng/pull/13991/commits/f52340b9daf5ea2ee921fc0906838b98007cd6ed
When selecting a dropdown option inside an `OverlayPanel` the click event also has to be processed by the options overlay and the `OverlayService`. Otherwise the `OverlayPanel` is not aware that the click on the option is a click on its content => `OverlayPanel` is closed. Unfortunately when improving the accessability an older "workaround" which handels the issue was removed and has now been added again.
Before:
After:
@cetincakiroglu would be great if you could have a look! 😄
> Fix #14323: Dropdown fix regression - options overlay is closed before it handles the click event

- src/app/components/autocomplete/autocomplete.spec.ts
- src/app/components/checkbox/checkbox.spec.ts
- src/app/components/chips/chips.spec.ts
- src/app/components/inputswitch/inputswitch.spec.ts
- src/app/components/listbox/listbox.spec.ts
- src/app/components/multiselect/multiselect.spec.ts
- src/app/components/selectbutton/selectbutton.spec.ts
- src/app/components/tristatecheckbox/tristatecheckbox.spec.ts
Fix test case error for autocomplete 
The 'onKeydown', 'onKeyup' and 'selectItem' methods have been renamed to 'onKeyDown', 'onKeyUp', and 'onOptionSelect', respectively in the autocomplete test script. Changes made to maintain consistency with actual method naming, enhancing readability and maintainability of the tests.
> Rename autocomplete methods in test

- src/app/components/tree/tree.ts
Resolves #14251 
When a tree node attribute `selectable` is set to `false`, we want to indicate this visually by making the checkbox 
- Added `p-disabled`; I think we should also reduce the entire row `opacity`, not only the checkbox.
> Fix the tree checkbox css issue and make it clearer when it is disabled

- src/app/components/table/table.ts
Performing the fix for the filters and maintaining the global filtering behavior
> Fixed #14432

- src/app/components/table/table.ts
Fixes #14248
Exporting a table with 3 columns while the last one is not exportable will still print a csvSeparator after the 2nd column, leading into an empty column in most CSV viewers.
Only exportable columns will be taken into account while considering printing csvSeparator.
> fix: Do not take into account non exportable fields for csv separators

- src/app/components/toast/toast.ts
- src/app/showcase/doc/toast/headlessdoc.ts
Suggestion for https://github.com/orgs/primefaces/discussions/740
Provide default toast-closing callback to headless toasts in case they want to implement their own close button
Fixed #14483
> feat(toast): providing close callback to headless toast template

- src/app/showcase/doc/treetable/gridlinesdoc.ts
- src/app/showcase/doc/treetable/sizedoc.ts
- src/app/showcase/doc/treetable/treetabledoc.module.ts
- src/app/showcase/pages/treetable/treetabledemo.ts
https://github.com/primefaces/primeng/issues/14024 - Missing size, gridlines documentation
Added Size, Gridlines documentation similar to Table Component
Necessary styleClass already exists
> Treetable: size,gridlines documentation

- src/app/components/table/table.ts
#14140
`rangeEnd` was missing while the table is lazily loaded and hence was selecting the whole page while using `shift` key
> FIX: Multiple selection with SHIFT/click

- src/app/showcase/doc/chart/chartjsdoc.ts
- src/app/showcase/doc/chart/stackedbardoc.ts
Fixes #12506
ChartJS no longer requires adding the script to angular.json because PrimeNG is using the ESM `chart.js/auto` import. Attempting to follow the PrimeNG docs results in an error.
The Stack Bar example also included a customization for tooltips which were improperly configured. 
The [configuration object](https://www.chartjs.org/docs/latest/configuration/tooltip.html#tooltip-configuration) is "tooltip", not "tooltips".
Please note that the StackBlitz and CodeSandbox examples do not include the script tag in angular.json, **but they do have the "tooltips" bug and should also be changed**.
Smaller scaled feature …
> Fix #12506 | Chart Docs - Import instructions and tooltip customization

- src/app/components/inputnumber/inputnumber.ts
When a negative number is entered with a suffix and minimum fraction digits, the format was incorrect.
For example:
-suffix " %"
-minFractionDigits 2
-0 resulted in a -00 concat value. (correct would be 0.00 %)
This results in a new call of formatValue() in handleOnInput(). The format is then correct, but the cursorposition is put to the end of the input: "0.00 %|" instead of "0|.00 %"
Fix #13651
> Fixed curser position for negative numbers with suffix

- src/app/components/panel/panel.ts
Fixes #14508 by generating one unique id for the component rather than a new one each time the property is read.
> Fix #14508 Panel id generation

- src/app/components/table/table.ts
SimpleChanges might not have `data` defined when only other input than `data` changes.
For details see reporting issue: https://github.com/primefaces/primeng/issues/14525
> Fix #14525 reading properties of undefined during EditableColumn changes

- src/app/components/table/table.ts
Fixes https://github.com/primefaces/primeng/issues/14562
Fix is based on https://stackoverflow.com/a/41363077
Tested on Microsoft Excel 2013
Input data:
Before fix: 
After fix:
> Fix #14562: Export CSV with cyrillic or chinese characters has broken encoding in Microsoft Excel

- src/app/components/paginator/paginator.interface.ts
- src/app/components/paginator/paginator.ts
- src/app/components/table/table.interface.ts
- src/app/components/table/table.ts
#9605
Hello, I've noticed that it is not possible to customize dropdown trigger icon in `page size selector` dropdown that is used inside Paginator and Table component.
The issue has been closed over 1 year ago without a fix.
Please let me know if my changes are sufficent. If not, please let me know what to change or just prioritize implementing this internally as it impacts custom theming.
> feat: Paginator & Table - Add option to customize dropdown icon #9605

- src/app/components/carousel/carousel.ts
Fixes swiping on carousel on iOS devices (Issues #12942 & #9786) by moving the existing touch event listeners to the parent div (.p-carousel-items-content), similar to the [implementation of the PrimeVue carousel](https://github.com/primefaces/primevue/blob/c8609171c29c702da09054d901fc76a671248ef8/components/lib/carousel/Carousel.vue#L24).
> Fix Carousel touch events on iOS devices

- src/app/components/multiselect/multiselect.ts
Fixed #14611
The first video demonstrates that after the pull request changes the scrolling issue with the PrimeNG table filter row demo is fixed.
https://github.com/primefaces/primeng/assets/45439491/32f9134f-f7de-4a43-aaa0-720e5b8b5b90
The second video demonstrates that after the pull request changes the reproducer is fixed.
https://github.com/primefaces/primeng/assets/45439491/1cbd49e3-7eab-45a8-abfb-7862e544c0f0
> fix #14611 -- fixed  multiselect scrollIntoView to use 'nearest'

- src/app/components/table/table.ts
fixed #14613 
The two annotated screenshots listed below show that the pull request fixes the issue for the PrimeNG table filter menu demo.
> fix #14613 - updated column filter's trash and plus icons

- src/app/components/calendar/calendar.css
- src/app/components/calendar/calendar.ts
Fix #14606
This fix was the root cause of the issue:
https://github.com/primefaces/primeng/issues/14501
I added a class to the inline icon in the input, to make it more restrictive and only disable pointer events for this specific icon
Update:
@k0sr mentioned another bug with this solution. The pointer events need to stay when the calendar does not open when focusing the input.
This partially reverts 14501. So we need another solution for that
> fix #14606 restricted pointer events more

- src/app/components/paginator/paginator.spec.ts
- src/app/components/table/table.spec.ts
- src/app/components/table/table.ts
Paginators in a table used to have position classes, e.g. `p-paginator-top` or `p-paginator-bottom` but are missing since https://github.com/primefaces/primeng/commit/6069219df46666c81a23fd6e50eb755a17b7e87f#diff-54f9fcc81f3c7d880cfe5f7ddd5dda1e60f15581a7ce88dd922b0586b1f259a1
due to conflicting bindings
```html
<p-paginator
styleClass="p-paginator-top"
[styleClass]="paginatorStyleClass"
```
> fix(table): paginator missing p-paginator-top/bottom class

- src/app/components/dropdown/dropdown.ts
Fixes #14367
I didn't want to create a duplicate issue for this problem, but did create a very simple demo of the issue in Stackblitz:
https://stackblitz.com/edit/stackblitz-starters-xxhaw6?file=src/main.ts
> Fix #14367: Dropdown selected item template

- src/app/components/dropdown/dropdown.ts
Fix #14596
1) fixes logic for the dropdown's selectedOption
2) uses dropdown's selectedOption for computing label
-- note: issue with virtual scrolling with lazy loading (PrimeNG Demo) as a result keeping original logic for computing label when virtual load (no harm)
The following  video demonstrates  the fix working for the reproducer in  issue #The following video demonstrates the fix.
https://github.com/primefaces/primeng/assets/45439491/2bacb0a7-ff42-480c-82d2-bef95157e6da
> Fix #14596 - fixes p-dropdown logic for selectedOption and label

- src/app/components/dropdown/dropdown.ts
- src/app/showcase/doc/dropdown/filterdoc.ts
See #14715
Not sure if this is by design or if a larger set of value should or should not be accepted (such as true/false), feel free to reject this PR. I did hesitate to use ObjectUtils.isNotEmpty but since it excludes an empty string as being an authorized option, I thought it may be too much.
> fix(14715): selecting a falsy value (such as '0' or 0) should not show placeholder

- src/app/components/dropdown/dropdown.ts
> Fix Dropdown: dynamic text in placeholder is not displayed fixes #14320

- src/app/components/timeline/timeline.ts
- src/app/showcase/pages/chips/chipsdemo.ts
closes #14783 
Changed `seperator` to `separator`
> chore: typo separator

- src/app/components/progressspinner/progressspinner.ts
- src/app/showcase/doc/progressspinner/basicdoc.ts
> Fixed #14798 - ProgressSpinner | Unable to set aria-label

- src/app/components/dropdown/dropdown.ts
Fixed #14716
Fixed #14757
re-fixed #14596 - v17.6.0 broke  changes that were made in v17.5.0 that were used to fix issue #14596
The changes:
1) when computing the label,  use  all options verses just visible options this new logic will find the selected option whether or not the user is currently filtering  because the filtered (i.e. visible) options, are a subset of all the options
2) When finding selected option,  consider all options even those that have been disabled
**Note: These changes supersedes PR #14759.  This PR contains all the changes of #14759 (change (1)) plus change (2)**
Please see the annotated screenshot and the  video listed below  which shows the fixed issue #14716
https://github.com/primefaces/primeng/assets/45439491/5c801d9f-0894-4f8c-af07-bb7d770af402
> fixed #14716 and fixed #14757 - updated computed label logic to also handle disabled selected option

- src/app/components/contextmenu/contextmenu.ts
> Fixed #14773 - ContextMenu | Double opacity applied to disabled items

- src/app/components/dom/domhandler.ts
Fixes [#14691](https://github.com/primefaces/primeng/issues/14691) by checking if each element is visible.
> Fix #14691 DomHandler.getFocusableElements returns visible elements

- src/app/components/dom/domhandler.ts
Reverts primefaces/primeng#14692
> Revert "Fix #14691 DomHandler.getFocusableElements returns visible elements"

- src/app/components/dom/domhandler.ts
Fix for #14691  
Improved previous fix by by using the global `getComputedStyle`.
Also consolidated `getComputedStyle` calls, so now there's only one instead of two.
> Fix #14691 DomHandler.getFocusableElements should return only visible els

- src/app/components/contextmenu/contextmenu.ts
For both `appendTo="'body'"` and `appendTo="templateVariable"` check if there is `this.containerViewChild`.
Fixes #14793
> Fix: #14793 check if containerViewChild exists before removing

- src/app/components/multiselect/multiselect.ts
Fix  #14807 
Fix #14252
Fix #14603
I  updated the onToggleAll method to call onChange.emit and onSelectAllChange.emit.  Special logic was add to determine whether or not onSelectAllChange.emit should be called since a user could be filtering.
The first video shows the issue #14807 reproducer (which I created based on the steps provided in the issue)  working after the fix.  Note:  the end of the video shows  how the changes work when the user filters  before toggling on and off
https://github.com/primefaces/primeng/assets/45439491/8cb5feb5-81d1-4365-b306-62250ee9f5d3
The second video shows the  issue #14252 reproducer working after the fix.  Note:  the end of the video also shows  how the changes work when the user filters  before toggling on and off …
> fixed #14807 #14252 #14603 - updated onToggleAll method to call onChange and onSelectAllChange

- src/app/components/dropdown/dropdown.ts
Fixed #14815
The video listed below shows the issue #14815 reducer working after the fix (Note "All" option corresponds to  
`{name: 'All',code: null})`
https://github.com/primefaces/primeng/assets/45439491/0c9c6130-6252-4aa5-b1d7-7c570345bac6
Note:  I verified the fix did not break any of the PrimeNG demo dropdown examples
The issue was caused by a special case where the modelValue is null but the selected option's value is also null.
As part of the PR,  I also renamed the method **isOptionEqualsModelValue** to **isOptionEqualsModelValue** which is a more descriptive name.  Note:  in a previous PR #14768 that was accepted I refactored the code that resulted  in the original **isOptionEqualsModelValue** method
> Fixed #14815 - improved logic when modelValue is null and selected option value  is null

- src/app/components/tabmenu/tabmenu.spec.ts
- src/app/components/tabmenu/tabmenu.ts
Fixes #14867 
When the TabMenu is controlled by updating the activeItem property, the updateInkBar() method isn't called hence the reason the inkbar doesn't get updated in the UI.
After the fix
> Fixed #14867 - Tab change inkbar for material design theme

- src/app/components/utils/objectutils.ts
since the Util function is only used within multiselect, it should have no side effects. Also uses kind of best practices according to SO to determine if something is an object https://stackoverflow.com/questions/8511281/check-if-a-value-is-an-object-in-javascript
Fixes https://github.com/primefaces/primeng/issues/14835
> fix isObject detection (closes #14835)

- src/app/showcase/layout/doc/app.docapisection.component.ts
- src/app/showcase/layout/doc/app.docapitable.component.ts
> Fixed  #14942 - Only showing first parameter

- src/app/components/calendar/calendar.ts
This fixes issue #15005 using the current date when setting a time before picking a date.
Fix #15005, allows users to pick a time before specifying a date in calendars with `showTime` enabled. 
Modified the implementation of `calendar.validateTime()` to set the date value to the current date when validating a time without picking a date first. Previously, `Calendar.value` was `undefined` when trying to access it as an array [here](https://github.com/primefaces/primeng/blob/13fbaf38acba3ba3a5fb1f35832baf607bce4ef3/src/app/components/calendar/calendar.ts#L2488C5-L2488C16), causing the error mentioned in #15005.
- This is my first PR here, so please bear with me as I get used to this :)
- This currently works by defaulting to the current date... so it could be a band-aid/temp solution? 
- …
> fix: #15005 Calendar time-picker errors when changing time before date

- src/app/components/chip/chip.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/doc/chip/imagedoc.ts
Fix https://github.com/primefaces/primeng/issues/15000
- Added alt attribute when `Chip` component has image.
> feat(Chip): Add alt attribute

- src/app/components/calendar/calendar.ts
fix: primefaces #14839, Calendar: The lowest year in the Year navigator dropdown remains disabled when we are applying minDate in date selector.
> fix: primefaces #14839, Calendar: The lowest year in the Year navigator dropdown remains disabled when we are applying minDate in date selector

- src/app/components/listbox/listbox.ts
Fix empty message displaying for Listbox component, closes https://github.com/primefaces/primeng/issues/14459
Before:
After:
> fix #14459 p-listbox empty message for filter

- src/app/components/table/table.ts
- src/app/showcase/doc/table/filterrowdoc.ts
fixes https://github.com/primefaces/primeng/issues/15024
Added aria-label support.
> fix #15024 table filter row aria-labels

- src/app/components/table/table.ts
Fixes #14987 
The root of this issue stems from having two distinct dialog overlays appended to the body of the DOM. In the document event listener, the check for whether or not the user has clicked outside of the overlay only applies to the singular column-filter-menu overlay. In the specific case of the datepicker, this second overlay is not considered when this check occurs, thereby rendering any event target as invalid, closing the dialog.
This fix handles the following:
- Checks for the presence of multiple divs with the "role" attribute having a value of "dialog". If the number is greater than 1, disable the default behavior of closing the column filter dialog, prioritizing the behavior of the other dialogs. This was written to handle other cases beyond just the datepicker, though …
> Fixed #14987 - Table | Date Filter Closing Unexpectedly

- src/app/components/tree/tree.ts
fix: issue-12718 in tree with virtual scroll  parent node always undefined
https://github.com/primefaces/primeng/issues/12718
> fix: issue-12718 in tree with virtual scroll  parent node always undefined

- src/app/components/calendar/calendar.ts
Fixes #13919 
When checking the year for disabled status, now each month is checked for disability. 
An optional year parameter has been added to the isMonthDisabled method
> fix(calendar): added checking for each month when checking the disabled year

- src/app/components/tieredmenu/tieredmenu.ts
> fixes 15058 - keyboard navigation for tieredmenu with hidden elements

- src/app/components/table/table.ts
Using paginator take in consider actual page.
Selection - while toggling groups use groupRowsBy field instead of dataKey, otherwise is not possible use row selection.
> Fix #13783 and #14081 - Table | expandable groups broken with paginator, Expansion and Selection not Working Together

- src/app/components/inputotp/inputotp.ts
> Fix: Integer input from numpad

- src/app/components/multiselect/multiselect.ts
Fixes #15135
[https://github.com/primefaces/primeng/issues/15135](url)
1. Fixed the comment that gets repeated twice.
> fixes #15135 Repeated Comments issue

- src/app/components/table/table.ts
no need to filter when removeConstraint called and showApplyButton is visible exactly like onOperatorChange.
> no need to filter when removeConstraint called and showApplyButton is visible

- src/app/components/dynamicdialog/dialogservice.ts
- src/app/components/dynamicdialog/dynamicdialog-ref.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
Motivation:
With the current implementation is hard to do things like use the child component public API (i.e. to populate inputs) because the component is created asynchronously and trying to pass data using the angular lifecycle hooks to access the child component throws errors because often is undefined. Pass the data through the DynamicDialogConfig is a bit tricky.
So I made generic the open method of the DialogService and DynamicDialogRef. The open method of the DialogService now returns a typed DynamicDialogRef that has a new subject (onChildComponentLoaded) where the typed component instance is emitted when loaded.
> feat: Dynamic dialog. Child component reference to be able to 

- src/app/components/calendar/calendar.ts
See discussion #1136 https://github.com/orgs/primefaces/discussions/1136
For context : actually minDate & maxDate are 2 inputs of calendar that only accept non-nullable Date value. What it means is that you can have no value for any of them at startup but once you set any value (for example for search purpose) you can't reset it programmatically, i.e. providing undefined or null value. The only way to perform such reset is by using clear option (with [showClear]=true) or emptying the field manually (such leading in false value).
This change is all about enabling minDate & maxDate value to accept undefined value allowing free programmatical change, all checks about its truthyness being already handled. Let me know if null should be accepted instead/aswell.
> Feat: calendar - enable minDate & maxDate to be nullable

- src/app/showcase/doc/apidoc/index.json
This commit fixes the type in `MessageService` doc
> fix: `MessageService`  doc typo

- src/app/components/editor/editor.ts
This PR is enhancing changes made on [PR #14232](https://github.com/primefaces/primeng/pull/14232). During SSR build this issue #8817  still occurs.
So it seems the issue comes from importing quill on the top level, which somehow automatically initializes the instance of Quill.
```ts
import Quill from 'quill'
```
So on this update, I have removed the import from the top level to dynamically import quill when it's in browser mode.
I also introduced [afterNextRender](https://angular.dev/guide/components/dom-apis#) because render callbacks never run during server-side rendering or build-time pre-rendering.
> FIX: Editor Module. ReferenceError: document is not defined. #8817 

- src/app/components/calendar/calendar.spec.ts
- src/app/components/calendar/calendar.ts
- src/app/showcase/doc/calendar/minmaxdox.ts
This PR fixes this issue #10358 
i.e. it now allows the user to use the time selector but it changes the actual time value to be clamped within min/max date inputs
> #10358: fix date restriction within the hour issue

- src/app/components/calendar/calendar.ts
onTodayClick doesn't return Date
Fixed https://github.com/primefaces/primeng/issues/15148
> fix - Calendar onTodayClick emit

- src/app/components/multiselect/multiselect.ts
fixes #14945
Added toggleAllAriaLabel. Filter text box already have aria-label that can be set from ariaFilterLabel input: https://primeng.org/multiselect#api.multiselect.props.ariaFilterLabel
> fix #14945 MultiSelect toggleAllAriaLabel

- src/app/components/dropdown/dropdown.ts
> Fixed #15122 - Dropdown | Missing ariaLabel when in editable = true

- src/app/components/dropdown/dropdown.ts
- src/app/components/multiselect/multiselect.ts
> Fixed #15197

- src/app/components/multiselect/multiselect.ts
Fixed #15229: keep pre-selected disabled options selected when filtering and checking toggleAll
https://github.com/primefaces/primeng/issues/15229
> Fixed #15229: keep pre-selected disabled options selected when filtering and checking toggleAll

- api-generator/build-apidoc.ts
- src/app/components/autocomplete/autocomplete.ts
- src/app/components/calendar/calendar.spec.ts
- src/app/components/calendar/calendar.ts
- src/app/components/cascadeselect/cascadeselect.ts
- src/app/components/inputotp/inputotp.ts
- src/app/components/treeselect/treeselect.ts
- src/app/showcase/doc/treeselect/virtualscrolldoc.ts
- src/app/showcase/service/nodeservice.ts
> Bug #15188 - Autocomplete: multiple and readonly still show button to remove options

- src/app/components/dynamicdialog/dynamicdialog.ts
- src/app/showcase/doc/dynamicdialog/exampledoc.ts
> fix #15144 DynamicDialog get closeAriaLabel

- src/app/showcase/doc/theming/scalingdoc.ts
Pointed out in PrimeLand discord; there is a typo in the Scaling docs. "reqire" should be "require".
> Fix typo in Scaling docs

- api-generator/build-apidoc.ts
- src/app/components/autocomplete/autocomplete.ts
- src/app/components/calendar/calendar.spec.ts
- src/app/components/calendar/calendar.ts
- src/app/components/cascadeselect/cascadeselect.ts
- src/app/components/inputotp/inputotp.ts
- src/app/components/treeselect/treeselect.ts
- src/app/showcase/doc/treeselect/virtualscrolldoc.ts
- src/app/showcase/service/nodeservice.ts
> Bug #15208 - Autocomplete: Down/Up arrows trigger (onSelect) event when [autoHighlight]="true"

- src/app/components/inputnumber/inputnumber.ts
- src/app/components/table/table.ts
fixes https://github.com/primefaces/primeng/issues/15264
> fix: #15264 use null as fallbackValue for input transform of minFractionDigits and maxFractionDigits

- package-lock.json
- src/app/components/messages/messages.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/doc/messages/servicedoc.ts
#15260
`<p-messages>` element does not use `msg.closable` in the `*ngIf`. This means that when adding multiple messages to the service, you cannot have some closable and others not closable.
This PR adds the logic and updates the documentation to fix this and allow the ID attribute to be set from the `Message` object.
> #15260: Messages component uses `closable` and `id` from `Message`

- src/app/showcase/doc/panel/styledoc.ts
Just a documentation fix I noticed today
> Fixes Panel's styling class names in documentation

- src/app/components/autofocus/autofocus.ts
- src/app/components/button/button.ts
- src/app/components/calendar/calendar.ts
- src/app/components/cascadeselect/cascadeselect.ts
- src/app/components/checkbox/checkbox.ts
- src/app/components/chips/chips.ts
- src/app/components/colorpicker/colorpicker.ts
- src/app/components/dialog/dialog.ts
- src/app/components/dom/domhandler.ts
- src/app/components/dropdown/dropdown.ts
- src/app/components/dynamicdialog/dynamicdialog-config.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
- src/app/components/inputmask/inputmask.ts
- src/app/components/inputnumber/inputnumber.ts
- src/app/components/inputotp/inputotp.ts
- src/app/components/inputswitch/inputswitch.ts
- src/app/components/multiselect/multiselect.ts
- src/app/components/password/password.ts
- src/app/components/radiobutton/radiobutton.ts
- src/app/components/rating/rating.ts
- src/app/components/selectbutton/selectbutton.ts
- src/app/components/slider/slider.ts
- src/app/components/splitbutton/splitbutton.ts
- src/app/components/togglebutton/togglebutton.ts
- src/app/components/treeselect/treeselect.ts
- src/app/components/tristatecheckbox/tristatecheckbox.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/doc/calendar/propsdoc.ts
fix #14010, fix #13162, fix #13768, fix #13082, fix #10472
> Fix #14010, #13162, #13768, #13082, #10472

- src/app/components/table/table.ts
> Fixed #15233 | Refactor condition for outsideClick

- src/app/components/badge/badge.ts
- src/app/showcase/doc/apidoc/index.json
- src/app/showcase/doc/badge/sizedoc.ts
> feat(primeng/p-badge): rework dynamic property rerender for directive

- src/app/components/card/card.ts
> Fixed #15013

- src/app/components/multiselect/multiselect.ts
> Bug #15304 - Tooltip does not hide on multiSelect clear 

- src/app/components/table/table.ts
Fixes #15303 
https://user-images.githubusercontent.com/11733376/208727545-67866f60-7db8-4256-ae2b-43a0a178753d.mov
Frozen Columns
Lolibai
17.3.1
17.13.0
Angular CLI App
TypeScript
20.12.2
Chrome 123.0.6312.123
1. Freeze columns to the right
2. Have at least 10 rows of data
3. See the "stairs" of columns that should be freezed
https://user-images.githubusercontent.com/11733376/208727545-67866f60-7db8-4256-ae2b-43a0a178753d.mov
All columns should be freezed as per attribute and directive assignment.
[Reproduction](https://stackblitz.com/edit/qnmajp?file=package.json)
> Fix Issue with frozen columns #12408

- src/app/components/table/table.ts
#fix #14803 
Touch and click get coordinates in slightly different ways. Fixed the issue by checking if the movement is made by a touch or a click and getting the x coordinate accordingly.
> Bug #14803: Column resize not working on tablet

- src/app/components/menubar/menubar.ts
Solves issue [#15040 ](https://github.com/primefaces/primeng/issues/15040)
Fixed #15040 
menu items now keeps the focus the clicked/Enterkey one and no longer focuses back to first menuitem
> Menubar: Enter key moves focus at first menuitem 

- src/app/components/keyfilter/keyfilter.ts
- src/app/showcase/doc/keyfilter/regexdoc.ts
FIXED #14639 
This bug was happening because the keyFilter would check each inputted character against the regex meaning you could never check for length of the whole input. Rectifying this meant that the preset Regex's in the keyfilter component had to be adjusted so that they would work again which I have done.
>  Component: KeyFilter #14639 limit input length

- src/app/components/treeselect/treeselect.ts
Fixes #15378 The same problem occurs with the TreeSelect component, and it can be fixed in the same way as it was done in the Checkbox component.
https://github.com/primefaces/primeng/issues/14819
> TreeSelect Disabled State Not Updating Properly

- src/app/components/api/filterservice.spec.ts
- src/app/components/api/filterservice.ts
Fixes #14978 
Previously, the equals and notEquals filters would convert the value and filter to string before comparing them. It now checks if the two are equal before converting them and checking again. This allows 1 == 1.0 etc.
> Bug #14978: Table filter integer does not equal decimal string

- src/app/components/dialog/dialog.ts
Fixes #15022
The bug happens because there's a onMouseDown event on the dialog header that does nothing if the element has class 'p-dialog-header-icon' else it does the drag logic. However when a user clicks on the TimeIcon instead of the button (that has the p-dialog-header-icon css class) , the implements the drag logic instead of closing. I have added the css class of the TimesIcon to fix the bug.
> Fixes #15022:  dialog not closing

- src/app/components/api/filterservice.ts
FIXED #14886 
This bug seemed to be happening with entries that were the same date as the selected filter date but had a later time, there by making them after but on the same day. I have fixed this by changing the time for the entry to (0,0,0,0) during the filter comparison.
> Bug #14886: p-calendar "Date After" filters do not exclude date inclusive

- src/app/components/checkbox/checkbox.ts
> fix(primeng/p-checkbox): support formControlName in multiple mode

- src/app/components/autocomplete/autocomplete.ts
fixes #14599
Implements the ability to set an optionValue, so the autocomplete can also store object properties and not only the object itself
> feature(autocomplete): Add optionValue input

- src/app/components/tieredmenu/tieredmenu.ts
Fixes #13929 
[13929](https://github.com/primefaces/primeng/issues/13929)
`positionSubmenu()` is never called because of this codeBlock beeing deleted in the commit 
https://github.com/primefaces/primeng/commit/28989fd4cafe4ee5b7d805f5b059618f5fc1128b#diff-0f78da967be578fe31289e62b917434f52f9902618913c827f6388d7de7fc3c0L147 
```
@Input() get parentActive(): boolean {
return this._parentActive as boolean;
}
set parentActive(value) {
if (!this.root) {
this._parentActive = value;
if (!value) this.activeItem = null;
else this.positionSubmenu();
}
}
```
> fix 13929 tieredMenuSub not posititioning itself within viewport

- src/app/showcase/doc/chart/combodoc.ts
- src/app/showcase/doc/theming/primeflexdoc.ts
Fixed a couple spots in the docs from 'usign' to 'using'.
Let me know if I should open an issue for this, from looking at past PRs it looks like this might be small enough that might not be needed.
Thanks!
> docs: typo in chart and primeflex docs

- src/app/components/tieredmenu/tieredmenu.ts
Fixes [13929](https://github.com/primefaces/primeng/issues/13929) (improvement)
This fix seems to work more stable but it requires a change to signal input for activePathItem please review.
TieredMenu uses already input signals but TieredMenuSub not.
As soon as there is space again on the right side it does not flip in further subviews:
> fix tieredMenuSub not positioning itself within viewport

- src/app/components/paginator/paginator.ts
> Fix paginator getPageAriaLabel replacement

- src/app/components/megamenu/megamenu.spec.ts
- src/app/components/megamenu/megamenu.ts
Fixes #15110 
The megamenu keyboard navigation was not working because the visibleItems kept returning the default processedItem rather than the items from the current processedItem. I removed the logic that was comparing the key with the focusedItem's parentKey. I don't know what that was doing but I manually tested the menu and also added a unit test. 
It would be great to have all the unit test fixed so it'll be easy to tell if a change has broken something or not.
> fix broken megamenu keyboard naviagation

- src/app/components/tree/tree.ts
Filter nodes when new data are added
fixes #15193
> Tree: Update filtered nodes on nodes value changes

- src/app/components/scroller/scroller.ts
This is the simplest fix #15395
> Bug #15395 - prevent division by zero Errors in Scroller when no itemSize provided

- src/app/components/calendar/calendar.ts
Fixes [#15487](https://github.com/primefaces/primeng/issues/15487)
Calendar component: date input value is removed when a date before min Date is entered when KeepInvalid has been set to true
> Fixes #15487 - Calendar component: invalid date value is removed even though KeepInvalid is true

- src/app/showcase/doc/orderlist/dragdropdoc.ts
> docs(orderlist): mention dependency on angular/cdk

- src/app/components/picklist/picklist.ts
fixes #15011 
onListFocus was using the index of the source list rather than the filtered list so was selecting a different item
> Fix PickList element selection problem after filtering with ScrollBar

- src/app/components/dataview/dataview.ts
Fixes [#15455](https://github.com/primefaces/primeng/issues/15455)
When adding the [rowsPerPageOption] to the p-dataview attribute list it is not loading the dropwdown. As rowsPerPageOption is being transformed into NaN
Remove transform numberattribute as it is unable to parse an array of numbers
> Fixed #15455 - DataView [rowsPerPageOption] not working

- src/app/components/tieredmenu/tieredmenu.ts
Resolves #15130 
This is my first contribution. Forgive me if I have failed to follow S.O.P.
This PR removes the `aria-level` attribute from the `<li>` items in the tiered menu component. The reason being that this attribute was flagged as incorrect by axe devtools (presumably due to the role attribute being incompatible with aria-level?)
> chore(tieredmenu): remove aria level attribute from list item

- src/app/components/table/table.ts
Fixes #15283
Refactored the `onRowMatchModeChange` method in the `Table` component. A check is now included to ensure `fieldFilter.value` is present before calling the filter function, preventing unnecessary filter function calls.
> Update table filter match mode behavior

- src/app/components/tooltip/tooltip.ts
> Fixed #15468 - Tooltip | tooltipEvent - focus | hover combined

- src/app/components/inputnumber/inputnumber.ts
FIXED  #15311 
The issue was essentially that each time a value was entered a RegExp would be used to replace the prefix and suffix with '' however the RegExp had the /g flag and as such would replace all occurances of the pre/suffix including any occurances entered by the user. I also fixed some issues around the use of backspace and delete keys when the selector was around the prefix and suffix
> Fixed inputNumber with numeric prefix is not working as expected 

- src/app/components/fileupload/fileupload.interface.ts
- src/app/components/fileupload/fileupload.ts
- src/app/showcase/doc/fileupload/templatedoc.ts
> Fixes #15435 - FileUpload | Templating enhancements

- src/app/components/calendar/calendar.ts
Fixes #14995 
Updated the calendar component to include keyboard navigation. Users can now utilize keys such as Page Up, Page Down, Home, and End to navigate through the calendar as mentioned in the issue description. The update also involves refactoring date formatting into dedicated functions to improve code readability and maintainability.
> Improve calendar keyboard accessibility

- src/app/components/steps/steps.spec.ts
- src/app/components/steps/steps.ts
> fix steps component unit tests

- src/app/components/dropdown/dropdown.ts
> fix(dropdown): apply ID to (editable) input element

- package-lock.json
- src/app/components/treeselect/treeselect.ts
https://github.com/primefaces/primeng/issues/15537
Also fixed that there were not onFocus and OnBlur Events
> fix(treeselect): #15537 ng-touch on treeselect

- src/app/components/skeleton/skeleton.ts
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.
#15535 issue has been close by this commit I've submitted. I've changed the type of the input parameter because I've seen that the skeleton file has already a shape …
> #15535 - skeleton value changed from a shape to string for rem values

- src/app/components/accordion/accordion.spec.ts
> Accordion: fix broken unit test

- src/app/components/fileupload/fileupload.ts
> fix(fileupload): improve spacing where image preview doesn't exist

- src/app/components/password/password.ts
> FIX:PasswordDirective loss PrimeNGConfig in constructor

- src/app/components/api/filterservice.ts
This fixes issue #15684 
I fixed it by making a copy of the value and setting the hours to 00:00 on that, then use that copy for comparison.
> Fix dateAfter filter changing date object hours

- src/app/components/contextmenu/contextmenu.spec.ts
> fix context menu unit tests

- src/app/components/tooltip/tooltip.ts
Updated logic of tooltip activeElement method to handle case of a non PrimeNG component.
The following Video shows the issue #15648 reproducer is fixed with this Pull Request:
https://github.com/primefaces/primeng/assets/45439491/080ab680-71da-4e52-8414-6f9730b64251
I also verified this fix against all the tooltip documentation examples
> fixed #15648 - fixed tooltip for custom component 

- src/app/components/editor/editor.spec.ts
- src/app/components/table/table.spec.ts
> fix Editor and Table unit test

- src/app/showcase/doc/table/filterbasic.ts
Fixes [issue](https://github.com/primefaces/primeng/issues/15626) around table basic filtering demo not loading.
Issue was with a duplicate @Component annotation.
> fix: remove duplicate @Component annotation from table filter basic demo

- src/app/components/dom/domhandler.spec.ts
In a PR 16 months ago the expect for this test was altered from 1 to 2. I can't seem to find any reason why, only one button is added, the 'a' and 'p' tags are not focusable so shouldn't impact this, as such I've changed it back
> Fixed Domhandler tests

- src/app/components/toolbar/toolbar.ts
- src/app/showcase/doc/toolbar/templatedoc.ts
Fixes #15608 
Add missing SharedModule import & export.
> Fixed #15608 - Add missing import & export of sharedModule

- src/app/components/slidemenu/slidemenu.spec.ts
- src/app/components/treetable/treetable.spec.ts
- src/app/components/treetable/treetable.ts
> Fix tree table unit test

- src/app/components/inputtextarea/inputtextarea.spec.ts
Fixes [#15605](https://github.com/primefaces/primeng/issues/15605)
> Input text area: fix unit test and expand on testing suite

- src/app/components/multiselect/multiselect.ts
Multiselect: selectionLimit not working if the value 0 is provided
[#15400 ](https://github.com/primefaces/primeng/issues/15400)
> Multiselect: selectionLimit not working if the value 0 is provided

- src/app/components/table/table.ts
This PR reverts the changes made in PR #15594
This PR also fixes issue #15778
This PR fixes the functionality of the PrimeNG's Table Advance Filters which was  "Critically" broken when trying to fix issue #15557.   Note:  PR #15594 actually only partially fixed issue #15557.
This PR also breaks issue #15557.  Since the problem identified in issue #15557 has been in PrimeNG for multiple years without being fixed,  I believe it is better to fix the Advance Filter immediately and in the future develop a more holistic/complete fix for issue #15557 that doesn't "critically" break  Advance Table Filters
> Fixed #15804 - Advance Filtering is broken (revert PR #15594 changes)

- src/app/components/button/button.spec.ts
- src/app/components/dom/domhandler.spec.ts
- src/app/components/dynamicdialog/dynamicdialog.spec.ts
- src/app/components/fileupload/fileupload.spec.ts
- src/app/components/multiselect/multiselect.spec.ts
- src/app/components/tree/tree.spec.ts
- src/app/showcase/layout/app.component.spec.ts
> fix broken unit tests

- src/app/components/multiselect/multiselect.ts
#15784 
fixes regressions in multi select icon templates
> Fixed #15784 fix CheckIcon is taking precedence over templates, and error on just having checkicon template

- src/app/components/inputnumber/inputnumber.ts
> fix: integer display when min/max fraction digits are set to 0

- src/app/components/button/button.ts
- src/app/showcase/doc/apidoc/index.json
fix #15736 
The button was not showing and now is adding correctly the text completed that you write in `icon` and `loadingIcon` attribute
> fix(Button):  The icon is not shown

- src/app/components/button/button.ts
This PR fixes Issue #15862.   
PR #15773 only partially fixed Issue #15736.  It fixed the loading icon when the p-button component (\<p-button\>)was used.  It did not fix the problem when a button with a pButton directive (\<button pButton\>) was used.
The first video shows the broken functionality before the fix.  Note:  all the p-button cases work properly.
The second video shows all the "loading" functionality working after the fix.
https://github.com/primefaces/primeng/assets/45439491/1be71c2e-d5d8-4942-abd9-83e151f4ca4e
https://github.com/primefaces/primeng/assets/45439491/fbe99956-1de2-4c9d-b454-d4ed54613e3e
> fixed 15862 - fixed loading button when using the pButton directive

- src/app/components/dom/domhandler.ts
Fixes #15877
SVG elements do not have an offsetWidth or offsetHeight property. So we have to use the getBoundingClientRect() method to get the width and height of the element
> Fix aligment of popup menu for svg

- src/app/components/accordion/accordion.ts
Fixes #15851
Fixes #15871
Fixes #15859
> Fixed #15851 - Component: Accordion

- src/app/components/dropdown/dropdown.spec.ts
- src/app/components/dropdown/dropdown.ts
This fixes #15762 where when the dropdown panel is open, the p-dropdown-open class is not added to the container. Also added a unit test to ensure functionality continues working in the future
> Fixed #15762 p dropdown open style missing from dropdown

- src/app/showcase/layout/menu/app.menuitem.component.ts
Fixing the issue #14259  of choosing steps in menu close the menu and routerlink active is not working.
> doc(Steps): fix the issue of menu closing when choosing steps component.

- src/app/components/table/table.ts
> Fixed #15903 - Table | Multiple Selection with dataKey shows wrong selected row count upon CTRL+A

- src/app/components/message/message.ts
- src/app/showcase/doc/apidoc/index.json
Fixes #15881 
Fixes #15534 
Fixes #15913 
A type mismatch in the message component is corrected, which also results in a severity error in the toast component.
> Message  | Fix type mismatch

- src/app/components/splitter/splitter.css
Setting `pointer-events` to none to the panels when resizing fixes this issue.
Closes: #15942
> fix(splitter): resize not working when iFrames are used in panels

- src/app/components/calendar/calendar.ts
- src/app/components/carousel/carousel.ts
- src/app/components/confirmdialog/confirmdialog.ts
- src/app/components/dialog/dialog.ts
- src/app/components/orderlist/orderlist.ts
- src/app/components/picklist/picklist.ts
- src/app/components/table/table.ts
- src/app/components/toast/toast.ts
Fixes #15965 
Correct order of actions for CSP
> Fixes #15965 - Fix order of actions for CSP

- src/app/components/image/image.ts
Fix #15993 
I moved a hardcoded style that was set using the `style` attribute, to the `ngStyle` attribute.
The whole description about the error is in #15993.
> p-image: Fix inline style not compliant with Strict CSP policy

- src/app/components/dialog/dialog.ts
> Fixed #15749 - Dialog: Focus to input element set before transition ends

- src/app/components/calendar/calendar.ts
- src/app/components/carousel/carousel.ts
- src/app/components/confirmdialog/confirmdialog.ts
- src/app/components/dialog/dialog.ts
- src/app/components/dropdown/dropdown.ts
- src/app/components/toast/toast.ts
> Fixed #15155 - Component: Dropdown Accessibility

- src/app/components/scroller/scroller.ts
Fixes [ #15647](https://github.com/primefaces/primeng/issues/15647)
> fix(autocomplete): dropdown height with virtual scroll

- src/app/components/accordion/accordion.ts
- src/app/components/autocomplete/autocomplete.ts
- src/app/components/chart/chart.ts
- src/app/components/contextmenu/contextmenu.ts
- src/app/components/dialog/dialog.ts
- src/app/components/dropdown/dropdown.ts
- src/app/components/dynamicdialog/dynamicdialog.ts
- src/app/components/listbox/listbox.ts
- src/app/components/megamenu/megamenu.ts
- src/app/components/menubar/menubar.ts
- src/app/components/multiselect/multiselect.ts
- src/app/components/progressbar/progressbar.ts
- src/app/components/slidemenu/slidemenu.ts
- src/app/components/speeddial/speeddial.ts
- src/app/components/table/table.ts
- src/app/components/tieredmenu/tieredmenu.ts
- src/app/components/tree/tree.ts
- src/app/components/treetable/treetable.ts
> Fixed #15998 - Inline style not compliant with strict CSP

- src/app/components/table/table.ts
#15937
create a filter base on p-columnFilter and set show buttons to false:
```
<p-columnFilter [showButtons]="false">
......
<ng-template pTemplate="footer">
</ng-template>
</p-columnFilter>
```
the output will render the div and will have extra padding based on styles.
> fixes #15937 Table: columnFilter

- src/app/components/multiselect/multiselect.ts
Fixes #16039
Added a check for NaN values.
Note:
I couldn't add new tests because my unit tests were not working locally.
When running `npm test`, I've got a lot of errors with this message: `export 'async' (imported as 'async') was not found in '@angular/core/testing'`
> fix(MultiSelect): Check for NaN values in isSelectionAllDisabled method

- src/app/components/keyfilter/keyfilter.ts
> fix(keyfilter): regex test with the correct value onKeyPress

- src/app/components/table/table.ts
#16020
Table: column-filter outside click does not close when it is inside a dialog component
> fixes #16020 Table: column-filter outside click does not close when it is inside a dialog component

- src/app/showcase/doc/fileupload/advanceddoc.ts
- src/app/showcase/doc/fileupload/templatedoc.ts
Fixed some typos. let me know if any issue has to be created.
Also wanted to make a first contribution.
Thank you
> docs(typo): from files to here to files here

- src/app/components/tabmenu/tabmenu.ts
this is a fix for tabmenu component which emits change event twice when an item is clicked. 
issue #16123
> tabmenu: fix emitting change event twice when clicking on item

- src/app/components/table/columnfilter.interface.ts
> Fix template names, fixes #16180

- src/app/showcase/doc/calendar/accessibilitydoc.ts
Fix typo in Popup Keyboard Support section.
This is my first contribution so please let me know if anything is required.
Thanks.
> Fix typo in calendar documentation

- src/app/components/scroller/scroller.ts
Fixes #16165 
no need to set fixed height when scrollHeight === '100%' (setSpacerSize()) which is coming from scrollHeight = flex of all other components.
This causes on first load to set height to static values instead of '100%'.
> When scrollHeight is '100%' setSpacerSize() should not set static height to the scroller

- src/app/components/autocomplete/autocomplete.ts
Fixes #16160
Fixes the linked issue by only preventing the propagation of the enter key if it was handled internally by the component.
> fix(autocomplete): enter keypress event

- src/app/components/autocomplete/autocomplete.ts
- src/app/components/overlay/overlay.ts
Fixes #15281
This PR fixes the mentioned issue & additionally a bug in the overlay which would close the panel & never open it again (when opening & closing before the animation finishes) as the internal state of the overlay was half opened / half closed.
Details:
`modalVisible` was `false` while `visible` was true. This basically "deadlocks" the overlay.
Also fixes the minlength behavior for when "0" is used as a value.
> fix(autocomplete): not opening on second click

- src/app/components/table/table.ts
> Change .innerHTML assignments in table.ts to .textContent

- src/app/components/menubar/menubar.ts
> Fixes #16201

- src/app/components/table/table.ts
> Fixes #16211

- src/app/components/table/table.ts
closes #16209 Table: Cannot set autoSize from ScrollerOptions,
I have checked that options is the latest p-scroller parameter in all other components, they are all correct except for the table component.
I moved the autoSize before lazy to keep in sync with other components but moving it anywhere before options will fix this issue.
By and large, in all components [options]="virtualScrollOptions" should be latest binding since angular write them by order from top.
> closes #16209 Table: Cannot set autoSize from ScrollerOptions

- src/app/components/editor/editor.ts
Fixes https://github.com/primefaces/primeng/issues/16114
> Fixed #16114 - Editor | hide primeng toolbar when insert quill modules.

- src/app/showcase/doc/table/paginatorprogrammaticdoc.ts
Fixes #16308 _- The example code for programmatically paginating trough tables, in the `isLastPage()` function, is flawed because it only works correctly when the amount of items in the table is an exact multiple of the rows per page count._
The new line correctly identifies the last page by checking if the index after the current page's last item reaches or exceeds the total length of the customers list.
The old line incorrectly identifies the last page, only working correctly when the amount of items in the table is an exact multiple of the rows per page count.
> Fix #16308: Flawed example in table paginator documentation

- src/app/components/tree/tree.ts
Fixes #16282 - When using loadingMode="icon", the spinning loading icon only appears on root items, not on child items.
The bug occurred due to not including loadingMode="icon" to the nested TreeNode component.
The new line forwards the loadingMode veriable to the nested TreeNode component.
> Fixed #16282 Loading icon does not show on child items

- src/app/components/megamenu/megamenu.ts
This PR fixes issue #16248.
This Issue #16248 was similar to closed Issue #16241.  As a result I used merged PR #16241 as a reference.
The video below shows the fix working:
https://github.com/user-attachments/assets/3ed703af-d9a2-4f4c-8539-14d0e5e3d685
> Fix #16248 - Removed aria-hidden attribute from MegaMenu

- src/app/components/splitter/splitter.ts
Fixes #16425
zero width panels are incorrectly parsed as null, and therefore incorrectly set to the default size. Switching over to the null coalescing operator will accept 0 as a valid size, and default only if the size was null.
> Enabled splitter to support zero width panels #16425

- src/app/components/autocomplete/autocomplete.ts
- src/app/showcase/doc/autocomplete/autocompletedoc.module.ts
- src/app/showcase/doc/autocomplete/dropdowndoc.ts
- src/app/showcase/doc/autocomplete/forceselectiondoc.ts
- src/app/showcase/doc/autocomplete/objectsdoc.ts
- src/app/showcase/doc/autocomplete/reactiveformsdoc.ts
- src/app/showcase/doc/autocomplete/showclear-doc.component.ts
- src/app/showcase/doc/autocomplete/templatedoc.ts
- src/app/showcase/doc/autocomplete/virtualscrolldoc.ts
- src/app/showcase/pages/autocomplete/index.ts
Fixes #16410 and adds new Autocomplete ShowClear documentation
> fix(#16410): Autocomplete Clear Icon correctly shown when value set programmatically

- src/app/components/contextmenu/contextmenu.ts
- src/app/components/dock/dock.ts
- src/app/components/megamenu/megamenu.ts
Fixes #16397
Removes the aria-hidden attribute from anchor elements in the ContextMenu, Dock and MegaMenu components.
> Fixes #16397: Removed aria-hidden attribute from ContextMenu, Dock, and MegaMenu

- src/app/components/table/table.ts
Fixes #15192
`shouldRenderRowGroupHeader` expects the `rowIndex` to be the absolute index (i.e. `first + rowIndex`)  when paginated.
The problem was that the `rowIndex` passed starts from `0` for every page, and the index calculation in the method then resulted in a negative number.
For expanded rows,  the method `getRowIndex` is used, which adds the starting offset (`first`) to the `rowIndex`.
This method is used here now as well.
> Fix #15192: Row grouping breaks after first page

- src/app/components/calendar/calendar.ts
change isYearSelected function so it doesn't break when no date(s) is selected yet
Fix for https://github.com/primefaces/primeng/issues/14233
> Fix #14233 - Component: Calendar Year picker

- package-lock.json
- package.json
- src/app/components/scroller/scroller.ts
- src/app/components/tsconfig.lib.json
Fixes #16246
Commit e7b611 introduced a regression in the size calculation for `TreeTable` component with a `"flex"` height configuration. The issue arises because the spacer size is no longer being updated correctly. As a result, the scrollbar resizes itself during scrolling, which causes jumping of the scrollbar.
I have replaced the window-size listener with a `ResizeObserver`, because the number of visible items in a `TreeTable` with virtual scrolling must get recalculated if the view size changes. The new observer should handle window size changes, important to the `TreeTable`, equally well.
> Fix #16246 TreeTable Spacer Size Calculation

- src/app/components/dropdown/dropdown.ts
Allows the dropdown to be filled by the user (in combination with `selectOnFocus` = `true`) with minimal keyboard input without showing the overlay panel. Usefull when the user already is familiar with the selectable options and just quickly wants to select a value and move on to the next input (e.g. via tab).
closes https://github.com/primefaces/primeng/issues/16462
> dropdown: added option to disable showing the panel on key down (#16462)

- src/app/components/table/table.ts
Fixes #15043
this.containerViewChild can be undefined so I added a check that it will not result in a error
> Fix check containerViewChild for undefined in saveColumnWidths

- src/app/components/panelmenu/panelmenu.ts
+ Adjusted panelmenu
+ Changed itemTemplate to TemplateRef as it is in the Panel Menu itself
+ Corrected item toggle to recreate the items with expand state and keep state correctly
Fixed https://github.com/primefaces/primeng/issues/16511 - PanelMenu not working in v18 beta
> Fixed primefaces#16511 - PanelMenu not working in v18 beta

- src/app/components/table/table.ts
> Fixed #16618 - Table | Bug on table checkboxes

- src/app/components/calendar/calendar.ts
- src/app/components/listbox/listbox.ts
fix for #16689 
This pull request fixes span duplication in ListBox component, new check was added to ensure olny desired span is being added.
(my apologies, by mistake I have added commit from another branch, which is reversed now)
> fix( #16689): duplicated span in ListBox component

- src/app/components/multiselect/multiselect.ts
Fix #14780 - Fix multiselect instantly call onModelTouched
> Fix #14780 - Fix multiselect instantly call onModelTouched

- src/app/components/inputnumber/inputnumber.ts
Fix for #16733
The component uses `getSelection()` which [is not supported](https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection#related_objects) in Firefox and Edge (Legacy). Does making `onInputKeyPress()` read `null` on selected texts.
Updated `onInputKeyPress()` for more browser agnostic approach.
> Fix: InputNumber(16733): unsupported `getSelection()` causes input unwritable

- src/app/components/tooltip/tooltip.ts
Fix for #16729 
I modified the behavior so that the `document:keydown` event listener is only active when the Tooltip is in `interactionInProgress` state. This change significantly reduces the number of active `@HostListener`, improving overall performance and preventing browser freezes.
> Fix: Tooltip[(16729): unresponsive browser if pressing ESC-key in combination with lots of tooltips or overlay panels

- src/app/components/carousel/carousel.ts
Fixes #16552
This PR addresses an accessibility issue in the p-carousel component, where interactive elements within hidden slides were focusable, triggering warnings in tools like Axe DevTools. The fix ensures that only active slides have tabindex="0", while inactive slides are set with aria-hidden="true" and tabindex="-1" to meet accessibility standards.
> Fix accessibility issues in Carousel component (issue #16552)

- src/app/components/autocomplete/autocomplete.ts
#16625
In an autocomplete input component, events can often lead to unintended order of execution, particularly when handling change and click events. When a user types in the input and then selects an item from the dropdown list, the change event fires first because it’s triggered as soon as the input field loses focus or updates its content. Then, the click event on the dropdown item is executed.
Problem:
change Event: This triggers first when the input value changes, such as when the user clicks outside the input or the dropdown, updating the internal value.
click Event on Dropdown Item: This triggers after the change event, potentially overriding or undoing the intended selection behavior.
Solution with mousedown Event:
To change the order and have the dropdown selection (click) …
> fix: In autocomplete dropdown, the item’s event has been changed from click to mousedown

- src/app/components/api/selectitemgroup.ts
Make `SelectedItemGroup` a generic, passing the type to `SelectItem`.
```ts
export interface SelectItemGroup<T = any> {
label: string;
value?: any;
items: SelectItem<T>[];
}
```
Fixes #16561
> SelectedItemGroup type as generic

- src/app/components/api/primeicons.ts
I started a related issue some minutes ago [here](https://github.com/primefaces/primeng/issues/16543)
Just to have a small recap here too, [primeicons.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/api/primeicons.ts) has a bugged value/keys with 3 icons.
Read related issue to a complete description
> Asterisk icon wrong key and value; arrow-h and arrow-v wrong key

- src/app/components/picklist/picklist.ts
**### Issue for this PR: https://github.com/primefaces/primeng/issues/16498**
The Movebottom Button in the picklist component references the wrong aria label.
Instead of 'Move Down' it should be 'Move Bottom'.
> fix: fixed label of movebottom-button in picklist component

- src/app/components/api/treenode.ts
- src/app/components/tree/tree.ts
Find the tree node's index programmatically based on its position within its parent, instead of using the ngFor array's properties because with virtual scroll, the list is flat and the indexes lost relativity to the tree node's parent.
#16296
> Fix indexing in the p-tree so drag and drop will work with virtual scroll.

- src/app/components/chips/chips.interface.ts
- src/app/components/chips/chips.ts
- src/app/showcase/doc/apidoc/index.json
This PR exposes contextmenu events on chips analog to existing click events. 
This is a small non-breaking change and completes the existing api for usages of the contextmenu on single chip items.
Closes [2791](https://github.com/primefaces/primeng/issues/16769)
> feat(chips): added onChipContextMenu output analog to onChipClick

- src/app/components/table/table.ts
Fixes #16734 by finding the parent TH element and using it as the resizeElement
> fix(table): column resize does not work with sortable columns

- apps/showcase/doc/theming/componentdoc.ts
This PR fixes a type in the Component section of the Theming documentation.
Changes "our" to "your" in the sentence "Overriding components tokens is not the recommended approach if you are building our own style, building your own preset should be preferred instead."
> fix(docs): typo in theming#component

- apps/showcase/doc/button/iconsonlydoc.ts
- Removes extra spacing 
- Renames "warning" to "warn" to match the `severity` type defined in 
https://github.com/primefaces/primeng/blob/6f926f194c970794d8829db0dfa204a526c187bb/src/app/components/button/button.ts#L150
Issue https://github.com/primefaces/primeng/issues/16645
> fix(docs): removes extra spacing and renames "warning" to "warn"

- packages/primeng/src/tabs/tab.ts
Fix for #16768 
**Solution Implemented**: added `p-disabled` to host class mapping.
> Fix: Tab[(16768): disabled input is not disabling tab

- src/app/components/inputotp/inputotp.ts
Resolves #16777 
Updated `length` validation for `onPaste()`.
> Fix: InputOtp[(16777): Length validation bypassed `onPaste`

- src/app/components/panelmenu/panelmenu.ts
Resolves #16781, resolves #15124
This is a separate PR to solve display and animation specific bug. The `expand` behavior is solved with #16790.
> Fix: PanelMenu(16781, 15124) - Submenu display and animation bug

- src/app/components/scroller/scroller.ts
Resolves #16438, resolves #16564
**Problem**: Missing optional chaining that causes `undefined` read on scroll update.
**Solution**: Fixed.
> Fix: Scroller(#16438 and #16564) - Scroll behavior bug

- src/app/components/package.json
Hi :)
Locally, I built a version and link it to a project and found out the current state of the lib is not fundamentally incompatible with Angular 19.
So I'm opening this PR so we can, if possible allow Angular 19 as a peer dependency, or at least have a place to discuss the issues encountered by those who have tried using PrimeNG with the latest version of Angular :)
I also posted a [message on Discord](https://discord.com/channels/787967399105134612/787967806367989790/1308595968182194270) about this
The first place I tried to look for information about Angular 19 support was in the Issues, 2nd was open PRs so if you think it's appropriate I can open an issue as well
Cheers
> feat(angular): allow/support Angular 19 with zone.js 0.15

- packages/primeng/src/panelmenu/panelmenu.ts
> Fixed #16683 | Panel Menu - wrong class when using routerLink

- packages/primeng/src/datepicker/datepicker.ts
When clicking on chevron buttons month (next / previous) an error is shown:
This commit resolves the issue taking into account that theming mentions the new token with `-button` suffix for both prev and next.
> fix(v18): Datepicker focus error #16590

- packages/primeng/src/panelmenu/panelmenu.ts
> Fixed #16882 - PanelMenu | Hover is not working on child items

- packages/primeng/src/autocomplete/style/autocompletestyle.ts
> Fixed #16846 | Autocomplete: dropdown arrow and clear icon overlap

- apps/showcase/doc/splitter/nesteddoc.ts
- packages/primeng/src/splitter/splitter.ts
- packages/primeng/src/splitter/style/splitterstyle.ts
Fixes #16526 , #16527 , #16893
> Fixes #16526 & #16527 & #16893 | Splitter

- packages/primeng/src/overlaypanel/overlaypanel.ts
- packages/primeng/src/popover/popover.ts
Fixes #15964 
This PR ensures that the component always listens to click events, regardless of whether the `dismissable` property is `true`. 
This change respects the current value of the dismissable property, even if it is updated dynamically after the OverlayPanel/Popover has been opened.
> Fixed #15964 - OverlayPanel, Popover | Respect current value of dismissable property

- .github/ISSUE_TEMPLATE/bug_report.yml
Providing a direct link to the `app.component.html` file ensures users can easily navigate to the key part of the template when creating or reproducing issues, reducing confusion and saving time.
> Update Stackblitz URL to Directly Open `app.component.html`

- src/app/components/tooltip/tooltip.ts
fixes #16630 
This fix improves accessibility by maintaining proper ARIA relationships for tooltips.
- Added `setAriaDescribedBy` to dynamically set `aria-describedby` attribute on the target element when the tooltip is created.
- Added `removeAriaDescribedBy` to remove the `aria-describedby` attribute when the tooltip is removed.
> fix(#16630): ensure aria-describedby is dynamically set and removed for tooltip

- src/app/components/autocomplete/autocomplete.ts
Issue reported here #16805
To handle `updateOn` setup with `blur` value, the following changes have been made:
1. Adapting the `onInputBlur` conditionally calling `onModelTouched` only if `forceSelection` is `false`.
2. Adding `onModelTouched` call in the `onSelect` ( unconditionally ), which provides the `FormControl` / `FormGroup` the value selected by the user, without considering the text input the user is searching ( unless forceSelection is false ).
This way was chosen because [NG_VALUE_ACCESSOR](https://angular.dev/api/forms/ControlValueAccessor#registerOnTouched) updates the ancestor calling `registerOnTouched` which by angular docs:
> When implementing registerOnTouched in your own value accessor, save the given function so your class calls it when the control should be …
> Fix autocomplete updateOn blur on select (#16805)

- src/app/components/scroller/scroller.ts
Resolves #16708, resolves #16727
**Problem**: `onResize()` is triggered first before `calculateAutoSize()`. While `onResize()` sets the height and width of scroller, **it's job is not to calculate and update the height/width** but to just identify if update is needed. The proper calculations actually happens in `calculateAutoSize()`.
**Solution**: Transferred the height/width update job to `calculateAutoSize()` to eliminate errors in height/width updates.
> Fix: Multiselect & Autocomplete(#16708 & #16727) - Scroller panel height bug

- src/app/components/panelmenu/panelmenu.ts
Resolves #15403
**Problem:**: The logic from `ngOnChanges()` forces the component to create new `processedItems` with `expanded: undefined`.
**Solution**: Added check to keep `expanded` properties.
_This is a possible solution for #16781 too, but I created another PR(#16791) with the fix for the `hide` animation._
> Fix: PanelMenu(15403) - Submenu displays angledownicon when submenu is collapsed

- src/app/components/inputotp/inputotp.ts
This PR addresses issue #16653. It modifies the InputOtp component to allow the Tab key to function correctly, enabling smooth navigation between OTP fields.
> Issue 16653 tab fix

- src/app/components/fileupload/fileupload.ts
FileUpload: Format file size to accept locale in error message: https://github.com/primefaces/primeng/issues/16382
> Accept the locale for the file size of the format

- src/app/components/multiselect/multiselect.ts
> Fix variable in getOptionValue in multiselect #16651

- packages/primeng/src/togglebutton/togglebutton.ts
> fix empty label render issue in togglebutton

- packages/primeng/src/picklist/picklist.ts
> fix: moveRight/moveLeft transferring only half of items after "Select All"

- packages/primeng/src/inputnumber/inputnumber.ts
The naming of the "incrementbuttonicon" content child has a typo:
Currently: "icrementbuttonicon"
Correct: "incrementbuttonicon"
edit: resolved conflicts with master
> fix (#17088): typo in input number component content child incrementbuttonicon

- packages/primeng/src/usestyle/usestyle.ts
> fix: useStyle when id undefined

- packages/primeng/src/select/select.ts
Closes #17178
**Problem:** `onModelChange `triggered because of depricated `autoDisplayFirst`.
**Solution:** Replaced with initial value check.
> Fix: Dropdown/Select(#17178) Marked as dirty on start

- packages/primeng/src/select/select.ts
Closes #17110
**Problem:**  Property `modelValue()` has empty string value on clear which prevents placeholder to show.
**Solution:**  Passed `null` to `updateModel()` when `value` is empty to properly update the input element.
A separate PR #17115 for V17 was created
> Fix: V18 Editable Dropdown(#17110) Placeholder bug

- package.json
Fixes error thrown by rimraf during repository setup with `npm run setup` in Windows environments #17186 
add `--glob` flag to rimraf call, as suggested by https://stackoverflow.com/questions/75281066/error-illegal-characters-in-path-in-npm-rimraf and documented at https://www.npmjs.com/package/rimraf
> add glob flag to rimraf call in clean command for windows compatibility

- packages/primeng/src/tree/tree.ts
#17132 
Move prevent default closer to the event's origin (checkbox). 
Was added here: 
https://github.com/qwadrox/primeng/commit/0f615c4bb2879213404115d34ab50d5001eae8d7
> #17132 Fix link would not work in Tree 

- packages/primeng/src/tag/tag.ts
Removes the deprecation warning from the icon property in TagComponent. Since it seems not to be deprecated (see #16220)
This is the fix for v19.
> Fix: Tag v19 (#17181): Remove deprecation warning from icon-property of TagComponent

- packages/primeng/src/select/select.ts
#17130
The goal was to ensure that it is possible to search backwards
https://github.com/user-attachments/assets/7ffb481d-e698-475c-a834-07965d3a5787
> #17130 Dropdown: Fix search

- packages/primeng/src/dialog/style/dialogstyle.ts
This pull request fixes issue #17193
The video shows the pull request fixes the reproducer that demonstrated the bug.
https://github.com/user-attachments/assets/5b9d0aab-c4df-49e1-8605-5d83e7da881c
Note:  I manually verified that this pull request doesn't break  PrimeNG's dialog and dynamic dialog demos
> fixed #17193: fixed rendering of dynamic dialog content

- packages/primeng/src/inputnumber/inputnumber.ts
Closes #17169
**Problem:** Input is marked dirty on blur. This is caused by `writeValue()` writing `this.value` as `string`.
**Solution:** Parsed value first before overwriting.
> Fix: InputNumber(#17169) InputNumber marked dirty on blur

- apps/showcase/pages/lts/index.ts
Revised the lifecycle information to reflect updated versioning. Adjusted the LTS and STS labels in the table to align with the new release schedule and added "Legacy" rows for deprecated versions.
> Update LTS version details and lifecycle table

- packages/primeng/src/tree/tree.ts
#17171
The goal is to keep the provided style and add to it --p-focus-ring-color value only if it's not set before.
> fix: #17171 Fix tree inline style overridde

- src/app/components/tree/tree.ts
[Component: SelectionTree, Bug when selecting something while having filtered value #16792
](https://github.com/primefaces/primeng/issues/16792)
Description of fix:
`propagateUp()` in `tree.ts` was calculating `node.children` incorrectly when figuring out if a node was partially selected. `propagateUp()` only needed tweaking in a couple spots to ensure it was referencing the original `node.parent` instead of the filtered one. Otherwise on filter, it would always assume `node.children` was equal to one and thus the issue would occur.
> 16792 Issue Fix - Tree select filtered value bug

- packages/primeng/src/select/select.ts
Closes #17112
Problem: `changeFocusedOptionIndex()` was not triggered properly if overlay is still in animation state.
> Fix: Dropdown(#17112) Autoscroll Bug

- packages/primeng/src/dynamicdialog/dialogservice.ts
Fixes https://github.com/primefaces/primeng/issues/16402
I'm not 100% sure why this works considering the component ref gets destroyed before calling it's change detector, but as far as i can tell it just works.
> Fix: Dynamic Dialog not being properly destroyed on close

- packages/primeng/src/select/select.ts
fixes #17218
PrimeNG Select Component - Missing Scroll to Selected Item 
Expected Behavior:
Upon opening the select component, the list should automatically scroll to the highlighted/selected item, ensuring it is visible without manual scrolling.
Current Behavior:
When the select is opened, the highlighted item is not brought into view. Users must scroll down manually to find the selected item, which can be inconvenient with large datasets.
> Fix #17218

- packages/primeng/src/datepicker/datepicker.ts
fix hideOnDateTimeSelect issue with range mode.
Fixes #17222
> fix: #17222, hideOnDateTimeSelect issue for range

- packages/primeng/src/inputnumber/inputnumber.ts
writeValue() must not parse the model value as it is expected to be a number already. Otherwise, all kinds of locale related issues may arise.
> fix: #17314 -  inputnumber model binding issue

- packages/primeng/src/rating/rating.ts
- packages/primeng/src/rating/style/ratingstyle.ts
Fixes primefaces#17315
This fixes the keyboard navigation for the rating component.
Part of the fix is using the value of a signal instead of the signal itself for comparison purposes (`focusedOptionIndex`). I fear that similar problems exists in other components as well—at least in `dropdownstyle.ts` a quick search yields a similar situation.
> fix: rating keyboard navigation, fixes primefaces#17315

- packages/primeng/src/datepicker/datepicker.ts
fix #17326
changed *ngIf="!decadeTemplate && _decadeTemplate" to *ngIf="!decadeTemplate && !_decadeTemplate">
This video shows the v19 PrimeNG DatePicker Basic dem's Decade title  working correctly after the fix.
https://github.com/user-attachments/assets/0d637d1d-d979-4a09-9d87-29d8a5b02089
> fix decade title logic, fixes #17326

- apps/showcase/doc/apidoc/index.json
The .json file was missing a part for selecting the active tab in css
> [FIX] add missing doc for active tab css selector

- apps/showcase/components/layout/designer/app.designer.component.ts
Fixes issue https://github.com/primefaces/primeng/issues/17285
1. Lookahead `(?!...)`:
- `(?!\w+\.\d+)` ensures the key does not match the pattern word.number (e.g., color.1).
- `\w+`: Matches one or more word characters (letters, digits, or underscores).
- `\.`: Matches a literal period (.).
- `\d+`: Matches one or more digits.
2. Adjusted Capturing Group:
- `((?!\w+\.\d+)[^"]+)`:
- Captures keys that do not match the \w+\.\d+ pattern.
- Ensures only valid keys are captured and replaced.
3. Replacement:
- `$1`: retains the captured group (key) and appends the colon.
> update designer json-to-js regex to allow keys with dot notation

- packages/primeng/src/drawer/drawer.ts
Closes #17242 .
Fixed mask's `zIndex` calculation.
> Fix: Drawer(#17242) - Mask zIndex calculation bug

- packages/primeng/src/tooltip/tooltip.ts
Closes #17243 
Fixed wrong parameter for `removeChild`.
> Fix: ToolTip(#17243 ) - AppendTo bug

- apps/showcase/doc/table/rowexpansiondoc.ts
Adjusting showcase code to use `rowexpansion` instead of `expandedrow`, according to the documentation.
> [...] To use this feature, add a template named **rowexpansion** and use [...]
Not really a "fix" as one word change in the showcase.
> docs: fix `rowexpansion` template name in showcase code

- apps/showcase/doc/dynamicdialog/passingdatadoc.ts
Updated the DynamicDialog documentation to include information about the inputValues property. Clarified its usage alongside the existing data property, explaining their differences and how they can be used together. Added in code example both properties in the DynamicDialog implementation.
> docs(dynamicdialog): update documentation to include inputValues support

- packages/primeng/src/inputnumber/inputnumber.ts
Upon testing I encountered a regression for my merged PR #17370 for issue #17314.
Setting the model value to null or undefined produced incorrect behaviour (value displayed as 0 or NaN).
> fix: issue from previous PR #17370

- apps/showcase/doc/apidoc/index.json
- packages/primeng/src/tree/tree.interface.ts
- packages/primeng/src/tree/tree.ts
_Related to [https://github.com/orgs/primefaces/discussions/3313](https://github.com/orgs/primefaces/discussions/3313)._
_This PR fixes #17401._
- Created `onNodeDoubleClick` emitter in Tree component.
- Thus created `TreeNodeDoubleClickEvent`.
> Add new emitter in Tree component: onNodeDoubleClick

- packages/primeng/src/table/table.ts
Changed operator to hide default if ng-template with  `#sorticon` OR `pTemplate="sorticon"` templates are provided in the component.
This is an enhancement of the fix for issue #17062
As the previous fix requires the both the template ref and ptemplate to be provided in order to hide the default sort icons.
``` 
<ng-template #sorticon pTemplate="sorticon">
...
</ng-template>
```
> Fix: Table(#17062) | Adding custom sorticon should replace default sorticon.

- packages/primeng/src/stepper/stepper.ts
Fixing: https://github.com/primefaces/primeng/issues/17482
> fix: make isSeparatorVisible full signal #17482

- packages/primeng/src/listbox/listbox.ts
> fix: remove aria-hidden from listbox focusable content

- packages/primeng/src/menu/menu.ts
Fixes: https://github.com/primefaces/primeng/issues/17262
Changes made to fix the Issue:
- Simplified the `hasSubMenu()` method for better readability and performance.
- Update the `submenu` visibility condition to correctly handle edge cases.
> fix(p-menu): menu item visible flag logic

- packages/primeng/src/select/style/selectstyle.ts
Closes #17382
**Problem:** `p-select-overlay` inherits `cursor: pointer` from `p-select`.
**Solution:** Added default cursor.
> Fix: Select(#17382) Clickable Empty Message Label

- packages/primeng/src/dragdrop/dragdrop.ts
Changing the value of pDroppableDisabled after ngAfterViewInit has no effect. This commit replicates the behaviour of pDraggableDisabled to bind and unbind the listeners on value change
> Fix detection of pDroppableDisabled change after ngAfterViewInit

- apps/showcase/doc/dataview/basicdoc.ts
- apps/showcase/doc/dataview/paginationdoc.ts
Fix #17621: Two examples in the [DataView component](https://primeng.org/dataview) have double class attributes, likely a copy-paste error. This issue / bug report exists because it is required for the PR I am creating to fix this documentation error.
This is a line the current documentation:
```html
<div class="col-span-12" *ngFor="let item of items; let first = first" class="col-span-12">
```
This is my proposed fix:
```html
<div class="col-span-12" *ngFor="let item of items; let first = first">
```
With kind regards
> Fix #17621: Removed duplicate class attribute in examples of DataView

- packages/primeng/src/dataview/dataview.ts
This update normalises the reference variable name of the loading icon template, which currently is "loadingIcon" but should be "loadingicon", following the same standard as other variable names.
> Updates Loading Icon template reference variable

- packages/primeng/src/datepicker/datepicker.ts
it was impossible to focus month or year using keyboard arrow keys/tab, due to incorrect class names in `updateFocus` method. this PR updates the class names according to new theming.
Fixes #17663
> fix: #17663 - month, year picker keyboard focus issue

- packages/primeng/src/iftalabel/style/iftalabelstyle.ts
**Fix solution for issue:**
https://github.com/primefaces/primeng/issues/17751
**Problem:**
When using the Select component with a filter within an Iftalabel, the search field appears in the IftaLabel pattern with padding top without the label.
**Solution:**
CSS adjustment so padding affects only first child element.
---
> Fix: Issue#17751 - Inftalabel affected nested inputtext in Select Component.

- packages/primeng/src/basecomponent/basecomponent.ts
[Issue 17645](https://github.com/primefaces/primeng/issues/17645)
Memory leaks are occurring in all components using BaseComponent because ThemeService was not being released.
As a fix, I modified it to call ThemeService.off within ngOnDestroy.
> fix: Fixed BaseComponent | release ThemeService

- packages/primeng/src/accordion/accordion.ts
Fixes [[Accordion] onOpen and onClose events emit wrong index value #17866](https://github.com/primefaces/primeng/issues/17866)
> Fixes #17866 - Emit correct index value when an AccordionHeader is clicked 

- packages/primeng/src/drawer/drawer.ts
Fixes https://github.com/primefaces/primeng/issues/17840
It appears this line was being set to solve a similar issue that was run into before with the drawer but only when the overlay mask was being applied. Moved this line out into the show handler so it covers both modal/non-modal cases.
> fix: dt styles not loading for drawer set to [modal]="false"

- packages/primeng/src/splitter/splitter.ts
- packages/primeng/src/stepper/stepper.ts
I believe this will fix issue #17759 where we are referencing classes before they've been defined. This causes issues when running unit tests with jest and receiving the error:
```
ReferenceError: Cannot access 'Splitter' before initialization
```
and
```
ReferenceError: Cannot access 'Step' before initialization
````
> v19.0.7+ Fixing issue #17759 where we are referencing classes that havent been defined yet

- packages/primeng/src/dialog/dialog.ts
fix #17301
Animations if they are quickly changed between they lost sync because they are not done programatically.
> fix(dialog): Ensure mask visibility state is consistent with dialog visibility

- apps/showcase/doc/paginator/basicdoc.ts
- apps/showcase/doc/paginator/currentpagereportdoc.ts
- apps/showcase/doc/paginator/imagesdoc.ts
- apps/showcase/doc/paginator/templatedoc.ts
The current paginator documentation, shows the practice of manually defining a type interface in every example where the paginator is used, for the `onPageChange($event)` event emitter. In every example, the type of `$event` is manually defined like so:
```ts
interface PageEvent {
first: number;
rows: number;
page: number;
pageCount: number;
}
...
onPageChange(event: PageEvent) {
this.first = event.first;
this.rows = event.rows;
}
```
Since PrimeNG internally uses its own interface definition for this event, manually defining it in the users' project code could lead to errors in future updates where PrimeNG changes its internal interface for the `onPageChange($event)` event emitter. Having users use their own defined type would undo the benefits of typed javascript, as it would obscure …
> Use PrimeNG's interface in examples, instead of manually creating a duplicate (bad practice in documentation)

- packages/primeng/src/iftalabel/style/iftalabelstyle.ts
**Fix solution for:**
https://github.com/primefaces/primeng/issues/17841
Problem:
After correcting the iftalabel for the filter field in the multi-select select components, a side effect occurred in other components.
Solution:
It was necessary to style the individual components and in the iconfield component it was necessary to style only the next element, the same as with inputText.
Screens:
Autocomplete:
CascadeSelect:
Datepicker:
Iconfield:
InputGroup:
InputMask:
InputNumber:
InputText:
MultiSelect:
Password:
Select:
TreeSelect:
> Fix: Inftalabel for other fields caused by PR#17755

- packages/primeng/src/autocomplete/style/autocompletestyle.ts
> fix: Set the opacity to `1` for disabled autocomplete inputs

- packages/primeng/src/calendar/style/calendarstyle.ts
- packages/primeng/src/cascadeselect/style/cascadeselectstyle.ts
- packages/primeng/src/checkbox/style/checkboxstyle.ts
- packages/primeng/src/datepicker/style/datepickerstyle.ts
- packages/primeng/src/inputmask/style/inputmaskstyle.ts
- packages/primeng/src/inputnumber/style/inputnumberstyle.ts
- packages/primeng/src/listbox/style/listboxstyle.ts
- packages/primeng/src/multiselect/style/multiselectstyle.ts
- packages/primeng/src/radiobutton/style/radiobuttonstyle.ts
- packages/primeng/src/toggleswitch/style/toggleswitchstyle.ts
- packages/primeng/src/treeselect/style/treeselectstyle.ts
Add missing css rules to allow the ng-invalid markings also for alternative supported selectors of components where these rules were missing
> Add missing ng-invalid css rules for alternative component selectors

- packages/primeng/src/tooltip/tooltip.ts
changed how tooltip identifies if is attached on primeng componentnt from includes("P-") to startsWith("P-") because even "app-component" is identified as primeng component.
That causes a wrong alignment on non-primeng components
#17980
> fix: changed how tooltip identifies if is attached on primeng component

- packages/primeng/src/multiselect/multiselect.interface.ts
Fixes #17892 - `selectedItems` template has incorrect casing in the docs.
> Fix docs for selecteditems template in multiselect

- packages/primeng/src/carousel/carousel.ts
Sets the correct value for aria-hidden on carousel items depending on the visibility of the item.
> fix: set correct aria-hidden value on carousel items

- packages/primeng/src/menu/menu.ts
fixes #17782 
Fixes a bug when using one menu for multiple targets in popup mode:
p-menu in popup mode does not close on scroll in some cases.
Szenario: 
you have 2 scrollable lists with items inside.
there is one menu with `[popup]="true"`
clicking on an item will trigger menu.show() and it will show some menu entries.
Steps that lead to the faulty behaviour:
- click on an item of the first scrollable list 
- menu appears
- scroll on the first list
- menu disappears
- click on an item of the second scrollable list
- menu appears
- scroll on the second list
- !!!!!!!!!!! menu does not disappear !!!!!!!!!!
- scroll on the first list
- ????? menu disapperas ?????
The reason is that the scrollHandler still has the reference to the list item of the first list.
This is bad for two reasons:
- …
> fix: remove scrollHandler on unbind

- apps/showcase/doc/tabs/tabmenudoc.ts
In the example provided in the docs, data is accessed in the template but this data and its format is not reflected in the typescript file. This would fix this inconsistency.
> fix: Add missing data in example tabmenudoc.ts

- packages/primeng/src/base/style/basestyle.ts
fixed #18033 
After analyzing v17 which did not have this problem,  I determined that some CSS was inadvertently removed.  The fix was to add back the missing CSS.
The video listed below shows the functionality working properly after the code fix
https://github.com/user-attachments/assets/d3ad67fd-995f-4377-a495-a856cdb2b965
> fixed #18033 - DynamicDialog selects content when resized

- packages/primeng/src/orderlist/orderlist.ts
Added missing empty and emptyfilter templates to orderlist
fixes #17955
> fix(orderlist): added missing empty and emptyfilter templates to orderlist

- packages/primeng/src/treetable/treetable.ts
This PR fixes an issue where TreeTable expand icons were misaligned when using **RTL mode**. The issue was caused by a hardcoded `margin-left`, which didn't adapt to the text direction.
- **Replaced** `[style.marginLeft]` with `[style.marginInlineStart]` in `p-treetable-toggler`.  
- **Ensures proper indentation** for child expand icons in **both LTR and RTL** modes.  
- Fixes incorrect alignment where child icons appeared **directly under parent icons** in RTL.
Fixes #17780
- This change is **fully backward-compatible** with LTR behavior.  
- No breaking changes.
> fix(TreeTable): Use margin-inline-start for proper RTL alignment

- packages/primeng/src/megamenu/megamenu.ts
fixes  #18060 
removed aria-hidden = true for megamenu routerlink
The following video shows  the changes fixes the issue:
https://github.com/user-attachments/assets/bdfd594e-b925-4638-af1d-41bb54349b54
> fix #18060 - remove aria-hidden = true for megamenu routerlink

- packages/primeng/src/menubar/menubar.ts
Fixes #16451
Remove unsupported `aria-level` attribute from MenuBar component.
* Remove `aria-level` attribute from `packages/primeng/src/menubar/menubar.ts` for items with `role="menuitem"`
> Remove unsupported ARIA attribute from MenuBar Fixes #16451

- packages/primeng/src/inputnumber/inputnumber.ts
There have been some long-standing issues with InputNumber for nearly four years. I finally tracked it down to some flawed logic in concatValues.
**To Reproduce**
[Navigate to the _Prefix and Suffix_ section of the InputNumber docs](https://primeng.org/inputnumber#prefixsuffix) and enter a 4-digit number in the "Mile" field. The insertion point jumps past the suffix.
This should resolve quite a few issues that don't necessarily seem related. At a minimum, it has been causing caret positioning issues when decimal places or suffixes are enabled. I will try to search for and tag as many related issues as I can. There are also some issues that were marked fixed that were not, so I'll tag those too.
This fix should also be pushed to v17 and v18 branches.
**Open Issues**
Fixes #16189
Fixes …
> fix: critical flaw in InputNumber.concatValues()

- packages/primeng/src/config/primeng.ts
Fixes an issue where setting the filterMatchModeOptions via the PrimeNG config would not work because the value was never set internally.
> fix(table): fix filterMatchModeOptions not being set in setConfig

- packages/primeng/src/togglebutton/togglebutton.ts
Fixes #18152 by resolving the [binding collision](https://angular.dev/guide/components/host-elements#binding-collisions)
> fix: toggle-button missing disabled attribute #18152

- packages/primeng/src/selectbutton/selectbutton.ts
fix #18211
This PR  preserves the  fix made for Issue #17576 (PR #18148) when multiple=true and reverts back to  PrimeNG v19.1.0 logic when multiple=false
The video  shows the reproducer working after the fix.
https://github.com/user-attachments/assets/7a2c3ced-0916-4a87-99d0-9368656cce12
> fix #18211 :  fix SelectButton when allowEmpty=false and multiple=false

- packages/primeng/src/accordion/accordion.ts
Fix #18296
Fixed memory leak in AccordionContent  component.
While investigating the memory leak I determined the problem was caused by the component's use of animation.   I initially assumed the problem was caused by the implementation of signals.  I confirmed that signals was not causing the problem.  I then compared the current v19 Accordion code with the deprecated AccordionTab, since v17 PrimeNG demo didn't have the memory leak.  The difference between the animation implementation was that v17  animation was attached to the content **DIV** and v19 animation was attached to the host.  Moving the animation back to the content **DIV** fixed the memory leak.
The video listed below shows this PR fixes the  memory leak is fixed
https://github.com/user-attachments/assets/2f90d57a-4449-406e-9 …
> fix #18296: fixed Accordion Memory Leak

- packages/primeng/src/divider/divider.ts
- packages/primeng/src/menubar/menubar.ts
- packages/primeng/src/treetable/treetable.ts
A follow on to https://github.com/primefaces/primeng/pull/18570 in order to apply this fix to all other affected components.
See angular docs here:
https://angular.dev/best-practices/a11y
https://github.com/primefaces/primeng/issues/18579
1. `Divider`
2. `MenubarSub` within menubar
3. `TTSelectableRow` and `TTRow` within treetable
> Fix: Attribute binding - use [attr.aria-xxx] instead of [aria-xxx] to comply with Angular template validation and support strict mode testing.

- packages/primeng/src/datepicker/datepicker.ts
- The @Input() defaultDate property was declared as Date but the PrimeNG docs state its default value is null.
- Passing null currently causes a type error, which contradicts the documented behavior.
- This PR corrects the mismatch by changing the getter/setter signature to accept Date | null.
(I'm creating an issue right away)
> fix: allow defaultDate to be null in DatePicker component

- packages/primeng/src/checkbox/checkbox.ts
fixes #18284 
There were two templates in the p-checkbox component: `icon` and `checkboxicon`. Only the `icon` template is documented. I changed the `@ContentChild` selector to `icon` so the template can be set with `<ng-template #icon>`.
> fix: #18284 - Checkbox: fix icon template, remove checkboxicon template

- packages/primeng/src/treeselect/style/treeselectstyle.ts
Adds the class name for the clear icon in the TreeSelect component.
fixes #18735
> fix: 18735 - Adds clear icon styling to TreeSelect

- packages/primeng/src/accordion/accordion.ts
fix #18741
By replacing:
**padding-block** with with **padding-block-start** and **padding-block-end**
**border-block-width** with **border-block-start-width** and **border-block-end-width**
fixes the warnings.
**Note:  I believe that the original implementation is equivalent to the new implementation.  I have no idea why the original implementation would generate console warnings  and this fix does not.**
The video below shows that no warnings are generated after the fix (when running the PrimeNG Accordion Demo in Developer Mode):
https://github.com/user-attachments/assets/1532a82e-ac47-485e-97d0-d13a64d96fd7
The video listed below verifies this fix doesn't reintroduce the Accordion Memory Leak:
https://github.com/user-attachments/assets/bb59f604-37d3-4803-a6b4-793b7c1b44ba
> fixed: #18741, fixed Accordion Console Warnings

- packages/primeng/src/dialog/dialog.ts
by using same logic in p-dialog that is also applied in p-dynamicdialog (z-index based check if dialog should be closed, e.g. when calendar is open inside dialog)
https://github.com/primefaces/primeng/issues/16955
> fix: Dialog: Escape listener closes everything always https://github.com/primefaces/primeng/issues/16955 

- packages/primeng/src/dialog/dialog.ts
Fixes the issue where the Dialog component did not reliably autofocus the first focusable element when the `focusOnShow` property was enabled.  
This ensures that keyboard users and screen readers are immediately placed inside the dialog content when it appears.
This addresses the existing issue [#18816].
---
- **Restored autofocus behavior:**  
Updated the dialog logic to ensure the first focusable element receives focus when `focusOnShow` is `true` and the dialog is shown.
- **Improved accessibility:**  
Guarantees that keyboard navigation starts inside the dialog, not on the previously focused element.
- **Verified the change in the showcase app:**  
Confirmed that focus is correctly set to the dialog content on show.
---
- Only affects the **Dialog** component.
- No breaking changes; …
> fix/restore autofocus on focusOnShow property

- packages/primeng/src/multiselect/style/multiselectstyle.ts
It is currently always applying the p-variant-filled class if _any_ value is provided in the variant.
You can see from the references - https://github.com/search?q=repo%3Aprimefaces%2Fprimeng%20p-variant-filled&type=code) it should be comparing to `filled` to match all the other components.
> Fix p-multiselect to only use p-variant-filled when appropriate

- packages/primeng/src/autocomplete/autocomplete.ts
fixes #16570 again for v19 (it was previously fixed for v17 but somehow broken in v19 again)
> fix(16570): Autocompete: do not clear whole input on backspace

- packages/primeng/src/menu/menu.ts
when item.escape === false sanitizeHtml is undefined resulting in exceptions
Closes #18836
this probably occurs because a function outside a component is not avaliable in a components template. Moreover this wouldn't have worked anyways, even if it would have been avaliable for the template, because inside the function inject() is called outside the injection context of angular.
> fix(Menu): fixes sanitizeHtml is undefined

- packages/primeng/src/tabs/tablist.ts
This pull request makes a small but important change to the `TabList` component in `tablist.ts` to improve the precision of scroll button state calculation.
* [`packages/primeng/src/tabs/tablist.ts`](diffhunk://#diff-001e0f27b24210e78810794c168e2a487ee37be1f06fd17f36981a3344fd4f09L179-R179): Updated the condition for enabling the "next" scroll button to use `Math.abs` for comparing `scrollLeft` and `scrollWidth - width`, ensuring a more accurate calculation with a tolerance of 1 pixel.
> fix: tab list next button visibility
